gfx-rs/naga

src/front/spirv.rs, src/front/wgsl.rs, src/lib.rs
This PR gets us the remaining bits required to parse "boids.wgsl" 🎉 
It also improves IR a bit:
- adds notion of local variables to function, instead of the variable statements
- adds loops
We can add "test-data/*.wgsl" to automated testing now.
It will probably needs some work before we are able to generate a sensible SPIR-V, but architecturally we are almost there.
=> [wgsl] control flow parsing

src/front/spirv.rs, src/front/wgsl.rs, src/lib.rs, src/proc/mod.rs, src/proc/typifier.rs
There is a [small TODO](https://github.com/gfx-rs/naga/blob/76eb307d350e63073bd378e0d2d4fc7d2e5676f9/src/front/wgsl.rs#L526) in the current WGSL parser:
```rust
Token::Separator('.') => {
let _ = lexer.next();
let _name = lexer.next_ident()?;
let expr = crate::Expression::AccessIndex {
base: handle,
index: 0, //TODO: compute from `name`
};
handle = ctx.expressions.append(expr);
}
```
We have a base expression, and we need to access a sub-field. The IR doesn't care about names, so in case of a structure it just needs an index into the member list. The problem, however, is realizing that the base type *is* a structure. In order to compute them, we essentially need to know all the types of all the expressions.
This is where `Typifier` comes in. It's a generic processor of IR that helps to …
=> Typifier skeleton

src/back/msl.rs, src/front/spirv.rs, src/lib.rs, src/proc/typifier.rs, tests/convert.rs
We now have a more powerful `Binary` expression type.
This PR also adds quad -> MSL conversion to the tests. This is strictly better than running it in the example, since the example isn't supposed to have any shader-specific information. Yet, the binding mapping is required. So the example would need to support some sort of a RON input with the binding map, but the tests can just have all of it specified in the code.
=> Remove Expression::Mul

src/back/msl.rs, tests/convert.rs
This PR upgrades the Metal backend to the point of producing *a* result for "boids" without panicing. There is still work to be done before this result is valid and can be consumed by Metal SDK. In the meantime, the tests now do the check for "boids" to ensure we can always convert.
=> [msl] operators, array access, and built-in calls

src/back/msl.rs, src/front/spirv.rs, src/front/wgsl.rs, src/lib.rs, src/proc/interface.rs, src/proc/mod.rs
This is a pass over the function statement and expressions that gathers all the used global variables for inputs and outputs. WGSL today doesn't provide these explicitly (see https://github.com/gpuweb/gpuweb/issues/592), so we need to derive them.
=> Interface processor

src/arena.rs
This PR makes a `Handle`'s index to be stored using `NonZeroU32`, by using the 1-based position in the `Arena`. Fixes #21.
The `Handle.index(self)` function has been changed to return the 0-based index, otherwise it would break the code with look-up tables for indexes.
I also ran `cargo fmt` on the file, which changed some of the formatting.
=> Use `NonZeroU32` for handle index

src/front/wgsl.rs, src/lib.rs
Fix #42 
Reduces the amount of duplicate information in the IR module. Constants and Global Variable arena now only contains unique values.
Also did this for expression to reduce duplicate expressions, but I am not sure if we would want that. Could there be a case where duplicate expressions are acceptable?
Note: Boids IR has been decreased by about ~300 lines.
=> Reduce duplicate values in IR module

src/back/spv/helpers.rs, src/back/spv/layout_tests.rs, src/back/spv/mod.rs, src/back/spv/writer.rs
- Add Physical Layout test
- Add Instruction tests
- Add Logical Layout test
I am not sure if we have `cargo test` already enabled for CI, but here are some tests for the SPIR-V back-end. The file layout.rs is completely tested.
=> Add Layout Tests

src/back/spv/layout.rs, src/back/spv/layout_tests.rs, src/back/spv/mod.rs, src/back/spv/test_framework.rs, src/back/spv/writer.rs
Added a basic test framework and already tested the most basic function for the SPIR-V back-end. The more complex ones will take too much time for now for what it is worth at the moment, as they are complex, they most likely will be refactored to smaller and simpler function when I am continuing with compiling the Boids example.
The writer tests will enforce basic spec requirements like Op code correctness, Word count correctness, and a simple check if a instruction is supposed to have: a result id, type id and/or operands. This can potentially be expanded on, to also include type correctness, and maybe some more things I cannot recall now.
The tests also include instruction correctness, which ensures the instruction data is correctly positioned in the output stream.
=> Add basic tests for SPIR-V back-end writer

src/back/spv/writer.rs, tests/convert.rs
Adds support for `Statement::Return { Some(value) }` in SPIR-V backend.
I've added a test to `convert.rs`, which tries to parse the `glsl_phong_lighting.frag` file (with the `glsl` feature) and then convert it to SPIR-V.
After the changes, the test no longer panics on return with value statement. It does fail on `not implemented: Divide`, so I've set it to be ignored.
=> Add support for return value to SPIR-V backend

Cargo.toml, README.md, examples/convert.rs, src/back/mod.rs, src/back/msl.rs, src/back/spv/writer.rs, src/front/glsl/helpers.rs, src/front/glsl/mod.rs, src/front/mod.rs, src/front/spv.rs, src/front/wgsl.rs, src/lib.rs, tests/convert.rs
Closes #70 
I think it's much nicer now, since we can make IR tighter with respect to various enumeration modes we used to borrow from SPIR-V.
=> Remove spirv-headers use from IR, make it optional

Cargo.toml, src/front/glsl/helpers.rs, src/front/glsl/mod.rs, src/proc/typifier.rs
I tried adding some stuff to the GLSL frontend, but I got annoyed with tracking down all the unwraps so I refactored the error handling. Let me know if you want any changes or if this is even a good direction to go in.
It also contains a few additions to the type checker and support for two unary operations, which is what I was adding when I got sidetracked. I can move them to another PR if you want.
=> Refactor error handling in GLSL frontend

fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/spv_parser.rs, fuzz/fuzz_targets/wgsl_parser.rs
Adds some `cargo-fuzz` targets for the SPIR-V and WGSL parsers.
=> Add fuzzing support

src/front/glsl_new/error.rs, src/front/glsl_new/mod.rs, src/front/glsl_new/parser.rs
Adds pomelo parser error handling for glsl.
Can now generate errors like:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: InvalidToken(Comma(TokenMetadata { line: 3, chars: 23..24 }))
}', examples/convert.rs:58:25
```
=> Handle glsl_new parser errors

Cargo.toml
- Require 4.1 as 4.0 now gives compile errors
=> Make glsl dep more specific

src/front/wgsl.rs
Until now the WGSL parser would interpret a character index as a byte index.
This could lead to a panic on invalid input strings like "\"\u{2}ПЀ\u{0}\"",
because it would use that index to slice a string without ensuring the slicing
happens on a character boundary.
One possible fix would have been to call `str::find` instead of `position`,
however by relying on `splitn` instead of slicing a str manually it is
easier to convince ourselves that this code can no longer panic.
Fixes https://github.com/gfx-rs/naga/issues/90
=> WGSL front end: Fix panic on invalid input

src/front/wgsl.rs
Add some basic lexer tests while we're at it.
=> WGSL front end: Only accept ASCII chars in identifiers

src/back/spv/layout.rs, src/front/glsl/mod.rs, src/front/glsl_new/parser.rs, src/front/spv.rs, src/lib.rs
=> Deny on panics with clippy

src/back/msl.rs, src/front/glsl/mod.rs, src/front/spv.rs, src/front/wgsl.rs, src/lib.rs, src/proc/typifier.rs
Plus some SPV front-end refactor in preparation to the control flow graph.
Note that SPIR-V allows function calls into future-defined functions, so we have to do some gymnastics in order to handle that. We collect all the local function calls and resolve them at the end of the module parsing.
=> Local function calls in IR

src/front/glsl/mod.rs, test-data/glsl_constant_expression.vert, tests/convert.rs
Adds constant evaluation for addition, and uses it for globals and array
specifiers.
=> Initial GLSL constant evaluation implementation

src/back/spv/writer.rs
With the change of the bits to Bytes in the IR, the SPIR-V back-end failed to correctly validate OpTypeFloat and OpTypeInt. Their width operand requires the bits, not the bits.
=> Fix SPIR-V back-end, width will now be multiplied by 8

src/front/wgsl.rs, src/proc/typifier.rs
While working on error types for `wgpu-core`, I needed to implement a `From` conversion from `ParseError`. This type was lacking a `Display`/`Error` implementation, so I've added it in this PR.
=> Implement `Error` for `wgsl::ParseError`

src/front/glsl_new/ast.rs, src/front/glsl_new/error.rs, src/front/glsl_new/parser.rs
Make the parser generate naga statements and expressions.
Still lots of disabled stuff, as well as todos and not implemented errors.
But it now fully parses `simple.vert`, generating working naga IR :)
After this PR probably time for adding some tests, before looking at refactoring. Main issue is that some of the grammar expression rules need to generate both naga expression and statements. I think will need something like a scope stack that can be passed around, so individual rules can easily add statements to current scope.
=> [glsl-new] Add initial handling of stmts and exprs

src/front/wgsl.rs
Add mat2x3, mat2x4, mat3x2, mat3x4, mat4x2, and mat4x3 keywords.
Updating the WGSL front-end to support all the matrices keywords, see [keywords](https://gpuweb.github.io/gpuweb/wgsl.html#keywords).
=> Add support for other matrices keywords

src/front/glsl_new/ast.rs, src/front/glsl_new/error.rs, src/front/glsl_new/parser.rs
I think this was the biggest remaining issue I needed to figure out - the rest should more or less be just work 😊
Probably also a good time to start figure out some proper tests.
=> [glsl-new] Handle local vars scopes

src/back/glsl.rs
Add support for local variable initialization to glsl backend.
Input glsl:
```glsl
#version 450 core
layout(location = 0) in vec2 position;
void main() {
float w = 1.0;
gl_Position = vec4(position, 0.0, w);
}
```
Before patch, converted to:
```glsl
#version 450 core
layout(location=0) in vec2 position;
void main() {
float w;
gl_position = vec4(position,0,w);
}
```
After patch, converted to:
```glsl
#version 450 core
layout(location=0) in vec2 position;
void main() {
float w = 1;
gl_position = vec4(position,0,w);
}
```
=> Add support for initialization of local variables to glsl backend

src/front/glsl_new/ast.rs, src/front/glsl_new/parser.rs
Fix issue with `Compose` expression depending on later expressions.
Now `Compose` isn't generated until all args have been collected.
=> [glsl-new] Fix expression ordering for compose

src/front/glsl_new/parser.rs
`constant_expression` wasn't really working, it would make unnecessary entries in constants and expression arenas - further complicating potential Rosetta testing.
For now disable this and make layout qualifiers use `IntConstant` directly.
=> [glsl-new] disable constant expression

src/front/glsl_new/lex.rs, src/front/glsl_new/parser.rs
Redesign of the previous patch (sorry about that) that makes type handling more generic and adds support for matrices.
=> Make type handling more generic in glsl-new

src/back/spv/writer.rs, src/lib.rs
=> Spirv lookup refactor

examples/convert.rs, src/back/glsl.rs, src/back/spv/writer.rs, src/front/glsl/mod.rs, src/front/glsl_new/ast.rs, src/front/glsl_new/lex.rs, src/front/glsl_new/parser.rs, src/front/spv.rs, src/front/wgsl.rs, src/lib.rs
This pr adds interpolation qualifier support to naga itself, as well as all frontends and all backends except `msl` (I don't know `msl` well enough). You may notice that includes `wgsl`. While there has been no official declaration of how interpolation qualifiers will make their way into wgsl, [this](https://github.com/gpuweb/gpuweb/issues/802) issue gave some good options, and I went with the one (the second) that seemed better to me. Easy enough to change down the line.
While I was able to test most of these, the spirv frontend was having issues that were unrelated to my changes and so I couldn't test it.
=> Interpolation support for wgsl, glsl, glsl-new, spirv (front and back), and glsl-out

src/front/wgsl.rs
Adds support for composite constant expressions to the wgsl frontend, as well as fixes a bug with broken array template endings.
=> [wgsl] Support for composite constant expressions.

src/back/glsl.rs
This PR reduces the calls to `clone` in half and replaces it with a `Cow`, the use of `beef` here could probably speed up things and save some bytes.
It also handles `MemberOrigin` in structs so that `BuiltIn` works and detects empty names (`""`) as invalid idents
=> glsl-out: Less allocations, handle struct member origin and correctly handle empty names

.github/workflows/pipeline.yml
Use 1.41.0 and nightly
Big surprise: nightly seems to run a bit faster :D
=> Make CI test on multiple rust versions

src/back/glsl.rs
Fixes `UnaryOp::Not` generating the wrong op (`~` instead of `!`) on booleans and correctly handles storage images
=> glsl-out: fixes

src/front/glsl_new/lex.rs, src/front/glsl_new/mod.rs, src/front/glsl_new/parser.rs, src/front/glsl_new/types.rs
Basically takes moves type handling out of `parser.rs` and `lex.rs` into `types.rs` in order to reduce their complexity
=> [glsl-new] Refactor type handling

src/arena.rs, src/back/glsl.rs, src/back/mod.rs, src/back/msl.rs, src/front/glsl/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/mod.rs, src/proc/typifier.rs
`TypeInner` generally can have heap allocation. Cloning it is not something that I expect we need, ever. It's stored in an arena, and it can always be referenced from it.
Previously, we derived `Clone` with a comment saying this is only meant to be used for error reporting. However, the genie gets out of the box, and it's tempting to use this clone universally once it's available.
So this PR puts the genie back into the box! In particular, it makes the `Error` of the backends to return references to types, and it makes both GLSL and MSL backends to share the same `MaybeOwned` type.
=> Make TypeInner to be non-clonable

examples/convert.rs, src/back/glsl.rs, src/back/msl.rs, src/back/spv/writer.rs, src/front/glsl/mod.rs, src/front/glsl_new/parser.rs, src/front/spv/error.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, tests/convert.rs
This is a draft design for inclusion of **Execution Modes** (Options of shader stages. See [1]) into Naga's IR. This is necessary to support all basic fragment and compute shaders.
Unresolved:
Some fields do not have to be specified in frontend languages like GLSL while always being defined in SPIR-V, like ```coordinate_origin```. This could lead to a situation where on a testing path GLSL -> Naga -> GLSL we would emit functionally the same code but with additional declarations not explicitly written in the original.
The question is whether to pollute the code with additional Options just for the testing or expect tests to be written with always explicitly declared defaults. The latter might break with expansion of the ```ShaderStage``` enum.
The enum currently has only SPIR-V 1.0 and It …
=> Implement Execution Modes

src/front/glsl_new/ast.rs, src/front/glsl_new/lex.rs, src/front/glsl_new/parser.rs
Handle "true" and "false" constants.
Refactor logical expression rules in parser to use `ExpressionRule`.
Still need to change remaining expressions to `ExpressionRule`.
=> [glsl-new] Add bool consts, update logical exprs

src/back/spv/instructions.rs, src/back/spv/mod.rs, src/back/spv/writer.rs
The [writer.rs](https://github.com/gfx-rs/naga/blob/master/src/back/spv/writer.rs#L255) in the spirv back-end was becoming a little bit too cluttered with instructions, especially after I wanted to add even more of them.  So I decided to move them to their own module. This is done for maintainability, as the instructions module will reach a point where it will always be correct (as the spirv spec doesn't really change).
After this, the spirv back-end will be ready for its growth towards compiling more complex shaders (boids).
=> [Spirv-out] Move instructions to own module

test-data/simple/simple.expected.ron, test-data/simple/simple.vert, test-data/simple/simple.wgsl
Temporary add explicit return to Rosetta test, until we handle this in intermediary step between front and back-end.
=> [rosetta] Add explicit return

src/back/glsl.rs, src/back/msl.rs, src/back/spv/instructions.rs, src/front/glsl/mod.rs, src/front/glsl_new/parser.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, test-data/simple/simple.expected.ron
It appears that the access flags are not really a part of the image type in SPIR-V. The `ReadOnly` and `WriteOnly` flags are only for the "Kernel" shader model, which we don't use.
Therefore, it's totally controlled by the decorations `NonReadable` and `NonWritable`, which are put on the global variables. Therefore, it makes sense to have the `storage_access` on the global vars instead of the image types, and now it can apply to buffers as well!
Unresolved: perhaps, the flags should be a part of the `StorageClass::Uniform` variant? I'm hesitating because SPIR-V confusingly considers storage buffers and images in this class. Also, it has an extension for the `StorageBuffer` class, which confuses me even more...
=> Move storage class from image type into the global declaration

Cargo.toml, examples/convert.rs, src/back/msl.rs, src/front/mod.rs, src/front/spv/error.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/spv/rosetta.rs, tests/convert.rs
Fixes #100 for good, as a follow-up to #101 
In SPIR-V all load/stores/access chains have to go through pointers.
I don't think it makes sense for the IR - it only clutters it, and doesn't allow us to do more than we can, already.
All the backends have an easier time working with load/stores/accesses directly into expressions and variables.
=> [spirv-in] make pointers totally transparent

src/front/glsl/parser.rs
Added newlines to `parser.rs` in order to avoid `unused_braces` issue.
Maybe not the prettiest, but pomelo needs those braces - and guess clippy can't really understand why :D
=> [glsl-in] Fix unused braces in parser.rs

examples/convert.rs, src/back/glsl.rs, src/back/msl.rs, src/back/spv/writer.rs, src/front/glsl/ast.rs, src/front/glsl/mod.rs, src/front/glsl/parser.rs, src/front/glsl/parser_tests.rs, src/front/glsl/variables.rs, src/front/mod.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/interface.rs, test-data/boids.param.ron, test-data/boids.wgsl, test-data/function.wgsl, test-data/quad.wgsl, test-data/simple/simple.expected.ron, test-data/simple/simple.wgsl, tests/convert.rs
Another innocent change that turned out to be rather big. I actually was just trying to update WGSL, and the changes started being contagious...
On the IR side, this changes entry points to:
- be a map, so no collisions by construction
- store the function directly instead of a handle, so that nothing can call this function
It also renames the "set" to "group" in the decorations.
And it updates WGSL attribute syntax to the one that just got accepted.
=> Refactor entry point IR

src/back/spv/instructions.rs
This PR combines all spec requirement verify unit tests for the spv back-end into one unit test. Reason for this is because it cluttered the test log with all the separate unit tests, and it can be compiled down to one unit test just fine.
=> [spv-out] Combined all instruction spec tests to one test

src/back/glsl.rs, src/back/msl.rs, src/back/spv/writer.rs, src/front/glsl/parser.rs, src/front/wgsl/conv.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/interface.rs, test-data/boids.wgsl, test-data/simple/module.ron
This is another bag of good stuff.
- IR: remove `Statement::Empty` variant
- "glsl-out": fix `As` expression
- "msl-out": refactor call syntax, implement all the expressions and statements (yay!)
- "spv-out": block writing refactor and support for `Statement::Block`
- "wgsl-in": introduce the convert module
Most importantly, the `boids` shader is now successfully converted through `WGSL -> IR -> GLSL` and validated on that end (with `glslangValidator`) 🎉
=> Complete MSL, refactor WGSL, and remove Statement::Empty

src/front/glsl/lex_tests.rs, src/front/glsl/parser_tests.rs
- remove simple lex test as was covered by others
- combine related tests to single function
- remove redundant prefix in test names
=> [glsl-in] consolidate tests

src/front/glsl/ast.rs, src/front/glsl/parser.rs, src/front/glsl/variables.rs
Partly handles issue in  #210
Example shader:
```glsl
#version 450
layout(set = 0, binding = 0) uniform Matrices {
mat4 modelViewProjection;
};
layout(location = 0) in vec2 position;
void main() {
gl_Position = modelViewProjection * vec4(position, 0.0, 1.0);
}
```
=> [glsl-in] Support anonymous global uniforms

README.md
There's no legend explaining what symbols mean for supported end-points, but it seems to be following the same format at wgpu. This PR copies wgpu's legend.
=> Add legend for supported end-points

src/front/glsl/parser.rs, src/front/glsl/variables.rs
=> [glsl-in] Implement swizzle for r-values

src/back/spv/writer.rs
The variable [`function_id`](https://github.com/gfx-rs/naga/blob/master/src/back/spv/writer.rs#L341) in `write_entry_point` was using a wrong id. Namely, the `write_function` method returned the block id instead of the function id. spirv-val tool told me it failed due to the entrypoint having a wrong id. 
At the same time, the `lookup_function` probably stopped working as block ids were inserted, instead of function ids.
This was introduced during the entry point refactor, due to the fact that it used to override variables, see [commit](https://github.com/gfx-rs/naga/commit/2ebaadaf0ca62e558ac027606f6f18c807308ee7#diff-4516391251ac170e6db90c0fa6f07022L1074).
=> [spv-out] Fix write_function returning block id

src/front/glsl/lex.rs, src/front/glsl/parser_tests.rs
Handle spacing between `#` and directive.
Also require directive to be first token on a line, to be recognized.
Examples:
```glsl
...
void main() {} #version 450 // now invalid
```
This is in preparation for supporting other pre-processor directives
=> [glsl-in] Handle spacing for preproces directives

src/back/spv/instructions.rs, src/back/spv/writer.rs
Add support for scalar conversions via `Expression::As`.
Following conversions are implemented:
- `OpConvertFToU` (float to unsigned int)
- `OpConvertFToS` (float to signed int)
- `OpConvertSToF` (signed int to float)
- `OpConvertUToF` (unsigned int to float)
Tested with the following WGSL:
```
[[stage(fragment)]]
var uint_1: u32 = u32(1.0);
var int_1: i32 = i32(1.0);
var float_1: f32 = f32(1);
var temp_uint_2: u32 = u32(1);
var float_2: f32 = f32(temp_uint_2);
return;
}
```
I've commented out two particular cases where double casting didn't result in a double `Expression::As` expression, so I had to use an temp variable to hold the first conversion in, see #222.
=> [spv-out] Add scalar conversion support

src/back/spv/writer.rs
Add check if name for global variables is set. When the debug flag is set for spv-out, `OpName` would be added for the global variable. It can happen, for instance when having a uniform variable, that the name is not set. 
As the code always called `unwrap` when the debug flag was enabled, the code crashed.
This bug was found in issue: #210.
=> [spv-out] Add check for global variables if name is set

src/proc/typifier.rs
I talked about with kvark about this in the matrix room, we didn't reach any conclusion but i think it's supposed to be supported, here are some links
- https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpAccessChain
- https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#CompositeType
=> Added support for matrix access on the typifier

src/front/glsl/lex.rs, src/front/glsl/lex_tests.rs, src/front/glsl/parser.rs, src/front/glsl/parser_tests.rs
This gives `consume_token`access to lexer state. This simplifies the code a bit, and is also in preparation for dealing with lexer states for e.g. pre-processor.
=> [glsl-in] make consume_token a lexer method

src/back/spv/instructions.rs, src/back/spv/writer.rs
Add support for the long-awaited multiply instructions:
- OpIMul
- OpFMul
- OpVectorTimesScalar
- OpVectorTimesMatrix
- OpMatrixTimesVector
- OpMatrixTimesScalar
- OpMatrixTimesMatrix
Tested with the following WGSL:
```
[[stage(fragment)]]
var int_1: i32 = 1;
var int_2: i32 = int_1 * int_1;
var float_1: f32 = 1.0;
var float_2: f32 = float_1 * float_1;
var vec_1: vec2<f32> = vec2<f32>(1.0, 1.0);
var vec_2: vec2<f32> = vec_1 * float_1;
var mat_1: mat2x2<f32> = mat2x2<f32>(1.0, 1.0);
var vec_3: vec2<f32> = vec_2 * mat_1;
var vec_4: vec2<f32> = mat_1 * vec_3;
var mat_2: mat2x2<f32> = mat_1 * float_2;
var mat_3: mat2x2<f32> = mat_2 * mat_2;
return;
}
```
=> [spv-out] Add multiply instructions

src/back/spv/writer.rs, src/front/spv/error.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/typifier.rs
- Disable match_like_matches_macro for now
Still need to deal with `panic`s found in:
- [/src/back/spv/writer.rs](../tree/master/src/back/spv/writer.rs#L1035)
- [/src/front/spv/mod.rs](../tree/master/src/front/spv/mod.rs#L1480)
- [/src/front/wgsl/mod.rs](../tree/master/src/front/wgsl/mod.rs#L1790)
- numerous
=> [clippy] Fix clippy issues after upgrading to 1.47

examples/convert.rs, src/front/glsl/error.rs, src/front/glsl/lex.rs, src/front/glsl/mod.rs, src/front/glsl/preprocess.rs, src/front/glsl/preprocess_tests.rs, tests/convert.rs, tests/rosetta.rs
Supported:
- `#define KEY VALUE`
- `#undef`
- `#ifdef`
- `#ifndef`
- `#else`
- `#endif`
Not supported (yet):
- `#define MACRO(x, y, z)`
- `#if` (need to handle const expressions)
- `#include`
Pre-configured defines can now also be passed in to the `parse_str` function as `Vec<String, String>` (key, value).
The preprocessor works on a line by line basis, and should be easy to apply to other front-ends if needed.
As the implementation is currently of reasonable size (<150 lines), this has not (yet) been feature gated.
=> [glsl-in] Add initial pre-processor

Cargo.toml
Apparently `#[error(transparent)]` wasn't supported prior to this
=> Bump thiserror to 1.0.21

src/back/glsl.rs, src/front/glsl/parser.rs, src/front/spv/mod.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/typifier.rs
Aligns our IR to WGSL according to https://github.com/gpuweb/gpuweb/pull/914
TL;DR: right shifts are always arithmetic for signed integer and logical for unsigned.
Fixes one of the points in https://github.com/gfx-rs/naga/issues/243
=> Simplify bitshift IR

src/back/glsl.rs, src/back/msl.rs, src/back/spv/layout.rs, src/back/spv/writer.rs, src/front/glsl/parser.rs, src/front/spv/convert.rs, src/front/spv/mod.rs, src/front/wgsl/conv.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/interface.rs, src/proc/validator.rs, test-data/boids.wgsl, test-data/quad.wgsl
Mostly aligns us to https://github.com/gpuweb/gpuweb/pull/1093
I think the storage classes were one of the most confusing parts of the IR, and I've long wanted to make them understandable. I believe, they are now.
The push constant class is not really supported, but we'll need it for future expansion (outside of WebGPU).
See https://github.com/KhronosGroup/SPIRV-Reflect/pull/96 for the logic about where SPIR-V chooses which classes.
=> Clean up the storage classes

src/front/spv/flow.rs
Header blocks were incorrectly overwritten. This fix shouldn't break anything. If it does then there are deeper problems.
This PR fixes collatz.comp.
=> spv-in: fix flowgraph

src/back/msl.rs
Makes the msl out use `io::Write` instead of `fmt::Write`.
`fmt::Write` is only implemented for `String` and even the rust documentation says that
> This is similar to the standard library's io::Write trait, but it is only intended for use in libcore.
=> msl-out: Use io::Write instead of fmt::Write

src/front/glsl/ast.rs, src/front/glsl/parser.rs, src/front/glsl/parser_tests.rs, src/front/glsl/types.rs
Managed to get simple form of texturing working. Parses stuff like:
```glsl
#version 450
layout(location = 0) in vec2 v_uv;
layout(location = 0) out vec4 o_color;
layout(set = 1, binding = 1) uniform texture2D tex;
layout(set = 1, binding = 2) uniform sampler tex_sampler;
void main() {
o_color = texture(sampler2D(tex, tex_sampler), v_uv);
}
```
=> [glsl-in] Add initial texture handling

src/back/glsl.rs, src/front/glsl/ast.rs, src/front/glsl/parser.rs, src/proc/interface.rs
I did some more GLSL work. With this all the shaders from #210 gets through glsl-in -> glsl-out with what looks like a sensible result - except for a small bug in glsl-out, which I'll open another pull request for.
=> GLSL local variables, interface blocks, and XOR

src/back/spv/instructions.rs, src/back/spv/writer.rs
Handles most simple case for `ImageSample`
Sample input (glsl)
```glsl
#version 450
layout(location = 0) out vec4 o_Target;
layout(set = 1, binding = 1) uniform texture2D ColorMaterial_texture;
layout(set = 1, binding = 2) uniform sampler ColorMaterial_texture_sampler;
void main() {
o_Target = texture(
sampler2D(ColorMaterial_texture, ColorMaterial_texture_sampler),
vec2(0));
return;
}
```
results in:
```spirv
; SPIR-V
; Version: 1.0
; Generator: Khronos; 0
; Bound: 25
; Schema: 0
OpCapability ImageMSArray
OpCapability Shader
OpCapability Kernel
%1 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %main "main" %o_Target %ColorMaterial_texture %ColorMaterial_texture_sampler
OpExecutionMode %main OriginUpperLeft
OpSource GLSL 450
OpName %o_Target …
```
=> [spv-out] Handle ImageSample

src/back/spv/instructions.rs, src/back/spv/writer.rs
Add support for `Expression::Access` and `Expression::AccessIndex`.
`Expression::Access`:
- ~~Matrix~~ - Will be done at a later moment.
- ~~Array~~ - Will be done at a later moment.
`Expression::AccessIndex`:
- ~~Matrix~~ - Will be done at a later moment.
- ~~Array~~ - Will be done at a later moment.
```
type Data = struct{
[[offset(0)]] e: f32;
};
[[group(0), binding(0)]] var<uniform> u_data: Data;
var a: vec2<f32> = vec2<f32>(1.0, 1.0);
var b: f32 = a[0];
var c: f32 = a.x;
#var d: f32 = u_data.k;
return;
}
```
=> [spv-out] Add access and access index support

src/back/msl.rs, src/proc/mod.rs, src/proc/namer.rs, src/proc/typifier.rs
Fixes #264
The idea is having a global registry of names, to avoid collisions. We fill it up as a separate step before writing down `Module` contents, so that during writing we only need to look up those names in a created map.
=> Naming processor, used for [msl]

src/back/glsl.rs, src/back/msl.rs, src/front/spv/mod.rs, src/lib.rs, src/proc/interface.rs, src/proc/typifier.rs
I figured this to be require to support `OpSelect` from SPIR-V, which is used in WebGPU samples.
An alternative would involve splitting the expressions into statements, blocks, and merging with `OpPhi` - the whole eternal pain :)
=> [ir] select expression

src/back/spv/writer.rs
When the following WGSL input was used:
```
var vector: vec2<f32> = vec2<f32>(1.0, 1.0);
return;
}
```
You would get a validation error when validating the SPIR-V output. The reason was because there would be a duplicate `OpTypeFloat` is because the vector implicitly uses OpTypeFloat here.
If you would first explicity add a float variable, it would work:
```
var float: f32 = 1.0;
var vector: vec2<f32> = vec2<f32>(1.0, 1.0);
return;
}
```
The reason this works is as there is an explicit `f32` declaration and that is getting parsed correctly.
This is due to how LookupTypes work and I am not entirely sure how it is caused, but it something has to do that the implicit `f32` don't have a handle and aren't recognized …
=> [spv-out] Fix duplicate scalar OpType

src/back/spv/instructions.rs, src/back/spv/writer.rs
- Add and implement i_sub and f_sub.
- Reduce DRY code from binary instructions.
- Move out binary operator logic out of `crate::BinaryOperator::Multiply` match to easily implement other binary instructions.
There is however an edge case, and I am not sure yet how we want to solve this. Both instructions are also compatible with vectors, but as the SPIR-V spec says: "The types of Operand 1 and Operand 2 both must be the same as Result Type.".
What this means, and I have checked this in the [shader playground](http://shader-playground.timjones.io/ce2a44d27e0012a232a04aa94fdda636), is that a float vector can be subtracted by an integer. This contradicts the SPIR-V spec, but it does work in the playground as follows:
1)  Convert integer to float
2) Create an CompositeConstruct (a vector) …
=> [spv-out] Add and implement i_sub and f_sub

src/back/spv/instructions.rs, src/back/spv/writer.rs
Support the following cases:
GLSL
```glsl
#version 450
void main() {
ivec2 test_1 = ivec2(1, 1) & ivec2(1, 1);    
int test_2 = 1 & 1;
}
```
=> [spv-out] Add and implement bitwise_and

src/back/spv/writer.rs
Moved the annotation loop to the bottom of the `write_logical_layout()`. Apparently it could happen that bindings of global variables for instance weren't getting added to the SPIR-V output as the loop over the annotation collection happened before even a binding was added as decorate to the annotations, resulting in no annotations being added.
=> [spv-out] Fix annotations not getting added to output

src/back/spv/writer.rs
I went through the Bevy shader thread (#210) and a requirement for a shader to work was vector with vector multiplication. I have used the same strategy as we came up with the normal multiplication: if it is not a float vector times float vector, we will default to an `ivec`/`uvec multiplication.
There are however two other vector types in GLSL at least: `bvec` and `dvec`, but I don't think they are that commonly used, but that is just an assumption?
=> [spv-out] Add support for vector with vector multiplication

src/back/spv/instructions.rs, src/back/spv/writer.rs
Helps with https://github.com/gfx-rs/wgpu-rs/issues/620 , but doesn't fully address the `hello-triangle` issue. Another follow-up is needed.
The core functional change here is that we pass-through the `As` operator argument in case of int-uint and x-x conversions.
=> [spv-out] always return expression type

examples/convert.rs, src/back/msl/mod.rs, src/back/msl/writer.rs, src/back/spv/mod.rs, src/back/spv/writer.rs, tests/convert.rs, tests/rosetta.rs
~~All my prior resistance to making it cloneable was futile. Yes, we get away from clone internally. But this is IR, it's a part of API, and for the users it's just convenient to be able to clone it. For example, `gfx` would need a copy for its purposes, and `wgpu` needs a copy for validation.~~
=> Add spv::write_vec helper

src/back/glsl/mod.rs, src/back/msl/writer.rs, src/front/glsl/parser.rs, src/front/spv/flow.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/interface.rs, src/proc/terminator.rs
Previous IR was unusable because the hashmap has no order, so "fallthrough" semantics was broken.
Now with an array it's usable, but we need to validate the array properly to not contain intersections.
=> Refactor Switch statement, implement on WGSL

src/front/wgsl/conv.rs, src/front/wgsl/mod.rs, src/front/wgsl/tests.rs
This allows writing things like `f32(i32(x) + 1)`, and also add more stdlib functions easily.
=> [msl] refactor function call parsing

src/front/glsl/parser.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, test-data/boids.wgsl, test-data/function.wgsl, test-data/simple/module.ron, tests/snapshots.rs
This PR brings a bag of improvements to WGSL frontend:
- `const` inside functions
- avoid generating meaningless/empty statements
- more neat DRY
- less backups of the lexer
=> WGSL const and function call refactor

test-data/simple.param.ron, test-data/simple.wgsl
Example works again, as it still used somewhat outdated WGSL syntax.
=> Update simple.wgsl to latest syntax

src/back/spv/instructions.rs, src/back/spv/writer.rs
This PR brings a number of fixes and improvements to the SPIR-V backend.
The goal was to get both the `cube` and `skybox` wgpu-rs examples converted to WGSL with validated SPIR-V output.
The main improvement here is the consistent logic of inserting the Load/Store instructions. There is no code duplication any 
more, and all the meat is in one place (`write_expression_raw`).
Based on #328 . Please review stuff starting with "[spv]".
=> [spv-out] Refactor the load/store logic

.gitignore, examples/convert.rs, src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/msl/writer.rs, tests/snapshots.rs, tests/snapshots/in/skybox.param.ron, tests/snapshots/in/skybox.wgsl, tests/snapshots/snapshots__boids.msl.snap, tests/snapshots/snapshots__quad.msl.snap, tests/snapshots/snapshots__simple.msl.snap, tests/snapshots/snapshots__skybox-Fragment.glsl.snap, tests/snapshots/snapshots__skybox-Vertex.glsl.snap, tests/snapshots/snapshots__skybox.msl.snap, tests/snapshots/snapshots__skybox.spvasm.snap
Based on #329, this PR gets us to a point where we can generate the MSL shader for the `skybox` example directly from IR 🎉 
(there is only one new commit here)
The things missing were:
- inserting the namespace qualifier `metal::` before the types (we can discuss this on Matrix if there are concerns)
- fixing matrix composition and indexing
Update: also got GLSL output working for this! And added it to the snapshot tests.
=> [msl] namespace and matrix fixes to get Skybox running

src/front/glsl/variables.rs
Adds a cast to SInt (`Expression::As`), when `gl_VertexIndex` is used.
Now getting this kind of output:
```
...
%14 = OpLoad %uint %gl_VertexIndex
%10 = OpISub %int %14 %int_1
%17 = OpConvertSToF %float %10            
OpStore %2 %17 
%21 = OpLoad %uint %gl_VertexIndex
%20 = OpBitwiseAnd %int %21 %int_1
%19 = OpIMul %int %20 %int_2                                                                             
%18 = OpISub %int %19 %int_1
%23 = OpConvertSToF %float %18                                                                           
OpStore %5 %23
%27 = OpLoad %float %2                                                                                   
%28 = OpLoad %float %5
%31 = OpCompositeConstruct %v4float %27 %28 %float_0 %float_1
OpStore %gl_Position %31
OpReturn
OpFunctionEnd …
```
=> [glsl-in] Cast gl_VertexIndex to SInt

src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/spv/writer.rs
For SPIR-V - the global variable can be in `Private` storage class, for which there isn't necessarily a binding.
For GLSL - the ES 320 target exists, although we may need to re-think the target version checks in the future anyway.
=> Fix SPIR-V global binding check, add GLES 320 support

src/back/glsl/mod.rs, src/back/msl/writer.rs, src/back/spv/layout.rs, src/back/spv/writer.rs, src/front/glsl/parser.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/mod.rs, src/proc/sizer.rs, src/proc/typifier.rs, src/proc/validator.rs, test-data/simple/module.ron, tests/snapshots/snapshots__boids.msl.snap, tests/snapshots/snapshots__simple.msl.snap, tests/snapshots/snapshots__skybox.msl.snap
Another chapter in the series of IR refinements. Previously, we carried a type handle in every constant.
However, this is redundant for the scalar constants mostly. New API is more dense, more correct by constructions. It allows a clear 1:1 between `ScalarValue` and `ScalarKind`.
Note: in some cases it seems that moving the `Bool` variant out of `ScalarValue` into `ConstantInner` would be more convenient, but we'd lose this 1:1 relationship, so I didn't do it.
=> Tidy up constants IR

src/front/glsl/ast.rs, src/front/glsl/error.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs, src/front/glsl/variables.rs
I was messing around with migrating my build scripts for https://github.com/sotrh/learn-wgpu to use `naga` instead of `shaderc`, and I ran into issues with errors not having enough information. While this PR doesn't fix that issue entirely, it makes `SemanticError`s more flexible as they can now still borrow static strings, and they can be formatted to include additional details such as line numbers and names of variables.
=> Change ErrorKind::SemanticError to use Cow<'static, str> instead of &'static str

src/back/spv/writer.rs
First PR of the series of PRs to implement flow control. This PR will add comparison operators to enable `==`, `!=`, `<`, `<=`, `>`, `>=` in the near future.
As far as I know, Sint, Uint, and bool are the only comparison operators.
There is maybe only one concern: Floats have two variants for all comparison operators. An ordered and unordered ones. I don't know what is the difference, but I implemented the ordered ones for now. Do we also want to implement the unordered ones?
=> [spv-out] Add comparison operators

src/front/wgsl/mod.rs
Fixes an assertion in the Typifier that happened on access to another function by handle.
=> [wgsl] resolve types across functions

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs
The old implementation was the *opposite* of what we need: it only read the index for storages, and expected an identifier.
=> [wgsl] fix and update storage load

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, tests/snapshots/snapshots__skybox.msl.snap
Enables type casts like `vec2<i32>(other_vec)` in WGSL
=> [wgsl] support vector type casts

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs
The code is mostly a copy-paste from `parse_block`, but sharing it would be more trouble than it's worth.
=> [wgsl] support simple block statements

Cargo.toml, examples/convert.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs
Here is how it looks with the PR:
```
[2021-01-27T15:57:52Z ERROR naga::front::wgsl] |	fn vs_bake() {
[2021-01-27T15:57:52Z ERROR naga::front::wgsl] >	    out_position = u_globals.view_proj 1* u_entity.world * vec4<f32>(in_position);
[2021-01-27T15:57:52Z ERROR naga::front::wgsl] |	                                        ^
thread 'main' panicked at 'error while parsing WGSL in scopes [FunctionDecl, Block, Statement] at line 26 pos 40: unexpected token Number { value: "1", ty: 'i', width: "" }, expected separator', examples/convert.rs:54:31
```
Here is how it looks on master right now:
```
[2021-01-27T15:57:34Z ERROR naga::front::wgsl] Unmet expectation for Separator(';')
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { error: Unexpected(Number { value: …
```
=> Improve WGSL error reporting

src/back/spv/instructions.rs, src/back/spv/writer.rs, tests/snapshots.rs, tests/snapshots/in/boids.wgsl, tests/snapshots/in/collatz.wgsl, tests/snapshots/snapshots__boids.msl.snap, tests/snapshots/snapshots__boids.spvasm.snap, tests/snapshots/snapshots__collatz.msl.snap, tests/snapshots/snapshots__collatz.spvasm.snap
Introducing conditional flow control for spv-out, also known as if/else statements. Some notable changes:
- Refactored binary operator parsing, as it always used the result type of either the left or right sided type. However for the comparison operators, this is not true. It always has to return `bool` as result type.
- Statements of the dominator block are getting split when it encounters a branching and resumes its statements after the branching is merged back to the merge block.
- Some optimizations done for the conditional branching. This is probably not something for the back-end and if we follow compiler architecture it should be in the optimizer layer. Optimizations done: When both accept and reject block are empty, ignore the whole conditional branching, when the accept block is …
=> [spv-out] Conditional flow control

src/back/spv/writer.rs
I consulted the specs of the extended instruction set https://www.khronos.org/registry/spir-v/specs/1.0/GLSL.std.450.html
and WGSL https://gpuweb.github.io/gpuweb/wgsl.html#float-builtin-functions
I didn't find any unit test around math function.
I tested with this WGSL shader:
```
var x: f32 = pow(1.0, 0.5);  // 1
var y: f32 = pow(2.0, 2.0) / 8.0; // 0.5
out_target = vec4<f32>(x, y, 0.0, 1.0);
```
=> Added function pow for the spirv backend

src/back/glsl/mod.rs, src/back/msl/writer.rs, src/proc/namer.rs, tests/snapshots.rs, tests/snapshots/in/boids.wgsl, tests/snapshots/in/shadow.param.ron, tests/snapshots/in/shadow.wgsl, tests/snapshots/snapshots__boids.msl.snap, tests/snapshots/snapshots__boids.spvasm.snap, tests/snapshots/snapshots__collatz.msl.snap, tests/snapshots/snapshots__empty.msl.snap, tests/snapshots/snapshots__quad.msl.snap, tests/snapshots/snapshots__shadow.msl.snap, tests/snapshots/snapshots__shadow.spvasm.snap, tests/snapshots/snapshots__skybox.msl.snap
MSL:
- actually implements `continuing` loop statement. Refactors the Namer API to aid that, and reuses the allocation within the writer.
- fixes scoping of binary expressions
- fixes unsigned constants
- fixes ">" operation
- fixes `sample_compare` calls to avoid `level(0)` option
- fixes `return` without a value in the middle of functions
In the end, it allows wgpu-rs to run the `boids` example with pure Naga translation, not involving SPIR-V on Metal 🎉 
Unfortunately, the `shadow` example got blocked on #390. It seems good otherwise.
For testing, the `boids.wgsl` is updated, now only contains the compute part. The `shadow.wgsl` is added, it demonstrates quite a few difficulties:
- depth sampling
- using a resource only within a helper function (not supported by our `Interface` …
=> Assorted MSL fixes

README.md
The checkmarks used were a bit confusing. This improves the visual prominence between primary and secondary support (IMHO)
=> Update emoji in README

src/front/glsl/lex.rs, src/front/glsl/lex_tests.rs, src/front/glsl/parser.rs
Fixes double constants (ending with "lf") being treated as floats and added support for uint constants (ending with "u")
=> [glsl-in] Fix double constant lexing and lex uint constants

src/front/glsl/ast.rs, src/front/glsl/functions.rs
Populates the `ResolveContext` with the module functions, otherwise the `Typifier` would panic.
Adds support for `sin`, `abs` and `mix`
=> [glsl-in] Populate ResolveContext with functions and add more math functions

src/back/spv/writer.rs
Implementation of `sinh`, `cosh`, `tanh`, `mod`, `frexp`, `ldexp`, `faceForward`, `exp`, `exp2`, `log`, `log2`, `sign`, `fma`, `mix`, `step`, `smoothstep`, `sqrt`, `determintant`, `reflect`.
At least `mod`, `frexp`, `ldexp`, `determintant` require some checking.
Perhaps the [specification](https://gpuweb.github.io/gpuweb/wgsl.html) missed the `refract` function.
=> [spv-out] Add missing math functions

src/back/spv/writer.rs, tests/snapshots/snapshots__boids.spvasm.snap, tests/snapshots/snapshots__shadow.spvasm.snap
This reduces our headache for re-using the same structure types between read-write and read-only storage buffers.
See also - https://github.com/KhronosGroup/glslang/issues/1317#issuecomment-771226026
=> [spv] put NonWritable on buffer variable itself

src/proc/validator.rs
FragDepth is written to in a fragment shader, not read.
=> FragDepth is a Write Property

Makefile, README.md, src/back/glsl/mod.rs, tests/snapshots/snapshots__quad-Fragment.glsl.snap, tests/snapshots/snapshots__skybox-Fragment.glsl.snap
This is something I wanted to do for a long time, and I think snapshots make it fairly easy to roll in.
The problem we had is that we generate the snapshot shaders, but it's tedious to double-check with the actual native SDK if those updated snapshots are valid at all. I.e. we could have a snapshot in-tree that is simply invalid, which compromises the whole idea of keeping it around. In fact, that's the case today for a few shaders.
So technically we have the native shaders produced, and we have the tools, but remembering all the tool syntax and editing the snapshot shaders to strip the header, makes it very hard to force this into a habit. Just takes too much effort!
Lo and behold - the automation:
```bash
make validate-spv # for Vulkan shaders, requires SPIRV-Tools installed
make …
```
=> Makefile commands for native shader validation

src/back/glsl/mod.rs, src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs
Vector equality in glsl is now handled as `all(equal(vec1, vec2))` and inequality as `any(notEqual(vec1, vec2))`
=> [glsl-in] Fix the way equality is handled

src/front/glsl/ast.rs, src/front/glsl/parser.rs
- `Plus` is a noop
- `Bang` and `Tilde` require some extra validation to ensure they don't parse invalid glsl
=> [glsl-in] Add support for unary ops

src/back/spv/writer.rs, tests/out/boids.spvasm.snap, tests/out/collatz.spvasm.snap, tests/out/empty.spvasm.snap, tests/out/quad.spvasm.snap, tests/out/shadow.spvasm.snap, tests/out/skybox.spvasm.snap, tests/out/texture-array.spvasm.snap
Apparently ID 0 can't be used freely, but spirv-val only complains in a specific phase of the moon.
=> [spv-out] fix initial ID 0 and 1 assignments

src/back/spv/instructions.rs, src/back/spv/writer.rs
Tested locally on the following example:
```rust
fn main() {
var x: i32 = 4;
const y: f32 = 6.0;
var z: f32;
switch(x) {
case 4: { z = 4.0; fallthrough;}
case 5: { z = 5.0; }
default: { z = 1.0; }
}
}
```
Worked at first try!
=> [spv-out] support Switch statements

src/front/wgsl/mod.rs
naga does not require offset decorations on struct fields in WGSL
source, and automatically adds them to spv output. The `tint` compiler
does not automatically add them, and requires that they be present in
the WGSL source.
A potential confusion is that an spv binary missing required
`OpMemberDecorate` instructions that set the field's offset will fail
validation when run through `spirv-val`. But since naga automatically
produces these offsets, the same spv binary passed through naga will
be successfully validated.
This change is to ignore these decorations in naga's WGSL front end so
that the same WGSL source can be used with naga and tint to produce
valid spv.
Fixes #455
=> [wgsl] ignore offset decorations on struct fields

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs
This isn't a very useful change on its own, but we need to track the number of bytes consumed per token in order to support #380 or other later contextual errors that need to know the byte span of relevant tokens.
Alternatively we could derive it by measuring the change in `self.input.len()` whenever `self.input` is changed, but counting the bytes directly as they're consumed felt like the most straightforward path.
If these changes seem useful, I was thinking we could land this PR on its own to avoid diverging too much from `master` in my branch.
=> [wgsl] track number of bytes consumed per token

src/front/spv/function.rs, src/front/spv/mod.rs
We had a bug in there, since global use resolution needs proper function indices, and ours were unpatched.
=> [spv-in] patch function calls before deriving the global use

examples/convert.rs, src/back/glsl/mod.rs, src/back/msl/mod.rs, src/back/msl/writer.rs, src/front/global_usage.rs, src/lib.rs, src/proc/analyzer.rs, src/proc/interface.rs, src/proc/mod.rs, src/proc/validator.rs, tests/out/shadow.msl.snap, tests/out/skybox.msl.snap, tests/parse.rs, tests/snapshots.rs
Figures out the following properties:
- control flow uniformity. This is only needed for validation.
- texture/sampler pairs. This is needed for `wgpu` level validation.
- expression reference counts. This is needed for the backends to figure out when to re-use the expressions.
Roughly, the idea is that validation will produce this analysis as an artifact, and the backends will accept it.
=> Analyzer processor

tests/snapshots.rs
On Windows, `ron::ser::PrettyConfig::default()` defaults to `\r\n` line endings, which caused the snapshot tests to fail (and print the whole file in the error log) because the existing snapshot is saved with `\n` line endings.
Explicitly specify `\n` to be the line endings to fix this.
=> Specify line endings in ron snapshot tests

src/front/wgsl/mod.rs, tests/out/shadow.msl.snap, tests/out/skybox.msl.snap
Restricts type casts to types of the same container.
resolves #454
=> [wgsl] restrict type casts to matching container types

src/front/spv/mod.rs
Add support for the `OpString` instruction.
`shaderc` adds a `OpString` instruction with the source filename to generated SPIR-V, which causes otherwise well-validating shaders to not parse. (Ref. #265) 
This is a dummy implementation that basically ignores the result of the instruction. This is valid here, because [the spec](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpString) explicitly allows ignoring it, and other instructions where the result may be used (`OpLine` and `OpSource`) either don't parse yet (`OpLine`) or are ignored as well (`OpSource`).
=> [spv-in] support string instruction

src/back/glsl/mod.rs, src/back/msl/writer.rs, src/back/spv/writer.rs, src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/lib.rs, src/proc/mod.rs, src/proc/typifier.rs
Add support for the `inverse` GLSL function.
I also added some other math functions to the GLSL frontend that were already available but were missing from the parsing step.
Resolves #357 
~~To make the code in #357 work, I had to add support for `TypeInner::Matrix` in the `Expression::As` branch in the typifier - I'm not sure if that's correct, feedback is welcome.~~
=> [glsl-in] support inverse function

src/back/msl/writer.rs, src/proc/namer.rs, tests/out/boids.msl.snap, tests/out/collatz.msl.snap, tests/out/quad.msl.snap, tests/out/shadow.msl.snap, tests/out/skybox.msl.snap
Previously, the MSL backend was just embedding all the constants in-place, which resulted in lot of repetition whenever composite constants were involved. Now we are declaring them separately and using throughout the code.
We may consider at some point to still in-line the scalar constants in the code, but I don't think it changes the core of this PR.
=> Support constants in the naming processor

Cargo.toml, examples/convert.rs, src/back/glsl/mod.rs, tests/snapshots.rs
Based on #445 
Part of the larger move to use the intermediate processing artifacts in the backends.
=> [glsl-out] use existing Analysis instead of implementing Visitor

src/back/msl/writer.rs, src/front/global_usage.rs, src/proc/call_graph.rs, src/proc/interface.rs, src/proc/validator.rs
More steps towards #409 
The `Interface` optimization is particularly interesting. When traversing the expressions, we only want to visit each expression once, and only when looking at the block that introduces it. If we had the ownership established in the IR like #452 suggests, we'd not need to keep the bitmask here.
=> Miscellaneous fixes for parsing Dota shaders

examples/convert.rs
After #466 the convert example panicked with `target SPIRV-0.0 is not supported` in the `spv-out` path since it was set to `(0, 0)` with the default constructor.
=> Set default SPIR-V version in convert example

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs
Adds a ~~context to the lexer to keep track of the type parameter nesting level~~ `next_generic` method to the lexer that skips parsing shift operations.
This could be kept fairly simple ~~and limited to the lexer~~ because WGSL doesn't allow operations inside type parameters.
Tested on this shader sample:
```wgsl
var x: array<vec2<f32>>;
var y: array<array<vec2<f32>>>;
var a: i32 = 12 << 1;
if (a < 10 >> 3) {
a = 10;
}
var b: i32 = 10 < 12 >> 1;
```
Resolves #415
=> [wgsl] support nested type parameters

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs
The first commit allows for statement header components to be optional.
This parses now correctly:
```wgsl
for(;;) {
...
}
```
The second commit limits the allowed initializer contents to `variable_statement | assignment_statement | func_call_statement` instead of allowing any statement.
=> [wgsl] allow empty for statement headers, and other compliance additions

examples/convert.rs, src/back/glsl/mod.rs, src/back/msl/mod.rs, src/back/msl/writer.rs, src/back/spv/writer.rs, src/proc/mod.rs, src/proc/typifier.rs, src/proc/validator.rs
- don't validate in `convert` if we are only printing to console
- use `thiserror` in MSL
- have typifier report the expression handle
=> Error tweaks

examples/convert.rs, src/back/glsl/mod.rs, src/front/glsl/error.rs, src/front/spv/error.rs, src/proc/typifier.rs, src/proc/validator.rs
This is how it looks now:
```
Global variable Handle(2) 'particlesSrc' is invalid:
Storage access LOAD exceeds the allowed (empty)
```
This is how it used to look:
```
thread 'main' panicked at 'Global variable Handle(2) 'particlesSrc' is invalid: InvalidStorageAccess { allowed: (empty), seen: LOAD }', examples/convert.rs:56:31
```
=> Use source attribute of errors

src/proc/typifier.rs
Fixes #504
We got this backwards:)
Before I flush this out of my cache, the "vector * matrix" is the same thing as "transpose(matrix) * transpose(vector)".
The multiplication is done by the classy textbook rules, where the vector<N> is equivalent to matrix<1,N>.
=> Fix type resolves of matrix by vectors

src/front/spv/flow.rs
Title says it all. Now the output seems to be the same as in: https://github.com/gfx-rs/naga/issues/499.
=> spv-in: fix if condition when merge node == false node

tests/errors.rs
This starts to track parser errors for the WGSL frontend. The snapshots are inline (instead of separate files like shader snapshots) because the parser errors should generally remain small.
The benefits of error snapshots are basically the same as shader snapshots – it lets us verify that the error is returned correctly and that we avoid regressions as parts move around internally.
=> [wgsl] Add parser error snapshot

src/proc/mod.rs, src/proc/validator.rs
Instead of traversing the types from top to bottom, enforcing the `HOST_SHARED` flag as we go, we are now collecting the type capabilities bottom to top (naturally), and comparing against the needs for global variables and such.
The PR also adds extends the checked properties into `SIZED`, and has a general `DATA` bit for the non-handle types.
This helps to validate cases like https://github.com/gfx-rs/wgpu/issues/1223
=> Rewrite the type validation

src/proc/layouter.rs, src/proc/validator.rs
Until we have some amount of type inference, an integer literal used as a constant array size must have a `u` suffix. This is inconsistent with the surface syntax presented in the spec, and is a minor inconvenience.
For now, allow a signed integer array size to pass validation so that user code need not change when type inference deduces values of the correct type.
Fixes #516
=> Validate signed integer array size constants

src/front/spv/flow.rs
Fixes #520
In case false and merge node are the same in a Header block there can be 2 cases
- path along true edge ends up in the merge/false node
- path along true edge ends up somewhere else
In both cases a separate stop index needs to be used
- first case it is the false/false node
- second case it is just stop index passed on from above
=> spv-in: fix if branches in CFG

Cargo.toml, bin/convert.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/errors.rs
Fixes #380 (at least for wgsl-in)
Only `Unexpected` includes span information for now. We can expand this to include all the other variants without much trouble but we could do it in separate PRs.
`StringErrorBuffer` is currently only used in `emit_to_string`, so we could make the fields of `ParseError` public and move `StringErrorBuffer` inside the tests module if we don't want to expose `emit_to_string` outside of tests.
=> [wgsl-in] Use codespan to report errors

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/errors.rs
Add some initial descriptions for `BadInteger`, `BadFloat`, `BadScalarWidth`, and `BadAccessor`. I removed some of the fields that weren't being used in the new descriptions – we could expand these over time as we improve the descriptions/notes.
=> [wgsl-in] Add descriptions for more errors

src/back/glsl/mod.rs, tests/out/quad-Fragment.glsl.snap, tests/out/skybox-Fragment.glsl.snap
Before:
```glsl
Light_block_2 {
mat4x4 proj;
vec4 pos;
vec4 color;
} _expr29 = _group_0_binding_1.data[i];
```
After:
```glsl
Light _expr29 = _group_0_binding_1.data[i];
```
=> [glsl-out] Set precision for image type and fix structure type in statement

Cargo.toml, bin/convert.rs, src/back/glsl/mod.rs, src/back/msl/writer.rs, src/back/spv/writer.rs, src/front/glsl/parser.rs, src/front/mod.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/layouter.rs, src/proc/typifier.rs, src/proc/validator.rs, tests/out/boids.msl.snap, tests/out/boids.spvasm.snap, tests/out/collatz.spvasm.snap, tests/out/shadow.msl.snap, tests/out/shadow.spvasm.snap, tests/out/skybox.msl.snap, tests/out/skybox.spvasm.snap, tests/out/texture-array.spvasm.snap, tests/parse.rs
Fixes #542
We talked about this with @jrmuizel and decided to try out an idea (after a series of other ideas that didn't work well - https://github.com/gfx-rs/naga/issues/542#issuecomment-790674102) where the type system has *another* pointer type for implicit value types. So it can only point to scalars or vectors. It allows us to keep the typifier roughly doing the same, while getting all the benefit from the real pointer type checks. This PR implements the approach, and I think it's good to land 🚀 
TL;DR: this PR allows the type system to differentiate between pointers (which have to be used only in `Access`, `AccessIndex`, and `Load` expressions, or the `Store` statement) and values. All the non-Handle variables are pointers now, aligning with SPIR-V.
=> First-class pointer semantics

src/front/spv/convert.rs, src/front/spv/error.rs, src/front/spv/function.rs, src/front/spv/mod.rs, tests/out/shadow.ron.snap
The function call patching was wrong because it didn't work with forward declarations.
The variables as pointers thing is a required follow up to #546: the SPIR-V frontend was still considering everything to be non-pointer, unconditionally. This prevented use cases where a function argument is a pointer, and this is what `glslang` always generates (including wgpu-rs water example shaders). So this PR makes pointers really first-class in the frontend, at the cost of slightly increased complexity in the type logic.
=> [spv-in] function calls and variable types as pointers

bin/convert.rs, src/proc/analyzer.rs, tests/out/collatz.info.ron.snap, tests/out/shadow.info.ron.snap
This is a big update to #445. Error reporting was really harsh, since it wasn't telling the user what part of the code requires uniformity, and what part doesn't let it happen. This PR adds this information to the errors. It also fixes the logic somewhere, since the water example no longer triggers an uniformity error.
=> More error information for uniformity analysis

src/back/glsl/mod.rs, tests/out/shadow-Fragment.glsl.snap, tests/out/skybox-Fragment.glsl.snap, tests/out/skybox-Vertex.glsl.snap, tests/snapshots.rs
Fix #560
Also this PR fix:
1. Remove redundant struct write
2. Enable `glsl-out` test with `shadow` shader
=> [glsl-out] Properly write array type

src/back/glsl/mod.rs, src/back/msl/writer.rs, src/front/glsl/ast.rs, src/front/glsl/constants.rs, src/front/glsl/error.rs, src/front/glsl/parser.rs, src/front/spv/flow.rs, src/front/wgsl/mod.rs, src/lib.rs
This enables `clippy::pattern_type_mismatch` warning for the whole project. We've already tried to follow it, unofficially, via my annoying review pings (sorry!). Now it's a part of the workflow, checked by CI. I'm really happy that we can do this :)
See also - https://github.com/rust-lang/rust-clippy/issues/6885
=> Prevent matching on a reference once and for all

src/back/glsl/mod.rs, src/back/mod.rs, tests/out/quad-Fragment.glsl.snap, tests/out/shadow-Fragment.glsl.snap, tests/out/skybox-Fragment.glsl.snap
Fixes #565
The problem with emitting here was that it only worked on expressions that have registered types. A lot of expressions don't.
Related, this PR also includes a small change in all the frontends to force the caching of `Derivative` expression, so that it gets tied to the region and doesn't slip deeper where the control flow may be less uniform.
Finally, `cached_expressions` needed to be reset between the functions, so that we don't hit it accidentally.
=> [glsl-out] fix cached expressions

src/front/spv/flow.rs
Fixes #570
This should correctly classify blocks and edges as **Back** ones. In the correct SPIR-V there should always be exactly one back edge - the one pointing to a loop block
=> spv-in: fix classification of back edges

CHANGELOG.md, bin/convert.rs
Fixes #580
The converter changes are meant to allow dumping the IR in case of a failed analysis. This is useful to analyze why the analysis fails in the first place :)
=> Changelog for v0.4, more flexible conversion

src/back/msl/writer.rs, tests/in/skybox.wgsl, tests/out/boids.msl.snap, tests/out/collatz.msl.snap, tests/out/quad.msl.snap, tests/out/shadow.msl.snap, tests/out/skybox-Fragment.glsl.snap, tests/out/skybox.msl.snap, tests/out/skybox.spvasm.snap
Now we have a snapshot test for `in: VaryingStructure` kind of argument of an entry point. The Metal backend wasn't processing it correctly. Now it does.
=> [msl-out] fix varying input structures

src/back/msl/mod.rs, src/back/msl/writer.rs, src/proc/typifier.rs
Fixes #595.
It also changes `io::Error` into `fmt::Error`, which reduces the footprint from 45K to 40K.
Edit: also refactors typifier errors to get it down to 26K
=> Diagnostics for stack allocation in MSL

src/front/wgsl/mod.rs, src/proc/layouter.rs, src/proc/mod.rs, src/proc/validator.rs, tests/in/boids.wgsl, tests/in/texture-array.wgsl, tests/out/boids.msl.snap, tests/out/boids.spvasm.snap, tests/out/texture-array.spvasm.snap
=> Validate Compose, Unary, Binary, Select, and Relational

src/valid/function.rs, src/valid/interface.rs, src/valid/mod.rs, src/valid/type.rs
I was hoping that introducing these errors would prevent people from using unaligned types in WGSL. However, it looks like the spec is not saying anything about `f32` or `vec3<f32>` in https://gpuweb.github.io/gpuweb/wgsl.html#storage-class-constraints, or I'm just missing it.
In any way, this code can be extended when we have all the restrictions on the table.
=> Validate structure layouts

src/back/glsl/mod.rs, src/back/msl/mod.rs, src/back/msl/writer.rs, src/back/spv/writer.rs, src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/mod.rs, src/front/wgsl/mod.rs, src/proc/mod.rs, src/proc/typifier.rs, src/valid/analyzer.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/interface.rs, src/valid/mod.rs, src/valid/type.rs, tests/out/collatz.info.ron.snap, tests/out/shadow.info.ron.snap
This is a continuation of the ideas in #600. We need to merge the analysis into validation.
This PR does it for functions, and allows them to re-use the type results instead of having the backends to regenerate it.
Edit:
This is now complete (and needs another look for the added commits). I really like the scheme we ended up with here:
- the `TypeResolution` is exposed, and it's a nicer thing to work with, versus separate `get_handle`, `get`, and `try_get` methods on a `Typifier`.
- the type is now a part of `ExpressionInfo`, as opposed to be coming from a different source. Everything is in one place now.
- the typifier doesn't have this double-identity issue where it needs to both be growable (for frontends) and immutable (for backends). The validation now produces type information, and …
=> Avoid re-typification in the backends

src/back/spv/writer.rs, src/proc/layouter.rs, src/proc/mod.rs, src/valid/analyzer.rs, src/valid/mod.rs, tests/out/boids.spvasm.snap, tests/out/collatz.info.ron.snap, tests/out/collatz.spvasm.snap, tests/out/quad.spvasm.snap, tests/out/shadow.info.ron.snap, tests/out/shadow.spvasm.snap, tests/out/skybox.spvasm.snap, tests/out/texture-array.spvasm.snap
Continuation of #602 
The type layout is now a part of `ModuleInfo`.
I switched spv-out to use it instead of creating a separate layout object, and I faced a problem wrt how things are organized there. With lazy type serialization, it would take a lot of boilerplate to propagate the layouter to all the things - basically to all the `write_` methods, since most of them call `get_type_id`.
Instead, I did what I wanted to do for some time and refactored the type serialization more drastically. Now all the "handle" types are serialized at the start. There is just a trick we were missing to make it work:
- first, all the scalar constants are serialized
- then gather the types corresponding to structures
- then all the types
- then all the composite constants
I also made it so the …
=> Move Layouter into ModuleInfo

src/lib.rs, src/valid/analyzer.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/interface.rs, src/valid/mod.rs, tests/out/collatz.info.ron.snap, tests/out/shadow.info.ron.snap
Even more steps towards #59 
The only expression type left is `Math`. It's a big one, and also, interestingly, the one that motivated me to dive into the validation in the first place (more precisely, the "Frexp" operation is tricky and would benefit from type checks).
=> Validate image expressions

src/valid/interface.rs, src/valid/mod.rs, src/valid/type.rs, tests/out/collatz.info.ron.snap, tests/out/shadow.info.ron.snap
The struct size check was just plain broken, and if I fix it, we'd start failing on the boids example...
Disabling now until https://github.com/gpuweb/gpuweb/issues/1558 is cleared.
=> Make layout validation optional, disable the struct size check

src/front/spv/image.rs, src/front/spv/mod.rs, tests/out/shadow.info.ron.snap, tests/out/shadow.ron.snap
The image operands were incorrect. We are expected to read 1 mask followed by the parameters, and instead we used to read each bit separately.
=> SPIRV frontend fixes for image operands and shifts

src/valid/function.rs, tests/in/shadow.wgsl
Looks like the expression validation check was flipped, unfortunately.
This should be merged after #609, which addresses the correctness of the image array index.
=> Fix expression validation check

src/back/spv/helpers.rs, src/back/spv/instructions.rs, src/back/spv/layout.rs, src/back/spv/mod.rs, src/back/spv/writer.rs, src/front/glsl/parser.rs, src/front/spv/mod.rs, src/lib.rs, src/valid/interface.rs, src/valid/type.rs, tests/in/boids.wgsl, tests/in/shadow.wgsl, tests/out/boids.spvasm.snap, tests/out/collatz.spvasm.snap, tests/out/quad.spvasm.snap, tests/out/shadow.ron.snap, tests/out/shadow.spvasm.snap, tests/out/skybox.spvasm.snap
Closes #611
The side effect of this change is that now we require SPV-1.3 or `SPV_KHR_storage_buffer_storage_class`. Apparently, this is universally supported, and it's a good thing. You can see how the code size is reduced in the PR.
=> Align the block decoration with SPIR-V, require storage buffers

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs
Fixes #627 
Very basic, there is no dereference, etc, but enough to be able to call `frexp` and friends.
=> [wgsl-in] ability to take a pointer to something

src/back/msl/writer.rs, tests/out/quad-vert.msl.snap
Our MSL code, translated from SPIR-V, was totally wrong. It couldn't modify the private vars that were returned from the wrapped function.
With this change, the Metal backend can not only serve the https://github.com/gfx-rs/wgpu-rs/pull/763 by generating valid code, it can also do so when generating SPIR-V and then parsing it back!
=> [msl] fix mutability of function parameters

src/front/spv/mod.rs, tests/out/quad-vert.msl.snap, tests/out/shadow.info.ron.snap, tests/out/shadow.ron.snap
If we emit them on the fly, we hit a validation error, since frontends aren't expected to emit constant expressions.
=> [spv-in] pre-emit constant expressions

src/proc/typifier.rs, tests/out/collatz.info.ron.snap, tests/out/shadow.info.ron.snap
Our typification code didn't support Matrix * Matrix if they are different types. Now it does.
=> Fix matrix multiplication types

bin/convert.rs, src/back/spv/mod.rs, src/back/spv/writer.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/proc/mod.rs, tests/in/boids.param.ron, tests/in/collatz.param.ron, tests/in/empty.param.ron, tests/in/image-copy.param.ron, tests/in/quad-glsl.param.ron, tests/in/quad.param.ron, tests/in/shadow.param.ron, tests/in/skybox.param.ron, tests/in/texture-array.param.ron, tests/out/boids.spvasm.snap, tests/out/collatz.spvasm.snap, tests/out/empty.spvasm.snap, tests/out/quad-vert.msl.snap, tests/out/quad.spvasm.snap, tests/out/shadow.spvasm.snap, tests/out/skybox.spvasm.snap, tests/snapshots.rs
Fixes #651
Unblocks https://github.com/gfx-rs/gfx/issues/3707
Our IR has the coordinate system that matches everything but Vulkan. So in order to correctly translate, we need to flip the Y of vertex outputs in both SPV-in and SPV-out.
This is a draft because I'm still trying to figure out what flags are needed to be exposed to control this.
=> Flip Y axis in SPIR-V frontend and backend

src/arena.rs
It seems impossible practically, but possible intentionally.
When arena size becomes `u32::MAX+1` on append the new handle returned contains 0 in NonZeroU32 which is UB.
=> Panic to prevent arena Handle overflow

src/front/wgsl/conv.rs, src/front/wgsl/mod.rs
Renames:
Error::UnknownDecoration => Error::UnknownAttribute
TypeDecoration => TypeAttributes
Scope::Decoration => Scope::Attribute
various argument names, string literals, comments
=> [wgsl-in] Decorations are now called attributes.

src/back/msl/writer.rs, tests/out/boids.msl.snap, tests/out/collatz.msl.snap, tests/out/empty.msl.snap, tests/out/image-copy.msl.snap, tests/out/quad-vert.msl.snap, tests/out/quad.msl.snap, tests/out/shadow.msl.snap, tests/out/skybox.msl.snap
Fixes #666
For global image variables (Metal textures), the type needs to depend on the storage access. One way to get that working is to always inline the type, since this is where we know about the storage access unconditionally. I figured it's going to be a general improvement for the produced code, since previously it was annoying to look up "typeN" for anything trivial.
=> [msl] Inline some of the types

src/back/msl/writer.rs, tests/out/boids.msl.snap, tests/out/collatz.msl.snap, tests/out/image-copy.msl.snap, tests/out/quad-vert.msl.snap, tests/out/quad.msl.snap, tests/out/shadow.msl.snap, tests/out/skybox.msl.snap
Closes #656
Technically, it doesn't add refcounts. The original motivation there was we could omit constants we don't use. This PR achieves the same effect, and even better. There was also an issue about some constants depending on the other, which made the idea difficult to implement in a useful way.
=> [msl] inline some of the constants

src/front/spv/function.rs
The initial intention was to make the code a little more elegant and match on
the Vec itself instead of its length, however there's also a - probably
minuscule - performance advantage:
`Vec::remove` internally copies the removed element onto the stack. In this case
that's a `StructMember` weighting 48 bytes. The `Binding` we are actually
interested in is only 8 bytes tough.
Cloning just the `Binding` saves us from copying 40 bytes for nothing.
=> [spv-in] Copy less bytes in `parse_function`

src/back/spv/writer.rs
(Obviously subjective, but I figured I'd see what folks think.)
This adds six `use` declarations and eliminates ~300 identifiers.
I tried to avoid cases where SPIR-V and Naga use similar terminology. For example,
`BuiltIn` remains `spirv::BuiltIn` or `crate::BuiltIn`.
=> [spv-out]: Add some `use` declarations to the writer.

src/back/msl/writer.rs, tests/out/collatz.msl.snap, tests/out/image-copy.msl.snap, tests/out/quad-vert.msl.snap, tests/out/quad.msl.snap, tests/out/shadow.msl.snap, tests/out/skybox.msl.snap
Apparently, there are SPIR-V in the wild that require packed vec3...
This code introduces a crude but tiny and localized workaround.
=> MSL packed vectors and shorter expressions

src/front/spv/error.rs, src/front/spv/function.rs, src/front/spv/mod.rs
Fixes #675 
I admit, this is a real PITA, and this code reflects it.
The workaround I wanted to implement was to issue an `Load` into the matrix if we see it being row-major, followed by `Transpose`, then pretending that it was column-major all this time.
The problem is that there are many ways to cross that "ima matrix" barrier:
- `OpAccessChain` doesn't have intermediate IDs, so we can't do it iteratively
- it may start high up and end on a matrix, or on an element of it
- it turns out, an array of matrices, when being a struct field, can also have this row-major decoration
If anybody can have a better idea, I'd love to consider it!
=> SPV-in workaround for row-major matrices

src/back/msl/mod.rs
This struct is used by the [`EntryPointMap`](https://github.com/gfx-rs/gfx/blob/3ee1ca9ba486b166a52765024d8d149cbb28d486/src/backend/metal/src/native.rs#L30-L36) in the gfx Metal backend. Implementing `Serialize` and `Deserialize` for this means that we can then serialize a SPIR-V -> MSL transformation cache (see also https://github.com/gfx-rs/gfx/pull/3719 and https://github.com/gfx-rs/gfx/issues/3716#issuecomment-816575736).
=> Add Serialize/Deserialize derives for `mtl::EntryPointError`

src/valid/expression.rs
Fixes #696
Based on the [spec for textureDimensions()](https://gpuweb.github.io/gpuweb/wgsl/#texturedimensions) - it should be valid for all image classes without mip level param.
=> Fix validation for `textureDimensions(t)` call

src/back/msl/writer.rs
See https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf table 6.5.
Before:
```glsl
#version 450
void main() {
colour = vec4(1.0/0.0, 0.0/0.0, 0.0, 1.0);
}
```
->
```metal
constexpr constant metal::float4 const_type1_ = {inf, NaN, 0.0, 1.0};
```
->
```
inf_nan.metal:4:50: error: use of undeclared identifier 'inf'
constexpr constant metal::float4 const_type1_ = {inf, NaN, 0.0, 1.0};
^
inf_nan.metal:4:55: error: use of undeclared identifier 'NaN'
constexpr constant metal::float4 const_type1_ = {inf, NaN, 0.0, 1.0};
```
After:
```metal
constexpr constant metal::float4 const_type1_ = {INFINITY, NAN, 0.0, 1.0};
```
=> [Metal] Handle `NaN` and `inf` correctly in constants

src/back/msl/writer.rs
Closes https://github.com/gfx-rs/naga/issues/695. It could probably be a little tidier though, I'm open to suggestions.
```glsl
#version 450
layout(location = 0) in float a;
layout(location = 1) in float b;
layout(location = 2) in float c;
void main() {
float l = length(a);
float d = distance(b, c);
float ds = dot(b, c);
colour = vec4(l, d, ds, 1.0);
}
```
->
```metal
void main1(
thread float const& a,
thread float const& b,
thread float const& c,
thread metal::float4& colour
) {
float l;
float d;
float ds;
l = metal::abs(a);
d = metal::abs(b - c);
ds = b * c;
colour = metal::float4(l, d, ds, 1.0);
return;
}
```
=> [Metal] Handle `length(float)` and `distance(float, float)`

src/back/msl/writer.rs
This seemed important to clarify.
=> Add a note about references and pointers to `Expression::Load`

Makefile
The snapshot files in tests/out start with headers like this:
---
source: tests/snapshots.rs
expression: dis
---
; SPIR-V
; Version: 1.0
; Generator: rspirv
...
The Makefile's `validate-foo` targets trim off those lines with `tail -n +5`
before submitting their test to the validators.
However, some versions of the `insta` crate seem to generate headers with an
extra blank line, like this:
---
source: tests/snapshots.rs
expression: dis
---
This makes the `validate-foo` targets unhappy.
This commit changes the `validate-foo` targets to use `sed` to cope with both
kinds of headers.
=> Makefile: Be more flexible in removing YAML headers from snapshots.

src/back/spv/writer.rs
Non-exhaustive matches on `Expression` make it harder to review changes that add
new enum variants, because the compiler can't tell you that you've missed a
case.
Although I believe Clippy is able to do so, I don't think we should make a
blanket rule of forbidding wildcard match arms against `Expression`. There are a
few matches that are only concerned with a handful of variants, or a single
variant. For example, variant, naga::front::spv::Parser::next_block is only
concerned with whether an expression is a constant or not. In principle, these
sites should also be checked when adding a new variant, but it seems too
burdensome to require them to list all the `Expression` variants they don't care
about. The principle should be applied only to matches that are already handling
most variants. …
=> Avoid non-exhaustive matches on Expression.

src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/msl/writer.rs, src/back/spv/writer.rs, src/front/glsl/constants.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/typifier.rs, src/valid/analyzer.rs, src/valid/expression.rs, tests/errors.rs, tests/in/boids.wgsl, tests/in/operators.param.ron, tests/in/operators.wgsl, tests/in/shadow.wgsl, tests/out/boids.msl, tests/out/boids.spvasm, tests/out/operators.Vertex.glsl, tests/out/operators.msl, tests/out/operators.spvasm, tests/out/shadow.Fragment.glsl, tests/out/shadow.info.ron, tests/out/shadow.msl, tests/out/shadow.ron, tests/out/shadow.spvasm, tests/snapshots.rs
See https://github.com/gpuweb/gpuweb/pull/1611
This PR adds the `Expression::Splat` variant to the IR. This is useful, versus relying on `Expression::Compose`, since the splat is much more limited, and these expressions do not require heap allocated component lists.
This is fairly trivial to support in the backends.
As for the frontends, WGSL has a bit of (necessary) complexity to auto-detect splats and build the proper IR. SPV-in also has a small piece to detect when a splat is used.
=> Vector splats

Makefile, src/back/glsl/features.rs, src/valid/interface.rs, tests/in/interpolate.param.ron, tests/in/interpolate.wgsl, tests/out/interpolate.Fragment.glsl, tests/out/interpolate.Vertex.glsl, tests/out/interpolate.msl, tests/out/interpolate.spvasm, tests/snapshots.rs
This PR adds a snapshot test for the old version of the WGSL interpolate attribute. A dependent PR brings its syntax up to date.
This change required the following:
- Make the GLSL back end check whether the requested interpolation qualifiers are supported in the requested GLSL version.
- In the validator, permit interpolation on bindings for both vertex shader outputs and fragment shader inputs.
- Let snapshot tests request a specific desk version of GLSL.
These changes are in separate commits for review. All commits should pass CI, so they shouldn't require squashing for that reason.
=> [wgsl-in] Add basic test for `interpolate` attribute.

src/back/msl/mod.rs
Oops! We must have missed this one during refactoring. Needed for https://github.com/gfx-rs/gfx/pull/3719.
=> Derive `Eq` for `msl::Options`

src/front/spv/mod.rs, src/proc/typifier.rs, src/valid/compose.rs, src/valid/expression.rs, src/valid/mod.rs, tests/out/collatz.info.ron, tests/out/shadow.info.ron
Fixes #726 
Here is what it says now:
> Constant [25] 'XYZ2RGB' is invalid:
Composing expects 3 components but 9 were given
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', bin/convert.rs:219:61
Note: we'll likely need to allow this particular case in WGSL. That's not the point of this PR. Instead, it tries to cover the gap we had in the composite constant validation, and share this code with composite expressions.
=> Validate composite constants

bin/convert.rs, src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/hlsl/mod.rs, src/back/hlsl/writer.rs, tests/snapshots.rs
As discussed in https://github.com/gfx-rs/naga/pull/727.
`wgsl-out` will be fixed in another PR.
=> Use fmt::Writer instead of io::Writer for glsl and hlsl backend

src/back/msl/writer.rs, tests/out/access.msl, tests/out/boids.msl, tests/out/operators.msl, tests/out/shadow.msl
As an example of how this is used, this now means that the following can compile:
```glsl
#version 450
layout(location = 0) flat in uvec4 xyz;
layout(location = 0) out uvec4 colour;
void main() {
colour = xyz >> 2;
}
```
->
```metal
#include <metal_stdlib>
#include <simd/simd.h>
void main1(
thread metal::uint4& colour,
thread metal::uint4 const& xyz
) {
colour = xyz >> as_type<uint4>(int4(2));
return;
}
struct main2Input {
metal::uint4 xyz1 [[user(loc0), flat]];
};
struct main2Output {
metal::uint4 member [[color(0)]];
};
fragment main2Output main2(
main2Input varyings [[stage_in]]
) {
metal::uint4 colour = {};
metal::uint4 xyz = {};
const auto xyz1 = varyings.xyz1;
xyz = xyz1;
main1(colour, xyz);
return main2Output { colour };
}
```
(The `int4` is `glslc` being bad)
=> [Metal] Impl `Expression::Splat`

src/back/dot/mod.rs, src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/msl/mod.rs, src/back/msl/writer.rs, src/back/spv/instructions.rs, src/back/spv/writer.rs, src/front/glsl/constants.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/interpolator.rs, src/proc/typifier.rs, src/valid/analyzer.rs, src/valid/expression.rs, src/valid/interface.rs, tests/errors.rs, tests/out/image-copy.msl, tests/out/operators.Vertex.glsl, tests/out/operators.msl, tests/out/operators.spvasm, tests/out/shadow.Fragment.glsl, tests/out/shadow.msl, tests/out/shadow.spvasm, tests/out/skybox.Vertex.glsl, tests/out/skybox.msl, tests/out/skybox.spvasm
Closes #681
As you can see, the produced output is much better now.
@grovesNL there is one controversial thing here - removal of the invalid access test in WGSL. We were generally trying to have a single place where inputs are validated. So WGSL code only has to validate the state that the IR validation doesn't cover. The access expressions are fully covered now, so technically WGSL should leave it to IR for validation.
However, the IR validation errors are nearly not as nice, and this is a general problem we have that needs more thought. We can consider #358 to be this issue.
=> Swizzle expression

README.md, bin/convert.rs
This is follow-up from https://github.com/gfx-rs/naga/pull/742#discussion_r617075895
It contains a number of small but important improvements, especially now that the binary is a part of the upcoming release, and people may use it via `cargo install naga`:
- if no output argument is specified, we only validate the module, we don't print the IR out
- if it's a success, we are explicitly printing "Validation successful" now. Otherwise it's not obvious if something happened or not.
- to print the IR out, one would specify "-" as the output. That is similar to existing tools, like the Metal compiler (where it's treated as "accept input from stdin").
- the validation errors are printed in stderr, so that they don't get mixed into the console output. One can redirect the IR into a file and …
=> Don't print the module in converter if no output is specified

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/in/quad.wgsl, tests/in/skybox.wgsl
Matches https://github.com/gpuweb/gpuweb/pull/1493
First, I tried to build a helper `ArgumentList` class to contain the logic of argument iteration, but it turns out to be quite hairy. I ended up with this approach where `Lexer` just have a few helpers to deal with the parens and trailing commas, and it seems to be mostly ok.
=> WGSL trailing commas

src/back/msl/writer.rs
MSL doesn't support 1D levels...
We may want to validate it earlier.
=> [msl] don't use sample level on 1D textures

src/back/msl/writer.rs
Fixes https://github.com/gfx-rs/naga/issues/760.
=> [Metal] Set `is_scoped` to false when evaluating a swizzle subexpression

Makefile, bin/convert.rs, src/back/wgsl/mod.rs, src/back/wgsl/writer.rs, tests/out/empty.wgsl, tests/snapshots.rs
Improve `wgsl-out` backend. A lot of code has been copy-pasted from `glsl-out` and `msl-out`.
Now it can produce simple shader:
In:
```wgsl
// vertex
let c_scale: f32 = 1.2;
struct VertexOutput {
[[location(0)]] uv : vec2<f32>;
[[builtin(position)]] position : vec4<f32>;
};
fn main([[location(0)]] pos : vec2<f32>, [[location(1)]] uv : vec2<f32>) -> VertexOutput {
return VertexOutput(uv, vec4<f32>(c_scale * pos, 0.0, 1.0));
}
```
Out:
```wgsl
let c_scale: f32 = 1.2;
struct VertexOutput {
[[location(0)]] uv: vec2<f32>;
[[builtin(position)]] position: vec4<f32>;
};
fn main([[location(0)]] pos: vec2<f32>, [[location(1)]] uv: vec2<f32>) -> VertexOutput {
return VertexOutput(uv1, vec4<f32>(c_scale * pos, 0.0, 1.0));
}
```
=> Improve wgsl-out

src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/mod.rs, src/front/glsl/parser.rs
- Export some type to allow for error handling for the user
- Load local variables
- Fix type constructors with a single argument
- Add `textureLod` function
- Add support for the `in` keyword in function parameters
=> [glsl-in] small usability fixes

src/front/spv/mod.rs, src/valid/expression.rs
Part of  #620, covering the add and subtract
=> [spv-in] work around sign differences in OpIAdd and OpISubtract

src/front/spv/function.rs
Follow-up to #746 , where the issue was introduced.
Tightly related to #781, which detects this problem.
=> [spv-in] emit the cast expression for builtin signness

src/back/glsl/mod.rs, src/back/msl/writer.rs, src/back/spv/writer.rs, src/front/spv/mod.rs, src/lib.rs, src/proc/mod.rs, src/proc/typifier.rs, src/valid/expression.rs
This doesn't seem to be in wgsl (yet?) but it's in glsl, spv and metal so I think it's reasonable to add it into the IR.
Here's an glsl example:
```glsl
#version 450
void main() {
vec3 incidence = vec3(0.0, 1.0, 0.0);
vec3 normal = vec3(0.0, 1.0, 0.0);
float ior = 1.0;
colour = vec4(refract(incidence, normal, ior), 1.0);
}
```
=> Add `MathFunction::Refract`

src/back/spv/writer.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, src/valid/expression.rs, tests/in/operators.wgsl, tests/out/operators.msl, tests/out/operators.spvasm
And also enable support for entry-point-less modules in SPIR-V, since this is useful for testing.
=> Support unary not in WGSL

src/back/msl/writer.rs, tests/out/access.msl, tests/out/quad-vert.msl
This fixes https://github.com/gfx-rs/naga/issues/741. Unfortunately it currently breaks the `quad-vert.msl` snapshot with this error:
```
Validating quad-vert.msl
<stdin>:40:30: error: type 'type6' is not valid for attribute 'clip_distance'
type6 gl_ClipDistance1 [[clip_distance]];
^~~~~~~~~~~~~
<stdin>:42:8: error: invalid return type 'main2Output' for vertex function
vertex main2Output main2(
^
<stdin>:54:86: error: type 'type6' does not provide a subscript operator
const auto _tmp = type10 {v_uv, _.gl_Position, _.gl_PointSize, {_.gl_ClipDistance[0]}};
~~~~~~~~~~~~~~~~~^~
3 errors generated.
```
This right solution to fix this test would be for `gl_ClipDistance` to be treated as a `float` instead of a `float[1]` in `msl-out`.
=> [msl-out] wrap arrays in structs so that they can be returned by functions

src/front/spv/function.rs, src/front/spv/mod.rs
This adds a constant for `PI / 180` as suggested in https://github.com/gfx-rs/naga/issues/786#issuecomment-827092368.
As a test:
```glsl
#version 450
void main() {
float deg = 15.0;
float rad = radians(deg);
float deg_again = degrees(rad);
colour = vec4(vec3(deg_again), 1.0);
}
```
->
```metal
...
void main1(
thread metal::float4& colour
) {
float deg;
float rad;
float deg_again;
deg = 15.0;
rad = deg * 0.017453292519943295;
deg_again = rad / 0.017453292519943295;
metal::float3 _e16 = float3(deg_again);
colour = metal::float4(_e16.x, _e16.y, _e16.z, 1.0);
return;
}
...
```
=> [spv-in] Impl `GLOp::Radians` and `GLOp::Degrees`

src/front/spv/convert.rs, src/front/spv/mod.rs, src/lib.rs, src/valid/expression.rs
This PR adds support for the `Int8`, `Int16`, and `Int64` capabilities to the spirv frontend, as well as support for `OpArrayLength`, `OpCopyMemory`, `OpInBoundsAccessChain`, `OpLogicalNotEqual`, and `OpLogicalEqual`.
=> Add several additional ops to the spirv frontend.

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, src/valid/expression.rs
This PR adds `arrayLength` support to the WGSL frontend.
=> Add support for arrayLength to the wgsl frontend

bin/naga.rs, src/front/spv/error.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, tests/errors.rs
SPV-in's error didn't derive `Error` and wasn't even publicly exposed.
WGSL's error had a lifetime, which makes it unable to form error chains, see https://github.com/dtolnay/thiserror/issues/68
This PR is largely made to address https://github.com/gfx-rs/wgpu/issues/1359
=> Error improvements in WGSL-in and SPV-in

src/back/glsl/mod.rs
Partially fix #812
Before:
```glsl
struct type20 {
vec2 member;
vec4 member1;
vec4 gl_Position1;
float gl_PointSize1;
type gl_ClipDistance1[1]; //unknown type
};
```
After:
```glsl
struct type20 {
vec2 member;
vec4 member1;
vec4 gl_Position1;
float gl_PointSize1;
float gl_ClipDistance1[1];
};
```
=> [glsl-out] Fix scalar arrays writing

src/back/msl/mod.rs, src/back/msl/writer.rs, tests/in/access.param.ron, tests/in/boids.param.ron, tests/in/skybox.param.ron, tests/out/boids.msl
This allows the sizes buffer slots to be tightly packed.
=> Unify back::msl push constants map and sizes buffer

src/front/spv/mod.rs
Looks like we just missed this one.
Needed for something like
```glsl
void main() {
bool y = true;
bool n = false;
colour = vec4(vec3(y == n), 1.0);
}
```
=> [spv-in] Handle `Op::LogicalEqual`

src/front/spv/mod.rs
This is implemented on the glsl front and backends, the wgsl frontend and the spv backend thus far.
=> [spv-in] Handle `Glo::MatrixInverse`

src/back/spv/writer.rs, src/front/spv/mod.rs
Test case:
```glsl
#version 450
void main() {
vec3 a = vec3(1.0);
vec3 b = vec3(2.0);
mat3 z = outerProduct(a, b);
colour = vec4(cross(a, b), 1.0);
}
```
=> [spv-in,spv-out] Handle outer product

src/back/glsl/features.rs
Fix #822. But I think it would be better if we can skip `gl_PerVertex` in glslang generated spv, somehow (in `spv-in`, or backend side).
This PR doesn't completely fix #812 case, because `glsl-out` generate uninitialized global variables (#834):
```
Caused by:
In Device::create_render_pipeline
Internal error in VERTEX shader: Shader module failed to compile: 0:60(9): warning: `gen_gl_VertexIndex' used uninitialized
0:63(14): warning: `tex_left_top' used uninitialized
0:72(14): warning: `tex_right_bottom' used uninitialized
0:74(12): warning: `color' used uninitialized
0:98(2): error: implicitly sized arrays cannot be assigned
shader compilation failed: Vertex
``
=> [glsl-out] Add clip distance feature

Cargo.toml, src/front/spv/error.rs, src/front/spv/flow.rs, src/front/spv/function.rs, src/front/spv/mod.rs
Fixes #613, #691, #578, #683
Makes obsolete: #690 
A lot of stuff is borrowed/inspired by Tint.
Changes
- Added postorder traversal
- Added constructs based on postorder traversal
- Add HashSet of all points traversal should be stopped
- Reworked when/where to stop for if selection
- Slightly improved CFG Visualization for better debugging
- Adds loop detection
- Replaces of cloning blocks with move
=> spv-in: path forward

bin/naga.rs, src/valid/mod.rs
This is useful to run #747, which we know will not be happy about some of the control flow uniformity checks we have.
=> Validation parameter for the converter

src/front/spv/flow.rs, src/front/spv/function.rs, src/front/spv/mod.rs
This is a HACK: we patch 2 known cases where the domination block emitted expressions that were later used by the parent:
- "if () { something } else { break; }"
- "switch () { default: something }"
Fixes #586
Closes #409
=> [spv-in] patch the SPIR-Vs wacky CFG cases by hand

src/back/glsl/features.rs, src/back/glsl/mod.rs, tests/out/quad-vert.Vertex.glsl, tests/out/quad.Vertex.glsl, tests/out/skybox.Vertex.glsl, tests/snapshots.rs
With this patch we can run patched `wgpu_glyph` (#812) with GL and Naga.
Fix #812
**cross:**
naga:
At least it stop crashing :smile:.
=> [glsl-out] Handle uninitialized global variables

src/back/wgsl/writer.rs, tests/out/access.wgsl, tests/out/empty.wgsl, tests/out/quad-vert.wgsl, tests/out/quad.wgsl, tests/snapshots.rs
First attempt to generate shader from spv frontend. Draft only because I can't fix all validation errors.
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/proc/interpolator.rs:90:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [validate-wgsl] Error 101
```
=> [wgsl-out] Enable snapshot testing for spv-in quad shader

src/back/msl/writer.rs, tests/out/collatz.msl, tests/out/shadow.msl, tests/snapshots.rs
Another (big) follow-up to #825
The original code was written in a way that doesn't consider entry points truly independent. We'd globally figure out if the sizes buffer is needed anywhere, and then blindly use it on all functions and entry points. This doesn't work if, say, the pipeline layout doesn't include some of the globals used by the program.
Instead, this PR determines, for each function, whether or not the sizes buffer is needed.
=> [msl] make sizes buffer local to each function

src/proc/mod.rs, tests/wgsl-errors.rs
If an array has a bogus length constant (a boolean, say), `TypeInner::span` will panic. However, the problem will be caught in validation, and this function is needed in front ends, which should never panic on invalid input.
This PR also moves `tests/errors.rs` to `tests/wgsl-errors.rs` and makes the entire file conditional on the `wgsl-in` feature, before adding some integration tests.
=> TypeInner::span: Tolerate bad array length constants for now.

src/back/glsl/mod.rs, src/back/spv/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/parser.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/layouter.rs, src/proc/mod.rs, src/valid/interface.rs, src/valid/mod.rs, src/valid/type.rs, tests/out/collatz.ron, tests/out/shadow.ron, tests/wgsl-errors.rs
Fixes #867
Pretty much reverts #663
Cleans up the code according to https://github.com/gpuweb/gpuweb/pull/1560
Refactors the layouter (again) to be re-used by both WGSL-in and SPV-in.
The line of thought is the following:
1. array alignment needs to be based on the base type
1. which makes it the first type that need to know the alignment of a base type
1. except for the structure, which already has the alignment in IR
1. should array have an alignment in IR as well? that would be unfortunate, the structure one also doesn't appear to be very useful or helpful to anybody.
1. maybe we can remove the struct alignment from the IR? then we can make the layouter look up the base types for both arrays and structures
1. dine
=> Remove alignment from struct IR

src/back/dot/mod.rs, src/front/wgsl/mod.rs
`Cow<'a, str>` implements `From<String>` and `From<&'a str>`, which makes creating them a bit nicer. And it seems like `Cow` is the right fit for the labels in `wgsl::ParseError`, which are sometimes fixed strings and sometimes formatted.
=> Use Cow more effectively.

src/back/msl/writer.rs, src/back/spv/writer.rs, tests/in/access.param.ron, tests/in/boids.param.ron, tests/in/collatz.param.ron, tests/in/control-flow.param.ron, tests/in/empty.param.ron, tests/in/extra.param.ron, tests/in/image.param.ron, tests/in/operators.param.ron, tests/in/quad-glsl.param.ron, tests/in/quad.param.ron, tests/in/shadow.param.ron, tests/in/skybox.param.ron, tests/in/standard.param.ron, tests/out/access.spvasm, tests/out/image.spvasm, tests/snapshots.rs
=> Fix deriving SPIR-V capabilities

.github/workflows/lazy.yml
Part of #747.
Test run - https://github.com/Gordon-F/naga/runs/2629733528. Now we can validate 130 out of 300 shaders.
=> Add Vulkan tutorial shaders to lazy check

src/back/spv/writer.rs, src/front/spv/mod.rs, src/lib.rs, src/proc/interpolator.rs, src/valid/interface.rs, tests/wgsl-errors.rs
The `apply_common_default_interpolation` helper function would panic if bindings
were missing, but missing bindings should be something that front ends can count
on validation to detect, so the helper should just return silently.
The validator returned `InvalidType` errors for missing bindings, apparently
because variables without bindings must be structs that do have bindings. But
this is unhelpful when you've just forgotten to label an argument. So this patch
adds a new, more specific, `VaryingError` variant.
=> Improve error messages for missing I/O bindings.

src/valid/interface.rs, src/valid/type.rs
WGSL requires that runtime-sized arrays appear only as the last member of a
structure in in the `storage` storage class. It seems to me that Naga should
enforce this restriction on its own IR as well.
=> Require dynamically sized arrays to appear in 'storage' memory.

src/front/wgsl/conv.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/wgsl-errors.rs
Improves error messages by adding spans for most wgsl lexer errors and adding more information to many messages to remove ambiguity.
For example:
**before**
```rust
error: expected paren, found '('
┌─ wgsl:49:13
│
49 │         vec4(c)
│             ^ expected paren
```
**after**
```rust
error: expected '<', found '('
┌─ wgsl:49:13
│
49 │         vec4(c)
│             ^ expected '<'
```
or
**before**
```rust
error: invalid type cast to `vec4`
```
**after**
```rust
error: cannot cast a struct to a vec4<f32>
┌─ wgsl:50:18
│
50 │         vec4<f32>(in)
│                  ^^^^ cannot cast a struct to a vec4<f32>
```
This also fixes a bug in which an integer or floating point constant with some invalid widths could be accepted. For example, the constant `3.0f33` was treated as an `f32` constant. …
=> [wgsl-in] Improve wgsl lexer error messages

src/valid/expression.rs
This wgsl currently fails validation (with error `Expression [43] is invalid Operation Add can't work with [21] and [42]`):
```
fn main() -> [[location(0)]] f32 {
let a = mat4x4<f32>(
vec4<f32>(0., 0., 0., 0.),
vec4<f32>(0., 0., 0., 0.),
vec4<f32>(0., 0., 0., 0.),
vec4<f32>(0., 0., 0., 0.),
);
let b = mat4x4<f32>(
vec4<f32>(0., 0., 0., 0.),
vec4<f32>(0., 0., 0., 0.),
vec4<f32>(0., 0., 0., 0.),
vec4<f32>(0., 0., 0., 0.),
);
let c: mat4x4<f32> = a + b;
return c.x.x;
}
```
According to the spec (https://www.w3.org/TR/WGSL/#arithmetic-expr) component-wise addition should work.
=> Validate matrix component-wise ops correctly

src/back/glsl/mod.rs, tests/out/quad-vert.Vertex.glsl, tests/out/quad.Fragment.glsl, tests/out/quad.Vertex.glsl, tests/out/shadow.Fragment.glsl, tests/out/skybox.Fragment.glsl, tests/out/skybox.Vertex.glsl
GLSL ES 3.0 allows location to be specified on attributes. This is not allowed for varyings, hence the extra guard against interpolations.
This change fixes wgpu's Cube example in WebGL2 (and possibly others, but I haven't tested that yet), particularily on MacOS, where the driver likes to assign locations out of order.
=> Insert attribute glsl location qualifier for opengl ES 3.0

src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/variables.rs
Adds a check to all entry points arguments if they should be read.
Fixes validation for the following snippet:
```glsl
// Vertex
void main() {
gl_Position = vec4(1);
fragColor = gl_Position;
}
```
=> [glsl-in] Read global in prologue only if allowed

src/back/spv/writer.rs, src/lib.rs, src/proc/mod.rs, src/proc/typifier.rs, src/valid/expression.rs, tests/in/access.wgsl, tests/out/access.msl, tests/out/access.spvasm, tests/out/access.wgsl, tests/wgsl-errors.rs
This makes Naga IR validation impose the restrictions added to WGSL in
gpuweb/gpuweb#1801.
Remove code in the SPIR-V writer to spill arrays to temporary variables in order
to index them dynamically. If such IR is encountered, treat it as a failure of
validation.
(This simplifies #916 a little bit, so I took it on first.)
=> Permit dynamic indexing of arrays and matrices only behind a pointer.

src/front/spv/flow.rs
Should fix https://github.com/gfx-rs/naga/issues/940. However, I am getting error ```The `break`/`continue` is used outside of a loop context``` from Naga.
The produced IR is identical to that of Tint for the shader in question. Naga should accept break statements inside switch cases I believe.
I also slightly improved the .dot output.
=> WIP: [spv-in] CFG: add break statements in switch selections

tests/out/quad-glsl.wgsl, tests/snapshots.rs
These began appearing in 344acc31 (João Capucho, 2021-06-01), but were
apparently left out of the PR.
=> Add snapshot output files for quad-glsl.glsl.

src/back/msl/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/ast.rs, src/front/glsl/parser.rs, src/front/spv/flow.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/proc/interpolator.rs, src/valid/interface.rs
Most of code suggestions are found by new `clippy` lints - [mem_replace_with_default ](https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_with_default) and [needless_borrow](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow).
=> Fix nightly clippy suggestions

src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/lex.rs, src/front/glsl/parser.rs, src/front/glsl/token.rs, src/front/glsl/variables.rs, tests/in/glsl/246-collatz.comp, tests/out/quad-glsl.wgsl
Contains a bunch of bug fixes and implements more parts of the parser to
finally be able to parse the collatz compute shader and other compute
shaders.
When I started working on this I thought it would be a simple thing but
it proved more complex, here&rsquo;s a list of the things included in this PR
-   Add parsing for compute shader workgroup modifiers (fixes #246)
-   Add support for the buffer storage class (fixes #902)
-   Add mod function and use implicit conversions for it&rsquo;s arguments
-   Add implicit conversions for locals initializers
-   Add glGlobalInvocationID builtin
-   Fixes a panic when calculating global use
-   Refractor the way global and blocks are handled to reduce code
duplication
-   Fixes unsized types being loaded
-   Fixes assignments for function arguments …
=> [glsl-in] Compute shader fixes and additions

fuzz/fuzz_targets/spv_parser.rs
Hi, naga team.
I found compile-time error in spv_parser.rs fuzzer test.
Could you review and accept my changes, pls?
error[E0061]: this function takes 2 arguments but 1 argument was supplied
--> fuzz_targets/spv_parser.rs:7:19
|
7   |     let _result = Parser::new(data.into_iter()).parse();
|                   ^^^^^^^^^^^ ---------------- supplied 1 argument
|                   |
|                   expected 2 arguments
|
note: associated function defined here
--> /Users/evgeny.proydakov/repository/naga/src/front/spv/mod.rs:411:12
|
411 |     pub fn new(data: I, options: &Options) -> Self {
|            ^^^
error: aborting due to previous error
Best regards, Proydakov Evgeny.
=> Fixed compile-time error in spv fuzzer test.

.github/workflows/lazy.yml, .github/workflows/pipeline.yml, Makefile, README.md
One thing that we missed in #938. Currently, `cargo run --all-features` running 0 tests.
=> Fix testing infrastructure

Makefile
Without this, `make validate-wgsl` fails, complaining that `cli` doesn't have a `wgsl-in` feature.
=> Makefile: Make validate-wgsl target use new 'cli' sub-package.

.github/workflows/pipeline.yml, Cargo.toml
Naga is now a workspace with `naga` and `cli` as its two members. The default
package for cargo commands is `cli`, so that `cargo run` will just run the CLI.
However, this has a few unexpected consequences:
- Now `cargo test` will just try to run `cli`'s tests, of which there are none.
Adding `"."` to the `default-members` list in the workspace's `Cargo.toml`
seems to fix this, without breaking `cargo run`.
- Even with `"."` added to `default-members`, `cargo test` will build `naga` by
default with the features requested for it in `cli/Cargo.toml`: all the front
and back ends, but no `serialize` or `deserialize`. This means that our CI job
meant to verify no-feature builds isn't doing that job any more. We need to
pass `--package naga` to `cargo test` to make it test naga directly.
=> Add `.` to the workspace's default members. Test with no features.

.github/workflows/lazy.yml
At the moment lazy CI task failed:
```
Run cargo build --release --features spv-in,msl-out --bin naga
Updating crates.io index
Updating git repository `https://github.com/Kangz/glslpp-rs.git`
error: none of the selected packages contains these features: msl-out, spv-in
Error: Process completed with exit code 101.
```
=> Remove features from lazy CI task

src/valid/mod.rs
This comment claims that the following work is being done after global
validation, but it actually appears before global validation.
=> Validator::validate: Remove bogus comment.

README.md
Since `wgsl-out` can handle all snapshot test set, we can update its status.
=> Update `wgsl-out` status in README

src/back/msl/writer.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/out/access.msl, tests/out/access.wgsl, tests/out/globals.spvasm
This change allows constant index expressions parsed by wgsl-in to be consumed by spv-out. Otherwise, the access is always treated as dynamic. Those accesses are often generated by `glsl-in -> wgsl-out` translation for matrix cast expression, which previously prevented those shaders to be further translated into spirv.
The msl-out change is also required, as this change surfaced a bug when generating those const accesses, emitting incorrect code from snapshot tests.
=> [wgsl-in] use AccessIndex for accesses using constant index

cli/src/main.rs, src/front/glsl/error.rs, src/front/glsl/parser.rs, src/front/glsl/parser_tests.rs, src/front/glsl/variables.rs
=> Glsl error message improvements

src/back/spv/mod.rs, src/lib.rs, src/proc/layouter.rs, src/valid/type.rs
This is dependent on #916 (some of the claims depend on those changes landing).
GitHub doesn't seem to have a concept of one PR depending upon another, so just look at the last commit to see the changes unique to this PR.
=> Improve docs for `TypeInner`, `valid::TypeFlags`, and some internal types.

src/valid/function.rs
If validation fails, `Validator` may be left with entries in
`valid_expression_list` and `valid_expression_set`. The validator does clear the
set before examining a function's body, but not the list, which means a
long-lived `Validator` could accumulate an unbounded amount of garbage in the
list.
(Minor cleanup: use structural update syntax where appropriate.)
=> Clear Validator::valid_expression_list before validating each function.

src/front/glsl/ast.rs, src/front/glsl/lex.rs, src/front/glsl/parser.rs, src/front/glsl/parser_tests.rs, src/front/glsl/token.rs, src/front/glsl/variables.rs
Corrects the `VertexIndex` and `InstanceIndex` to be uint and adds support for parsing precision qualifiers and statements
Fixes #1001
Fixes #1002
Fixes #1003
=> [glsl-in] Fix builtin type and add support for precision qualifiers

src/valid/function.rs
=> Refactor control flow validation, allow break in switches

src/front/glsl/parser.rs
This fixes GLSL shaders like:
```glsl
#version 450 core
void foo(int i[3]) {}
void main() {
int array[3];
foo(array);
}
```
Previous error:
<pre><font color="#F66151"><b>error</b></font><b>: Unknown function &apos;foo&apos;</b>
<font color="#12488B">┌─</font> array.vert:7:5
<font color="#12488B">│</font>
<font color="#12488B">7</font> <font color="#12488B">│</font>     <font color="#C01C28">foo(array)</font>;
<font color="#12488B">│</font>     <font color="#C01C28">^^^^^^^^^^</font>
</pre>
=> [glsl-in] Deduplicate constants so array types match

src/back/spv/mod.rs, src/back/spv/writer.rs, src/back/wgsl/writer.rs
Rather than giving `Block` an optional `terminator` field in addition to its
`body`, track block termination statically, with two types:
- `Block` is a block without a termination instruction. This is what most code
generation functions operate on.
- `TerminatedBlock` is a block with a termination instruction. This is what
`Function::blocks` holds.
The `Function::consume` method takes a `Block` by value, together with a
termination instruction, and turns it into a `TerminatedBlock`.
This lets us remove some unwraps and awkward conditions.
As part of this change, `Writer::write_block` no longer hits an `unimplemented!`
for Naga statements following `Break`, `Return`, and so on. Instead, it simply
doesn't emit code for them, which is a correct translation. If we want to forbid
these, we …
=> [spv-out] Track block termination statically.

src/back/spv/layout.rs, src/back/spv/mod.rs, src/back/spv/recyclable.rs, src/back/spv/writer.rs, src/back/wgsl/writer.rs
A single `Writer` can be reused to convert any number of Naga IR modules to
SPIR-V. This lets us reuse the heap allocations, but makes us responsible for
resetting the state of the `Writer` fully between modules. The old code
neglected to clear several different fields: logical_layout (all fields),
lookup_type, and cached_constants.
This commit uses Rust struct literal expressions to construct the re-initialized
`Writer`, which makes the compiler check that each field has been handled.
It also introduces a policy limiting how much storage will be retained, so that
processing the occasional whale doesn't leave us with leviathan buffers
permanently.
=> [spv-out] Properly reset `Writer`s between module writes.

cli/src/main.rs, src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/msl/mod.rs, src/lib.rs, tests/in/access.param.ron, tests/in/boids.param.ron, tests/in/interpolate.param.ron, tests/in/skybox.param.ron, tests/out/glsl/skybox.fs_main.Fragment.glsl, tests/out/glsl/skybox.vs_main.Vertex.glsl, tests/snapshots.rs
=> [glsl-out] binding location mapping

src/front/glsl/functions.rs, src/front/glsl/parser_tests.rs
First look for exact matches before trying the implicit
lookup. Otherwise, finding two wrong matches first will
result in an ambiguous function error.
This logic could use with a bit of a cleanup, keeping
track of a closer score and doing more exact matching
on types, but this might be good enough for now.
=> [glsl-in] Fix function lookup

src/front/glsl/error.rs, src/front/glsl/parser.rs
So we can get a source location rather than a panic.
=> glsl: Replace todo!() with a NotImplemented error

src/back/glsl/mod.rs, src/front/glsl/parser.rs, src/lib.rs, tests/in/interpolate.param.ron, tests/in/skybox.param.ron, tests/out/glsl/quad-vert.main.Vertex.glsl, tests/out/glsl/quad.main.Vertex.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl
Similar to SPIR-V, by default we should assume the "native" coordinate space of the language. In case of OpenGL, this means depth from -1 to 1.
@JCapucho we'll need to do something opposite for glsl-in, unless we are already doing something :)
Draft because I'm still figuring out how to make `shadow` example working
=> glsl-out: adjust coordinate space

src/back/glsl/mod.rs, src/back/wgsl/writer.rs, src/front/spv/error.rs, src/front/spv/function.rs, src/front/spv/image.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/valid/analyzer.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/type.rs, tests/in/texture-arg.wgsl, tests/out/analysis/collatz.info.ron, tests/out/analysis/shadow.info.ron, tests/out/glsl/texture-arg.main.Fragment.glsl, tests/out/msl/texture-arg.msl, tests/out/wgsl/texture-arg.wgsl, tests/snapshots.rs
WIP.
spv-in accepts shaders with sampling using a function argument and the validator partially supports it, the `sampling_set` of `FunctionInfo` only supports globals still so it can't validate shaders with this yet.
=> Handle texture/sampler function arguments

src/front/glsl/ast.rs, src/front/glsl/functions.rs, tests/in/glsl/clamp-splat.vert, tests/out/wgsl/clamp-splat-vert.wgsl
=> [glsl-in] Implicitly splat the results of clamp()

src/back/msl/keywords.rs
It seems that `this` is a reserved keyword in metal. Mark it as such.
=> [msl-out] Add 'this' as a reserved keyword

src/front/glsl/ast.rs, src/front/glsl/functions.rs
- Fix IR for shifts between vector and scalars
- Implicitly splat mix selector if needed
- Add implicit casts to some more builtin functions
=> [glsl-in] More fixes

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, src/valid/type.rs, tests/wgsl-errors.rs
Most errors still need improvements (using debug output for type handles, better descriptions, etc.), but just trying to capture most of the existing behavior for now, and switch to spans wherever it's easily possible.
We cover most of `wgsl::Error` with snapshots now, but still missing a few places (e.g. `ResolveError` variants or all of the possible cases for `Unexpected` tokens).
=> wgsl-in: add more error tests

Makefile, src/back/hlsl/mod.rs, src/back/hlsl/writer.rs, tests/out/hlsl/interface.hlsl, tests/out/hlsl/interface.hlsl.config, tests/snapshots.rs
1. Implement `Select` expression.
2. Enable `interface` snapshot
3. Return only real names for entry point in ReflectionInfo, instead of tuple (stage, name).
4. Properly write locations for fragment output (`SV_TargetN`, instead of `LOCN`)
=> [hlsl-out] More improvements 

src/back/spv/block.rs, tests/in/operators.wgsl, tests/out/glsl/operators.main.Fragment.glsl, tests/out/hlsl/operators.hlsl, tests/out/msl/operators.msl, tests/out/spv/operators.spvasm, tests/out/wgsl/operators.wgsl
The IR accepts select expressions which take a bool condition and select
between two vectors, whilst spirv only allows for component-wise
selects.
Now if the condition is a scalar and the object a vector we implicitly
splat the condition.
=> [spv-out] Support object-wise select

src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs, src/front/glsl/types.rs, tests/out/wgsl/246-collatz-comp.wgsl, tests/out/wgsl/constant-array-size-vert.wgsl
yet another one of these types of PR, this time we have
- Support for parsing all texture types and for shadow samplers
- Implicit splatting of arguments for the `max` builtin
- A fix for implicit conversions using bitcast instead of a regular cast
- Support for parsing array initializers of the form `type[maybe_size](components)`, glsl has this quirk that initializers for arrays without a size aren't actually dynamic but the size comes from the argument count, so things like `float[](1,2,3,4)` is of type `float[4]`
=> [glsl-in] Improvements and fixes

src/back/spv/block.rs, src/back/spv/index.rs, src/back/spv/mod.rs, src/back/spv/writer.rs
Since the table of cached expressions is only meaningful within a single
function, it's really something that should only be accessed from
`BlockContext`.
However, to save heap allocations, it makes sense to retain it in the `Writer`
between functions. But the `Writer` field should have a different name, to
ensure people don't use it by accident.
=> [spv-out] Move cached expression table to BlockContext.

src/back/wgsl/writer.rs, src/front/wgsl/conv.rs, src/lib.rs, tests/in/interpolate.wgsl, tests/out/wgsl/210-bevy-2d-shader-frag.wgsl, tests/out/wgsl/210-bevy-2d-shader-vert.wgsl, tests/out/wgsl/210-bevy-shader-vert.wgsl, tests/out/wgsl/800-out-of-bounds-panic-vert.wgsl, tests/out/wgsl/bevy-pbr-frag.wgsl, tests/out/wgsl/bevy-pbr-vert.wgsl, tests/out/wgsl/bool-select-frag.wgsl, tests/out/wgsl/clamp-splat-vert.wgsl, tests/out/wgsl/extra.wgsl, tests/out/wgsl/interface.wgsl, tests/out/wgsl/interpolate.wgsl, tests/out/wgsl/multiple_entry_points-glsl.wgsl, tests/out/wgsl/quad-vert.wgsl, tests/out/wgsl/quad.wgsl, tests/out/wgsl/quad_glsl-frag.wgsl, tests/out/wgsl/quad_glsl-vert.wgsl, tests/out/wgsl/shadow.wgsl, tests/out/wgsl/skybox.wgsl
This PR improves Naga's WGSL output by omitting parts of interpolation attributes which match default values.
It also enables the parsing of [`center` interpolation sampling](https://gpuweb.github.io/gpuweb/wgsl/#interpolation).
=> Improve WGSL interpolation attributes

Cargo.toml, cli/src/main.rs, src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/mod.rs, src/front/glsl/parser_tests.rs, src/front/glsl/variables.rs, tests/out/wgsl/210-bevy-2d-shader-frag.wgsl, tests/out/wgsl/quad_glsl-frag.wgsl, tests/snapshots.rs
WGSL will require this. Note that this still might
cause some issues with multi-entry-point GLSL
that I didn't know how to handle. That is, we will
handle unused builtin inputs but not unused
builtin outputs correctly right now. This is an existing
issue though, not a regression.
This is also provided as an option, but I feel like
the more correct approach is to never strip linkage
variables. We'll see though.
=> [glsl-in] Keep around extra linkage variables

src/back/glsl/mod.rs, tests/in/quad.param.ron, tests/out/glsl/quad-vert.main.Vertex.glsl, tests/out/glsl/quad.fs_extra.Fragment.glsl, tests/out/glsl/quad.main.Fragment.glsl, tests/out/glsl/quad.main.Vertex.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl, tests/out/glsl/skybox.fs_main.Fragment.glsl, tests/out/glsl/skybox.vs_main.Vertex.glsl
Should help https://github.com/gfx-rs/wgpu/issues/1617
Here is the breakdown:
- "location" is supported unconditionally for VS inputs and FS outputs
- "location" requires GLSL ES 310 for varyings (VS outputs and FS inputs)
- "binding" requires GLSL ES 310
=> glsl-out: fix emission of location/binding attributes

tests/snapshots.rs
Use `env_logger::try_init` to avoid complaints about repeated initialization. This function is thread-safe.
=> Enable logging in WGSL and SPIR-V tests.

Makefile, src/back/msl/mod.rs, src/back/msl/writer.rs, tests/in/extra.param.ron, tests/out/msl/access.msl, tests/out/msl/boids.msl, tests/out/msl/collatz.msl, tests/out/msl/control-flow.msl, tests/out/msl/empty.msl, tests/out/msl/extra.msl, tests/out/msl/globals.msl, tests/out/msl/image.msl, tests/out/msl/interface.msl, tests/out/msl/interpolate.msl, tests/out/msl/operators.msl, tests/out/msl/quad-vert.msl, tests/out/msl/quad.msl, tests/out/msl/shadow.msl, tests/out/msl/skybox.msl, tests/out/msl/standard.msl, tests/out/msl/texture-arg.msl
Follow-up to #1097, which reverts the macos min version change, but instead allows each test to carry the version it was made with, and validate against this. So now we can make sure different MSL versions are tested.
=> Validate the exact MSL version

src/back/wgsl/writer.rs, tests/out/wgsl/interpolate.wgsl
=> wgsl: Don't output interpolate(flat) for non-float arguments

tests/in/image.wgsl, tests/out/hlsl/image.hlsl, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/wgsl/image.wgsl
Prior to this change, nothing in the test suite exercised the SPIR-V backend
code for generating LOD or Sample arguments to OpImageFetch instructions.
=> Add tests for sampling mipmapped and multisampled images.

Makefile, tests/out/hlsl/control-flow.hlsl.config, tests/out/hlsl/empty.hlsl.config, tests/out/hlsl/globals.hlsl.config, tests/out/hlsl/image.hlsl.config, tests/out/hlsl/interface.hlsl.config, tests/out/hlsl/interpolate.hlsl.config, tests/out/hlsl/operators.hlsl.config, tests/out/hlsl/quad-vert.hlsl.config, tests/out/hlsl/quad.hlsl.config, tests/out/hlsl/shadow.hlsl.config, tests/out/hlsl/skybox.hlsl.config, tests/out/hlsl/standard.hlsl.config, tests/snapshots.rs
All entry points validations passed 🚀.
Still uses config files, but with a more readable `Makefile`. My attempt to implement validation with comments inside hlsl shaders makes `Makefile` unreadable at all and full of dark magic.
=> [hlsl-out] Validate all entry points in Makefile

src/back/hlsl/writer.rs, tests/out/hlsl/image.hlsl, tests/out/hlsl/shadow.hlsl, tests/out/hlsl/skybox.hlsl, tests/out/hlsl/standard.hlsl
It turns out `mul` is strictly for dot product kinds of things
=> hlsl-out: use * for vector by vector multiplication

src/back/glsl/mod.rs, src/back/wgsl/writer.rs, tests/out/glsl/boids.main.Compute.glsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/glsl/empty.main.Compute.glsl, tests/out/glsl/globals.main.Compute.glsl, tests/out/glsl/operators.main.Compute.glsl, tests/out/glsl/quad-vert.main.Vertex.glsl, tests/out/glsl/quad.fs_extra.Fragment.glsl, tests/out/glsl/quad.main.Fragment.glsl, tests/out/glsl/quad.main.Vertex.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl, tests/out/glsl/skybox.fs_main.Fragment.glsl, tests/out/glsl/skybox.vs_main.Vertex.glsl, tests/out/glsl/standard.derivatives.Fragment.glsl, tests/out/glsl/texture-arg.main.Fragment.glsl
I ran into an [error](https://matrix.to/#/!FZyQrssSlHEZqrYcOb:matrix.org/$XhLgbZcu0uCYJjUm07uVTNUjwCxjOXv8etwaOt7_y8E?via=matrix.org&via=mozilla.org&via=kyju.org) while targeting WebGL where the shaders failed to link because of differing precision between vertex and fragment shaders in a uniform with an integer field. This explicitly sets the integer precision to `highp` so that they match across vertex and fragment shaders.
=> Add Explicit Int Precision for GLSL ES Backend

cli/Cargo.toml, cli/src/main.rs
- Use argh for parsing commandline arguments and generating help message
- Remove almost all panics and handle errors by printing them and
exiting 1
Resolves #1107 
---
This adds the `argh` dependency for argument parsing which adds a measurable amount of compile time:
**Before:**
Targets: | naga-cli 0.4.0 (bin "naga")
-- | --
Total time: | 23.6s
**After:**
Targets: | naga-cli 0.4.0 (bin "naga")
-- | --
Total time: | 25.3s
That's a 1.7s ( 7.2% ) increase in build time on a clean release build.
If this is undesired I can switch it back to using the old parser, update the help message for the old parser to include available options, and keep the improved error handling introduced in this PR.
=> Improve CLI Argument Doc and Error Handling

src/back/glsl/features.rs
Will fail with an error when trying to generate a GLSL shader that has
dynamically sized arrays in a version of GLSL that does not support
dynamically sized arrays.
=> Gate GLSL Dynamic Array Size to Supported Versions

cli/src/main.rs
Allows output file to be left empty to perform validation only.
=> Fix Regression With CLI Not Working for Validation

src/back/glsl/features.rs, src/back/glsl/mod.rs
Prunes all unused, unsized types that are not referenced by globals used by the current entrypoint for the GLSL backend.
=> Prune Unused, Unsized Types From GLSL Output

src/back/hlsl/writer.rs, tests/out/hlsl/control-flow.hlsl, tests/out/hlsl/empty.hlsl, tests/out/hlsl/image.hlsl, tests/out/hlsl/interface.hlsl, tests/out/hlsl/interpolate.hlsl, tests/out/hlsl/operators.hlsl, tests/out/hlsl/quad-vert.hlsl, tests/out/hlsl/shadow.hlsl, tests/out/hlsl/skybox.hlsl, tests/out/hlsl/standard.hlsl
Those bool casts on vectors were wrong. And on scalars I think they aren't necessary.
=> hlsl: remove the boolean casts for unary operators

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/valid/expression.rs, tests/out/glsl/boids.main.Compute.glsl, tests/out/glsl/quad-vert.main.Vertex.glsl, tests/out/glsl/skybox.vs_main.Vertex.glsl
This PR contains:
1. Allow to translate from bool to another type in validator
1. [hlsl-out] Allow sint array size
1. [hlsl-out] Fix local variable writing with array type
1. [glsl-out] Fix array type writing
1. [glsl-out] Fix zero initialization for local variables
=> Fixes for zero init variables and variables with array type for hlsl and glsl backends

src/front/glsl/parser.rs
Should be the last place needing implicit conversions.
Closes #900
=> [glsl-in] Add implicit conversion for initializer

src/front/glsl/ast.rs, src/front/glsl/mod.rs, src/front/glsl/offset.rs, src/front/glsl/parser.rs, tests/out/wgsl/246-collatz-comp.wgsl
Implements the rules described in section 7.6.2.2 of the OpenGl spec to calculate the offsets of struct members
=> [glsl-in] Implement layouting for structs

src/back/glsl/mod.rs, src/back/hlsl/storage.rs, src/front/glsl/ast.rs, src/front/glsl/functions.rs
Extracts the `function_call` to `function_or_constructor_call` to reduce the indentation, adds implicit conversion for texture functions and implements `textureGrad`.
=> [glsl-in] Texture function improvements

src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs, src/front/mod.rs
glsl has no concept of depth images, so the frontend when parsing a constructor for shadow combined samplers will convert the image from sampled to depth, further more to support this when using textures passed trough function arguments a bitset is used that upon function call will be checked and will also convert the image type if needed.
=> [glsl-in] Add support for shadow sampling

src/front/glsl/ast.rs, src/front/glsl/constants.rs, src/front/glsl/functions.rs, src/front/glsl/lex.rs, src/front/glsl/offset.rs, src/front/glsl/parser.rs, src/front/glsl/token.rs, src/front/glsl/variables.rs
All the fixes are contained in their own commits and can be reviewed individually
- Use the same splatting logic of `max` for `min`
- Fix missing implicit conversion on `mix`
- Parse `restrict`, `readonly` and `writeonly` (no logic yet, only parsing)
- Accept precision qualifiers in locals
- Handle `pow` in constant evaluation
- Fix the span of a `gvec3`
=> [glsl-in] Fixes and improvements

src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs, src/front/glsl/variables.rs, tests/out/wgsl/210-bevy-2d-shader-frag.wgsl, tests/out/wgsl/210-bevy-2d-shader-vert.wgsl, tests/out/wgsl/210-bevy-shader-vert.wgsl, tests/out/wgsl/800-out-of-bounds-panic-vert.wgsl, tests/out/wgsl/bevy-pbr-frag.wgsl, tests/out/wgsl/bevy-pbr-vert.wgsl, tests/out/wgsl/bool-select-frag.wgsl, tests/out/wgsl/clamp-splat-vert.wgsl, tests/out/wgsl/multiple_entry_points-glsl.wgsl, tests/out/wgsl/quad_glsl-frag.wgsl, tests/out/wgsl/quad_glsl-vert.wgsl
Glsl allows things such as
```glsl
layout (location = 0) in vec4 a;
vec4 b = a;
```
In this case `b` depends on `a` which can't be known at compile time, so it's necessary to add a small prologue to the entry point to initialize it.
The prologue for global initialization is added after the prologue that assigns from the entry point arguments to globals because the parser utilizes this globals as opposed to the arguments.
=> [glsl-in] Add support for non constant global init

src/back/spv/block.rs, src/valid/expression.rs, tests/in/operators.wgsl, tests/out/glsl/operators.main.Compute.glsl, tests/out/hlsl/operators.hlsl, tests/out/msl/operators.msl, tests/out/spv/operators.spvasm, tests/out/wgsl/operators.wgsl
See https://github.com/gpuweb/gpuweb/pull/1974
I'm not totally sure if it's worth getting this into IR, or just resolve at the WGSL frontend side.
Pros:
- more compact backend output, since there are no splats introduced if not needed (WGSL, GLSL, HLSL)
- supporting the idea of "WGSL is text form of our IR", which is the basis for #752 
- less logic in GLSL-in and WGSL-in
Cons:
- more logic in SPV-out and the validator
- less restricted IR - more difficult to fuzz, etc
=> Allow mixing on a scalar selector

src/front/glsl/ast.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs, src/front/glsl/variables.rs, tests/out/wgsl/246-collatz-comp.wgsl, tests/out/wgsl/280-matrix-cast-vert.wgsl, tests/out/wgsl/long-form-matrix-vert.wgsl
All the fixes are contained in their own commits and can be reviewed individually
- Respect user defined interpolation
- Lower the init expression in for loops
- Use std430 for `buffer` objects (as defined in the spec)
- Reduce number of produced vector resizes (makes the output more readable)
- Matrix initializers with only one scalar produce diagonal matrices
- `mix` when using a boolean selector has inverted argument order (compared to the IR and SPV)
=> [glsl-in] Fixes and improvements #2

src/front/wgsl/mod.rs
The message previously made reference to the now-removed `access` attribute.
=> Fix Invalid Type Attribute Error Message

src/arena.rs, src/front/glsl/context.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/parser/expressions.rs, src/front/glsl/parser/functions.rs
Introduces a new type `StmtContext` which now holds the `Arena<HirExpr>`, this type is needed because lowering requires a disjoint borrow otherwise a clone is needed.
This type is reused in between lowers, this needed a new method on the `Arena` equal to it's `Vec` counterpart `clear`.
=> [glsl-in] Don't clone HirExpr when lowering

src/back/spv/block.rs, tests/out/spv/shadow.spvasm
In `back::spv::Writer::write_texture_coordinates`, `OpCompositeConstruct` can concatenate scalars and vectors, so when combining coordinates with an array index, there is no need to extract the coordinate vector's components individually: once the index has been converted to the appropriate component type, it can be combined with the coordinates in a single instruction.
=> [spv-out]: Use OpCompositeConstruct's schmear behavior.

Cargo.toml, src/arena.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/block.rs, src/front/glsl/constants.rs, src/front/glsl/context.rs, src/front/glsl/functions.rs, src/front/glsl/offset.rs, src/front/glsl/parser.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/parser/expressions.rs, src/front/glsl/parser/functions.rs, src/front/glsl/parser/types.rs, src/front/glsl/token.rs, src/front/glsl/types.rs, src/front/glsl/variables.rs, src/front/mod.rs, src/front/spv/flow.rs, src/front/spv/function.rs, src/front/spv/image.rs, src/front/spv/mod.rs, src/front/spv/null.rs, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/terminator.rs, src/span.rs, src/valid/analyzer.rs
Proof of concept for #358 .
Currently not used in any kind of back error reporting, just wanted to see what it takes to generate span information in a parser. Turns out it's pretty okay!
=> Proof of concept for "span" feature, with WGSL & GLSL parsing augmented.

src/back/spv/block.rs, tests/in/image.wgsl, tests/out/hlsl/image.hlsl, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/wgsl/image.wgsl
Some SPIR-V texture access instructions take coordinates as integers, others as
floats. The types of coordinates in Naga expressions generally match those in
SPIR-V, but Naga indices for arrayed textures are always integers, whereas
SPIR-V combines coordinates and array indices into a single vector, so indices
need to be cast to match the coordinate component type.
This commit makes `write_texture_coordinates` properly cast array indices to
match the coordinates' component type before combining them all into a single
result vector.
Fixes #1186.
=> [spv-out] Writer::write_texture_coordinates: Fix result type.

src/back/hlsl/writer.rs, tests/out/hlsl/interface.hlsl, tests/out/hlsl/quad-vert.hlsl
Closes #1183
Likely resolves #1182, at least for WebGPU case.
=> [hlsl-out] re-order interface struct fields

src/back/wgsl/writer.rs
This PR fixes #1191 by moving the `writeln!` statement responsible for printing the ending brace for case statements from just after the cases loop to being the last statement of the cases loop. This means that a closing brace is printed for each case statement instead of just the cases section as a whole.
All existing unit tests have passed after this change, and so has the `make validate-wgsl` command. However, this PR does not currently add any unit tests for switch cases. While making this edit, I was unable to find the unit tests for `back::wgsl::Writer`. Do these tests exist? And if so, where should I integrate the tests for switch case writing?
=> [wgsl-out] Move case-closing-brace writer inside cases loop

src/front/wgsl/mod.rs
This allows using `step` as a variable name, for example.
=> [wgsl-in] parse identifiers before builtin function calls

src/front/spv/mod.rs
We don't handle span information so it's very simple one line change
=> [spv-in] Parse OpNoLine

src/front/spv/mod.rs
The availability is checked at run-time by the validator.
=> [spv-in] allow float16 and float64

src/back/msl/writer.rs
=> [msl-out]: avoid inner structure for run-time array sizes

src/back/wgsl/writer.rs, src/front/wgsl/conv.rs, src/front/wgsl/mod.rs, tests/out/wgsl/246-collatz-comp.wgsl, tests/out/wgsl/access.wgsl, tests/out/wgsl/boids.wgsl, tests/out/wgsl/collatz.wgsl
Closes #1211 
Writes pointer types with the new syntax, adds support for the function storage class and writes dereferences where needed.
(Will follow up with dereference support for wgsl-in)
=> [wgsl-out] Write pointers types and loads

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs
Previously the constructor just used the type of the scalar argument
regardless of whether or not it actually matched the vector splat
constructors target type. This resulted in e.g. `vec2<f32>(0)`
erroneously getting the type of a bi-vector of Sints with width 4.
Now the splat constructor checks that the kind and width of the scalar
argument is the same as that of the target specified in the
constructor's type parameter.
For example, this code
```wgsl
fn main() {
let z = vec2<f32>(0);
let z_norm_sq = dot(z, z);
}
```
now results in the following error:
```
error: cannot cast a i32 to a vec2<f32>
┌─ wgsl:2:22
│
2 │     let z = vec2<f32>(0);
│                      ^^^ cannot cast a i32 to a vec2<f32>
Could not parse WGSL
```
Fixes #1222.
=> Fix WGSL vector splat constructor's type handling

src/front/glsl/parser/functions.rs, src/front/glsl/parser_tests.rs
This would otherwise cause the parser to enter an infinite loop.
Fixes #1232
=> [glsl-in] Allow expression statements to begin with ++ or --

src/front/glsl/ast.rs, src/front/glsl/context.rs, src/front/glsl/functions.rs, src/front/glsl/parser.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/parser/functions.rs, src/front/glsl/parser_tests.rs
Previously we always set the lhs flag when lowering to generate a
pointer so that dynamic indexing would work, this would produce an error
on constant variables since they can't be in a lhs context.
Now we introduce an enum which distinguishes not only between lhs and
rhs but also in array base, if lowering in a lhs context the base is
also lowered in a lhs context but if lowering in rhs the base is lowered
in a special array base context which bypasses the mutability check.
Fixes #1237
=> [glsl-in] Allow dynamic indexing on constant variables

src/front/glsl/offset.rs
=> [glsl-in] Use power of two alignment for bad type in struct

src/front/glsl/offset.rs
=> [glsl-in] Align child structs when calculating offsets

src/back/msl/writer.rs, src/back/spv/layout.rs, src/valid/analyzer.rs, tests/snapshots.rs
Passes cargo check and cargo test. 
PS: Running cargo test changes some files in tests/out (`#version 310 es`, seems to upgrade the shader to 310), but I didn't include them here because they are not changed by this PR. I think these should be under the .gitignore, as it's the shader output of the tests? Might be helpful to track the changes of the output shaders over time, though, in which case you can simply clone the repo and run cargo test, it edits these files:
=> Fix some clippy suggestions

src/back/spv/block.rs, src/back/spv/mod.rs, src/back/spv/recyclable.rs, src/back/spv/writer.rs
Remove 'forbidden_caps'.
Accumulate capabilities actually used separately from the permitted
capabilities, so that the latter can be retained across Writer resets, while the
former is cleared between modules.
=> [spv-out] Clean up capability handling.

src/back/glsl/mod.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/front/glsl/builtins.rs, src/front/spv/mod.rs
According to https://github.com/gpuweb/gpuweb/issues/1381 `MathFunction::Round` always goes to the even number when the fractional part is `.5`. But in spirv, glsl and msl the default `round` leaves this case as implementation defined, to fix this in spirv and glsl we now use `roundEven` and in msl `rint`.
=> Fix round in backends and add support for roundEven in frontends

.github/workflows/pipeline.yml, Cargo.toml, README.md
Puts infrastructure and documentation in place to allow a newer bitflags yet still warning about the MSRV trap.
Would be nice to backport this as well.
=> Allow Newer Bitflags

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, tests/in/control-flow.wgsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/hlsl/control-flow.hlsl, tests/out/msl/control-flow.msl, tests/out/wgsl/control-flow.wgsl, tests/snapshots.rs
=> [hlsl-out] Implement switch statement

src/back/hlsl/mod.rs, src/back/hlsl/writer.rs, tests/out/hlsl/access.hlsl, tests/out/hlsl/boids.hlsl, tests/out/hlsl/collatz.hlsl, tests/out/hlsl/control-flow.hlsl, tests/out/hlsl/image.hlsl, tests/out/hlsl/interface.hlsl, tests/out/hlsl/interpolate.hlsl, tests/out/hlsl/quad-vert.hlsl, tests/out/hlsl/quad.hlsl, tests/out/hlsl/shadow.hlsl, tests/out/hlsl/skybox.hlsl, tests/out/hlsl/standard.hlsl
This PR largerly rewrites the logic responsible to match input/output interfaces for HLSL. It's a follow-up to #1189
The new code is more isolated and robust. It works on structures that are used as both host-shared and entry point i/o.
=> HLSL: rewrite handling of interface matching rules

cli/src/main.rs, src/back/mod.rs, src/back/spv/block.rs, src/back/spv/image.rs, src/back/spv/index.rs, src/back/spv/instructions.rs, src/back/spv/mod.rs, src/back/spv/selection.rs, src/back/spv/writer.rs, src/lib.rs, tests/in/bounds-check-image-restrict.param.ron, tests/in/bounds-check-image-restrict.wgsl, tests/in/bounds-check-image-rzsw.param.ron, tests/in/bounds-check-image-rzsw.wgsl, tests/in/bounds-check-zero.wgsl, tests/out/spv/bounds-check-image-restrict.spvasm, tests/out/spv/bounds-check-image-rzsw.spvasm, tests/out/spv/bounds-check-zero.spvasm, tests/snapshots.rs
Here's the work-in-progress for bounds checks on `ImageLoad` and `ImageStore` for the SPIR-V back end.
Status: all three `IndexBoundsCheckPolicy` variants, for all texture types:
=> Texture bounds checks

src/front/spv/function.rs, src/front/spv/image.rs, src/front/spv/mod.rs
Fixes #1275
Problem was the interaction between these things:
- associated data for each function, tracking how each of the parameters is sampled
- topological sort of the function call graph
The latter was reshuffling the function handles, while the former stored a separate array with data addressable by handles. So after the topological sort they got de-synchronized.
=> [spv-in] track function parameter sampling flags across handle permutation

src/back/spv/writer.rs, tests/out/spv/image.spvasm, tests/spirv-capabilities.rs
Add a new test, `spirv-capabilities.rs`, for quickly assessing which SPIR-V features a small code fragment requires.
Also, fix the processing of cube array images:
- Using 1D images should require either the `Sampled1D` or `Image1D` capability.
- Using cube array images should require either the `SampledCubeArray` or
`ImageCubeArray` capability.
=> [spv-out] Quick tests for capability requests.

Cargo.toml, src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, src/front/wgsl/number_literals.rs, src/front/wgsl/tests.rs, tests/in/interpolate.wgsl, tests/in/operators.wgsl, tests/out/glsl/boids.main.Compute.glsl, tests/out/glsl/operators.main.Compute.glsl, tests/out/glsl/quad.main.Vertex.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl, tests/out/hlsl/boids.hlsl, tests/out/hlsl/image.hlsl, tests/out/hlsl/operators.hlsl, tests/out/hlsl/quad.hlsl, tests/out/hlsl/shadow.hlsl, tests/out/msl/boids.msl, tests/out/msl/image.msl, tests/out/msl/operators.msl, tests/out/msl/quad.msl, tests/out/msl/shadow.msl, tests/out/wgsl/boids.wgsl, tests/out/wgsl/image.wgsl, tests/out/wgsl/operators.wgsl, tests/out/wgsl/quad.wgsl, tests/out/wgsl/shadow.wgsl, tests/wgsl-errors.rs
I tried to implement lexing for all different types of number literals
as described by the current working draft and editor's draft
(they are the same for the literal definitions at the time of writing).
This should bring naga closer to being able to parse all kinds of number literals,
partially resolving #866 for example.
The next step would be to also allow for parsing of these new kinds of number literals,
as the currently used `FromStr::parse` won't work for hexadecimal literals (float or integer), see rust-lang/rfcs#1098.
The relevant code for this seems to be here:
https://github.com/gfx-rs/naga/blob/e384bce771db1d7dd156e9e29afe9d9235984924/src/front/wgsl/mod.rs#L1027-L1060
I have added the test cases I had written up for #866 to `tests/in/operators.wgsl` since they seem to fit in …
=> Implement lexing and parsing for all WGSL number literal types

fuzz/Cargo.toml
Set naga features in `fuzz/Cargo.toml` to those required for SPIR-V and
WGSL input.
Also bump libfuzzer-sys version.
The current fuzzing setup doesn't use the currently required features for SPIR-V and WGSL input (likely due to a feature name / default feature set change), making the compilation of the fuzzing targets fail.
With the adjusted `Cargo.toml` fuzzing works again, and has already found me a stack overflow (I'll open an issue / PR for that later).
=> Fix fuzzing setup

src/back/spv/block.rs, tests/in/control-flow.wgsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/hlsl/control-flow.hlsl, tests/out/msl/control-flow.msl, tests/out/spv/control-flow.spvasm, tests/out/wgsl/control-flow.wgsl, tests/snapshots.rs
=> [spv-out] Handle break and continue in switch statements.

src/back/glsl/mod.rs, tests/in/control-flow.wgsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/hlsl/control-flow.hlsl, tests/out/msl/control-flow.msl, tests/out/spv/control-flow.spvasm, tests/out/wgsl/control-flow.wgsl
Fixes #1309 by partially reverting 02c74b50021379092a9d4567fd11aeb0879c5405.
Also cleans up the GLSL output by only inserting a `break` where a case is not already broken out of at the end of the case body and inserts a comment indicating explicitly fallthrough cases.
Also adds a test case for switch statements not in the last statement position of a function, because those might have return statements inserted, which previously might have made it harder to notice some missing `break`s that should have been inserted.
=> Fix GLSL output for non-fallthrough switch cases

src/back/glsl/mod.rs, tests/out/glsl/operators.main.Compute.glsl
When there is a vector as the condition for `Expression::Select` we use a `mix` in the glsl backend but the first argument is the reject and the second the accept this was inverted.
This should probably be backported as can cause surprising results.
=> [glsl-out] Fix select order

src/front/glsl/offset.rs, src/front/glsl/parser/declarations.rs, src/front/mod.rs, src/front/spv/mod.rs
From the llvm discourse on whether spirv with missing offset decorations
> For non-external storage classes, the struct does not need to be explicitly laid out.
Seems like `shaderc` does this and I had shader where all offsets were 0, this PR fixes it by using a similar strategy to glsl frontend to calculate span/offsets.
=> [spv-in] Handle structs with no offset decorations

src/back/glsl/mod.rs, src/back/hlsl/storage.rs, src/back/hlsl/writer.rs, src/back/mod.rs, src/back/msl/writer.rs, src/back/wgsl/writer.rs
Follow up #1319.
Refactoring indent logic for hlsl, glsl, wgsl backends.
=> Refactoring indent logic for backends

src/valid/mod.rs
This was causing warnings in nightly (1.56.0).
=> Move `#[must_use]` attr on `Capabilities` to where it'll take effect.

src/front/spv/mod.rs
Some idiot (me) decided to put essential code inside of `debug_assert` and then was surprised why it didn't work in release.
=> [spv-in] Move essential code out of debug_assert

src/back/wgsl/writer.rs, tests/in/glsl/fma.frag, tests/out/wgsl/fma-frag.wgsl
Regression from ce676cf13090b87e1405640ea8ee43e1a1666005.
We need to output (*d).mx rather than *d.mx, at least according to Tint.
wgsl-in seems to handle *d.mx just fine, which is likely a separate bug.
=> Output parentheses around dereference

src/back/wgsl/writer.rs, src/front/wgsl/mod.rs, tests/in/skybox.wgsl
See the spec - https://gpuweb.github.io/gpuweb/wgsl/#module-scope-variables
> A variable in the private, workgroup, uniform, or storage storage classes:
>    Must be declared with an explicit storage class decoration.
>    Must use a store type as described in § 4.3.6 Storage Classes.
=> wgsl-in: require storage class to be given

src/front/wgsl/mod.rs, tests/out/glsl/access.foo.Vertex.glsl, tests/out/glsl/boids.main.Compute.glsl, tests/out/glsl/operators.main.Compute.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl, tests/out/hlsl/access.hlsl, tests/out/hlsl/boids.hlsl, tests/out/hlsl/operators.hlsl, tests/out/hlsl/shadow.hlsl, tests/out/msl/access.msl, tests/out/msl/boids.msl, tests/out/msl/operators.msl, tests/out/msl/shadow.msl, tests/out/spv/access.spvasm, tests/out/spv/boids.spvasm, tests/out/spv/bounds-check-zero.spvasm, tests/out/spv/operators.spvasm, tests/out/spv/shadow.spvasm, tests/out/wgsl/access.wgsl, tests/out/wgsl/boids.wgsl, tests/out/wgsl/operators.wgsl, tests/out/wgsl/shadow.wgsl
Make the parser code more closely follow the spec's grammar around `unary_expression`, `postfix_expression`, and `singular_expression`.
Change the handling of postfix expressions (indexing, member/component access, and swizzling) to apply the indirection at the appropriate time, resulting in code improvements on all output formats. For example, where we used to generate the following MSL:
metal::float4 _e13 = bar.matrix[3];
float b = _e13.x;
we now generate, simply:
float b = bar.matrix[3].x;
Propagate WGSL reference types correctly, so that parenthesizing expressions no longer causes the Load Rule to be applied.
Together with #1332 (already landed), this is a replacement for #1312, and unblocks #1352.
Fixes #1351.
=> [wgsl-in] Rework Load Rule handling and indirection.

src/span.rs
Without this change, the `to_range` method method returns `None` even when spans are enabled.
=> Correctly recognize defined spans.

src/back/wgsl/writer.rs, tests/out/wgsl/access.wgsl, tests/out/wgsl/globals.wgsl
Now that the WGSL front end distinguishes pointers and references correctly, we can land this.
Fixes #1352.
=> [wgsl-out] Properly parenthesize address-of expressions.

src/front/glsl/ast.rs, src/front/glsl/context.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/variables.rs
Constants that are to be dynamically indexed now are first transformed
into locals with them as the initializer.
Closes #1343
=> [glsl-in] Use local for constant indexing

src/front/glsl/builtins.rs
This caused arrayed textures to not be accepted
Closes #1231
=> [glsl-in] Fix bad bit pattern in texelFetch

src/front/glsl/ast.rs, src/front/glsl/context.rs, src/front/glsl/parser/expressions.rs, tests/in/glsl/prepostfix.frag, tests/out/wgsl/246-collatz-comp.wgsl, tests/out/wgsl/constant-array-size-vert.wgsl, tests/out/wgsl/prepostfix-frag.wgsl
Add support for float, vector and matrices targets.
Fix prefix and postfix being inverted (one was returning the value
of the other).
Remove an unneeded local indirection for prefix handling.
Add tests.
Closes #1344
=> [glsl-in] Improve pre/postfix handling

src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/hlsl/conv.rs, src/back/msl/mod.rs, src/back/spv/writer.rs, src/front/spv/convert.rs, src/front/spv/mod.rs, src/lib.rs, src/valid/interface.rs
Adds support for [`VK_KHR_multiview`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_multiview.html).
Adds the `ViewIndex` builtin which is only supported in spirv and glsl (2/5 backends), spirv-cross has two types of handling for this, for metal it uses a variable with the value 0, for hlsl it throws an error. This PR errors on both backends.
I understand that since this is not part of webgpu it's not a priority, but I needed it for a project which consumed spirv and used it in both vulkan and gles for stereo rendering and spirv-cross was not liking being cross compiled so I ended up patching naga and using it, so feel free to close.
=> Add support for multi view extensions

src/front/spv/function.rs
Naga is generating `break; fallthrough;` statements at the end of each case for any switch statement in my shaders (SPIR-V compiled from GLSL). The tint WGSL compiler used by Chromium rejects these shaders because the `fallthrough;` statement is obviously unreachable code. These changes prevent generating a `fallthrough` when the last statement of the case body always exits the switch.
I've never written Rust before, let me know if this idiomatic code.
=> Avoid case fallthrough when last statement is break, continue, kill or return

src/back/wgsl/writer.rs, tests/out/wgsl/operators.wgsl
Bitcasting a vector to a vector is valid according to the WGSL spec: https://www.w3.org/TR/WGSL/#bitcast-expr
The current wgsl-out code generates an unsigned-integer-to-float  conversion expression when compiling `uintBitsToFloat(uvec3)`, instead of the expected bitcast.
=> wgsl-out: vector bitcast

cli/src/main.rs, src/front/glsl/ast.rs, src/front/glsl/builtins.rs, src/front/glsl/context.rs, src/front/glsl/error.rs, src/front/glsl/functions.rs, src/front/glsl/lex.rs, src/front/glsl/mod.rs, src/front/glsl/offset.rs, src/front/glsl/parser.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/parser/expressions.rs, src/front/glsl/parser/functions.rs, src/front/glsl/parser/types.rs, src/front/glsl/parser_tests.rs, src/front/glsl/token.rs, src/front/glsl/types.rs, src/front/glsl/variables.rs
Removes the old `SourceMetadata` and replaces it with the crate wide `Span`.
They were but equal conceptually and structurally so there was no reason to keep both of them around, this removes a whole bunch of conversions.
=> [glsl-in] Use Span instead of SourceMetadata

src/back/glsl/mod.rs, tests/in/cubeArrayShadow.wgsl, tests/out/glsl/cubeArrayShadow.fragment.Fragment.glsl, tests/snapshots.rs
Adds checks that it isn't used in an unsupported function and emits the
depth_ref as a separate argument.
Closes #1153
=> [glsl-out] Improve handling of samplerCubeArrayShadow

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/parser/functions.rs, src/front/wgsl/mod.rs, src/front/wgsl/number_literals.rs, src/lib.rs, src/valid/function.rs, tests/in/control-flow.wgsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/hlsl/control-flow.hlsl, tests/out/msl/control-flow.msl, tests/out/spv/control-flow.spvasm, tests/out/wgsl/control-flow.wgsl
The wgsl spec defines that the switch selector must be a scalar integer type, this encompasses both signed and unsigned integers. This PR adds support for unsigned integers.
Furthermore the spec defines that the type of the selector and the case value type must match this PR also adds validation for that.
Closes #1029
=> Allow unsigned integers in switch

src/front/glsl/builtins.rs, src/front/glsl/functions.rs
- Takes a big part related to calculating the `Conversion` to it's own function to make it more clear what the algorithm is doing
- renames from declaration to overload were applicable to make it more correct
- adds a load of comments
- makes `sampled_to_depth` always defer errors. 
Overall just some house keeping, this part of the code is a bit more complicated so I felt that documentating it was the right thing to do.
=> [glsl-in] Refractor overload selector and add comments

src/back/wgsl/writer.rs, src/front/wgsl/mod.rs, src/proc/mod.rs, src/valid/compose.rs, src/valid/function.rs, tests/in/pointers.param.ron, tests/in/pointers.wgsl, tests/out/spv/pointers.spvasm, tests/out/wgsl/pointers.wgsl, tests/snapshots.rs, tests/wgsl-errors.rs
Depends on #1381.
Treat expressions in `Function::named_expressions` like WGSL `let` declarations,
assuming that the Load Rule was applied to the rhs of the declaration, meaning
that their values are always `Indirection::Ordinary`.
Split `write_expr_plain_form` out from `write_expr_with_indirection`, to clean
up the parenthesis generation: no more `opened_paren` variable, just function
calls. This makes the early return for named expressions neater.
Fixes #1382.
=> [wgsl-out] Correct handling of named pointer expressions.

Cargo.toml, src/front/spv/mod.rs
Spir-v allows in the case list of an `OpSwitch` for target block ids to be reused, this caused issues because our frontend didn't check this and emitted them all in the same order they appeared.
With this PR now first they are collected to an `indexmap` (which would've already been introduced with jimb's changes) and then added to the body making sure that cases that share the same target block are contiguous.
Closes #1403
=> [spv-in] preserve case order when reusing blocks

src/front/glsl/context.rs, src/front/glsl/functions.rs, tests/in/glsl/expressions.frag, tests/out/wgsl/expressions-frag.wgsl
Automatically spills to a local variable function call arguments to
parameters expecting a pointer where the argument storage class isn't
function since the storage classes wouldn't match.
Closes #1341
=> [glsl-in] Use intermediate local if storage class isn't function

tests/snapshots.rs
This implements @kvark's suggestion in his review of #1384.
=> When writing snapshots, reliably identify which writer has failed.

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/wgsl/writer.rs, src/proc/namer.rs, tests/out/hlsl/access.hlsl, tests/out/hlsl/image.hlsl, tests/out/hlsl/interface.hlsl, tests/out/hlsl/interpolate.hlsl, tests/out/hlsl/skybox.hlsl, tests/out/msl/access.msl, tests/out/msl/image.msl, tests/out/wgsl/access.wgsl, tests/out/wgsl/image.wgsl
Replace uses of `call_unique` with uses of `call` and `call_or`, which becomes public. It's not clear when `call_unique` is correct to use, and avoiding a few numeric suffixes here and there isn't worth it.
=> Remove Namer::call_unique.

src/valid/type.rs, tests/wgsl-errors.rs
WGSL says:
> - The last member of the structure type defining the store type for a variable ... may be a runtime-sized array.
>
> - A runtime-sized array must not be used as the store type or contained within a store type in any other cases.
Thus, a struct whose final member is a struct whose final member is a runtime-sized array is verboten.
=> Forbid unsized structs as final members of structs.

src/valid/expression.rs, tests/wgsl-errors.rs
Require the `accept` and `reject` arguments to `select` to be scalars or vectors, per WGSL spec.
=> Properly type-check `Expression::Select` arguments.

src/front/glsl/builtins.rs, tests/out/wgsl/samplers-frag.wgsl
The array index for 1D images was being parsed as the first element of the coordinate vector which is the coordinate itself.
The fix is just changing a number and we already had tests for this so I don't know how it managed to stay broken for so long
=> [glsl-in] Fix array index parsing for 1D images

src/back/glsl/features.rs, src/back/glsl/mod.rs, tests/in/image.param.ron, tests/in/image.wgsl, tests/out/glsl/image.main.Compute.glsl, tests/out/glsl/image.queries.Vertex.glsl, tests/out/glsl/image.sample.Fragment.glsl, tests/out/glsl/image.sample_comparison.Fragment.glsl, tests/out/hlsl/image.hlsl, tests/out/hlsl/image.hlsl.config, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/wgsl/image.wgsl, tests/snapshots.rs
glsl es doesn't support 1d samplers so they must be converted to 2d samplers and the respective operations on them patched.
=> [glsl-out] Es: convert 1D images to 2D

.github/workflows/lazy.yml, Cargo.toml, cli/Cargo.toml, src/valid/analyzer.rs, src/valid/compose.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/interface.rs, src/valid/mod.rs
This PR will disable shader validation as much as possible by default. Currently in draft status, because I think that implementation is not good enough.
Fix #1213
=> Compile the validation out of an executable

src/back/msl/mod.rs
This has no effect, but makes the code more legible.
=> [msl-out] Put serde(default) on the whole struct, not on each field.

src/front/spv/function.rs, src/front/spv/mod.rs, tests/out/glsl/quad-vert.main.Vertex.glsl, tests/out/hlsl/quad-vert.hlsl, tests/out/msl/quad-vert.msl, tests/out/wgsl/quad-vert.wgsl
Some compilers like shaderc introduce a full gl_PerVertex struct, this
includes gl_ClipDistance. Normally this isn't a problem since most
drivers optimize it away, but naga zero inits globals if they weren't
previously initialized. This causes gl_ClipDistance to be initialized to
zero which can be really bad for performance.
It only culls builtins inside structs since the problems only have been observed inside them and adding it to all expressions could be costly (would need a benchmark to be certain).
This is only observed in spirv backend since it's the only backend to zero initialize stuff.
=> [spv-in]: Cull unused builtins inside structs

src/back/hlsl/storage.rs, tests/in/access.wgsl, tests/out/glsl/access.foo.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
Fixes #1504
The code had to go through a bit of a refactor. The end result is very type-verbose, but I think it should also be cleaner to read.
=> hlsl: respect array stride in storage buffers

src/back/spv/writer.rs
Per the SPIR-V spec:
> For a numeric literal, the lower-order words appear first.
=> [spv-out] Fix word order for constants

src/front/spv/image.rs, src/front/spv/mod.rs
Previously some image related functions like `parse_image_write` were still using `lookup_expression` directly instead of `get_expr_handle`.
This PR replaces them all and refactors the code to use the `BlockContext` directly instead of it's fields for some functions like `get_image_expr_ty`.
Closes #1506
=> [spv-in] Always use `get_expr_handle` for expressions in image expressions

src/front/glsl/functions.rs, tests/in/glsl/long-form-matrix.vert, tests/out/wgsl/210-bevy-shader-vert.wgsl, tests/out/wgsl/bevy-pbr-vert.wgsl, tests/out/wgsl/long-form-matrix-vert.wgsl
> If a matrix is constructed from a matrix, then each component
(column i, row j) in the result that has a corresponding component
(column i, row j) in the argument will be initialized from there. All
other components will be initialized to the identity matrix.
This was previously not implemented causing a matrix to be composed from a matrix which wouldn't pass validation.
Closes #1497
=> [glsl-in] Implement matrix to matrix constructor

src/front/glsl/functions.rs, tests/in/glsl/expressions.frag, tests/out/wgsl/expressions-frag.wgsl
Glsl defines in section 5.4.1:
> Scalar constructors with non-scalar parameters can be used to take the first element from a non-scalar. For example, the constructor float(vec3) will select the first component of the vec3
From my testing this only applies if the non-scalar argument is either a matrix or a vector.
Closes #1493
=> [glsl-in] Allow constructors from non-scalar to scalar

src/front/glsl/context.rs
Glsl allows indexing all vectors and matrices, this didn't work in naga in some situations specifically when the access base was binary/unary operation or a constant because those weren't allowed in that position.
Closes #1495
=> [glsl-in] Allow more operations as access bases

src/back/spv/block.rs, tests/in/operators.wgsl, tests/out/glsl/operators.main.Compute.glsl, tests/out/hlsl/operators.hlsl, tests/out/msl/operators.msl, tests/out/spv/operators.spvasm, tests/out/wgsl/operators.wgsl
Converting some GLSL to WGSL, I ran into a panic in the SpirV backend: `not implemented: Mul (Scalar, Matrix)`. The fix is super simple. Tests are included.
Interesting, the HLSL backend already does this same transformation. Cool!
=> [spv-out] Fix scalar-times-matrix operations

src/valid/function.rs, tests/in/control-flow.wgsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/hlsl/control-flow.hlsl, tests/out/msl/control-flow.msl, tests/out/wgsl/control-flow.wgsl, tests/wgsl-errors.rs
From the WGSL spec: "Each switch statement must have exactly one default clause."
Noticed this because [this switch](https://github.com/hecrj/wgpu_glyph/blob/cd6f154db0e7dd8231fdd34fcac470f975c825d7/src/shader/glyph.wgsl#L35-L52) doesn't get rejected by naga but Chrome/Tint reports:
```
Tint WGSL reader failure:
Parser: 35:5 error: switch statement must have a default clause
switch (i32(input.vertex_index)) {
^^^^^^
```
=> [valid] Check that switches have a default case

src/back/spv/index.rs, src/proc/index.rs, src/valid/type.rs
Only the SPIR-V front end can produce such array types, and it seems that our back ends don't support this case well.
=> Forbid specializable constants as array lengths.

src/proc/mod.rs, src/valid/function.rs, tests/in/bounds-check-zero.wgsl, tests/out/spv/bounds-check-zero.spvasm, tests/wgsl-errors.rs
=> Check that stores are permitted by the pointer's storage access.

src/back/wgsl/writer.rs, src/front/wgsl/conv.rs
This builtin isn't part of the specification, but is a simple addition to add multi-view support for WGSL. Is there an extension mechanism we can make use of here? I'm too unfamiliar with WGSL what the best approach here is to take.
Related to: https://github.com/gfx-rs/wgpu/issues/2186
=> Add view_index wgsl builtin

src/back/spv/index.rs, src/front/wgsl/mod.rs, src/valid/function.rs, src/valid/type.rs, tests/in/pointers.wgsl, tests/out/spv/pointers.spvasm, tests/out/wgsl/pointers.wgsl, tests/wgsl-errors.rs
Pointers should not be `DATA`: they can never be stored in anything. (Function arguments are not storage; they're like `let` bindings.)
Un-`SIZED` values may only live in the `Storage` storage class, so creating pointers to them in other storage classes is meaningless.
The `ARGUMENT` flag should be set only on pointers in those storage classes that are permitted to be passed to functions.
See comments in code for details.
Fixes #1513.
[spv-out] Don't support arguments pointing to unsized types.
Functions with such arguments could never have been called anyway, and now they are forbidden in validation.
=> Tighten checks on pointers to unsized values, and pointer arguments

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, tests/in/globals.wgsl, tests/in/interpolate.wgsl, tests/in/quad.wgsl, tests/out/dot/quad.dot, tests/out/glsl/globals.main.Compute.glsl, tests/out/hlsl/globals.hlsl, tests/out/hlsl/interpolate.hlsl, tests/out/hlsl/interpolate.hlsl.config, tests/out/hlsl/quad.hlsl, tests/out/hlsl/quad.hlsl.config, tests/out/msl/globals.msl, tests/out/msl/interpolate.msl, tests/out/msl/quad.msl, tests/out/spv/globals.spvasm, tests/out/spv/interpolate.spvasm, tests/out/spv/quad.spvasm, tests/out/wgsl/globals.wgsl, tests/out/wgsl/interpolate.wgsl, tests/out/wgsl/quad.wgsl, tests/wgsl-errors.rs
=> [wgsl-in] Don't allow redefinition of module scope identifiers

src/back/glsl/mod.rs
GLSL backend wasn't properly reflecting textures used without samplers, it's required for https://github.com/kvark/vange-rs/issues/161 and others.
=> glsl: reflect textures without samplers

src/back/msl/keywords.rs, src/back/msl/writer.rs, src/proc/index.rs, tests/out/msl/bounds-check-zero.msl, tests/out/msl/policy-mix.msl
Fixes #1585.
Commits should be individually CI-clean.
=> [msl-out]: Properly write default values for non-scalar types.

src/front/glsl/functions.rs, tests/in/glsl/declarations.vert, tests/out/wgsl/declarations-vert.wgsl
The IR doesn't allow having structs has bindings for entry point
input/output, so the glsl frontend must flatten them.
Glsl defines that the locations are sequential from the block base location.
Closes #1278
=> glsl-in: Flatten entry point arguments

src/front/spv/mod.rs
We already have the infrastructure to handle sign agnostic ops, this PR only changes `OpIMul`, `OpIEqual` and `OpINotEqual` to take the correct branch.
Closes #620
Closes #1593
=> spv-in: Implement remaining sign agnostic ops

src/front/spv/mod.rs
Treat it as a noop since the IR has no concept of copying objects
Closes #1592
=> spv-in: Implement OpCopyObject

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs
Fixes #1545. Removes support for `elseif` keyword.
=> wgsl-in: correctly parse `else if`

src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/spv/image.rs, src/back/spv/instructions.rs, src/back/wgsl/writer.rs, src/front/glsl/builtins.rs, src/front/spv/image.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/typifier.rs, src/valid/analyzer.rs, src/valid/expression.rs, tests/in/image.param.ron, tests/in/image.wgsl, tests/out/glsl/image.gather.Fragment.glsl, tests/out/hlsl/image.hlsl, tests/out/hlsl/image.hlsl.config, tests/out/ir/shadow.ron, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/wgsl/image.wgsl
Closes #1570
See https://github.com/gpuweb/gpuweb/issues/2327
Doesn't implement parsing new SPV-in or GLSL-in instructions, but covers all backends and WGSL-in.
=> Gather operations

CHANGELOG.md, Cargo.toml, tests/in/globals.wgsl
Blocked on #1596 and #1611
Optionally, also on #1580 and #1473
=> Release v0.8

src/span.rs
I wanted to create a `CreateShaderModuleError` from a `&WithSpan<ValidationError>` to reuse `wgpu`'s shader error formatting, but that isn't possible right now because `WithSpan` can't be cloned and you can't get an `&E` from `&WithSpan<E>`.
Solution: `#[derive(Clone)]`
=> impl Clone for `WithSpan<E>`

.gitignore, src/back/glsl/mod.rs, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo.Vertex.glsl, tests/out/glsl/boids.main.Compute.glsl, tests/out/glsl/cubeArrayShadow.fragment.Fragment.glsl, tests/out/glsl/image.gather.Fragment.glsl, tests/out/glsl/image.main.Compute.glsl, tests/out/glsl/image.queries.Vertex.glsl, tests/out/glsl/image.sample.Fragment.glsl, tests/out/glsl/image.sample_comparison.Fragment.glsl, tests/out/glsl/quad.frag_main.Fragment.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl, tests/out/glsl/skybox.fs_main.Fragment.glsl, tests/out/glsl/skybox.vs_main.Vertex.glsl, tests/out/glsl/texture-arg.main.Fragment.glsl
=> [glsl-out] Add stage postfix to generated global name

src/back/hlsl/writer.rs, tests/in/access.wgsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
=> hlsl: support arrays of matrices

Cargo.toml
This reduces the size of a release naga binary on macOS
from 3.5MB to 3.2MB. It's also the configuration we use
for naga in Firefox.
=> Turn on panic = "abort" by default

src/front/glsl/functions.rs, tests/in/glsl/swizzle_write.frag, tests/out/wgsl/swizzle_write-frag.wgsl
This worked at one point but because of some changes to the IR it was
temporarily broken.
Closes #1621
=> glsl-in: Fix using swizzle as out arguments

src/back/msl/writer.rs, tests/in/globals.wgsl, tests/out/glsl/globals.main.Compute.glsl, tests/out/hlsl/globals.hlsl, tests/out/msl/boids.msl, tests/out/msl/globals.msl, tests/out/msl/shadow.msl, tests/out/spv/globals.spvasm, tests/out/wgsl/globals.wgsl
Closes #1625
Note: it's still incomplete. Packed vectors are a pain, I filed #1633 to follow-up.
=> msl: fix packed vec access

src/front/glsl/context.rs, src/front/glsl/functions.rs, tests/in/glsl/declarations.vert, tests/out/wgsl/declarations-vert.wgsl
In the recent rework of the constructors it seems that the logic for
composite types (arrays and structs) was accidentally removed by me.
This PR reimplements it, adds implicit conversions that were missing on them and adds tests.
Closes #1623
=> glsl-in: fix composite constructors

src/back/msl/writer.rs, tests/out/msl/bits.msl
`snorm` and `unorm` got mixed up.
=> Fix data packing functions on MSL

src/back/glsl/mod.rs, tests/out/glsl/access.foo.Vertex.glsl, tests/out/glsl/bits.main.Compute.glsl, tests/out/glsl/boids.main.Compute.glsl, tests/out/glsl/interpolate.vert_main.Vertex.glsl, tests/out/glsl/operators.main.Compute.glsl, tests/out/glsl/quad-vert.main.Vertex.glsl
The zero initializing was inhibiting the output of initializers for structs and arrays, this PR reenables the output of initializers for them and for completeness also implements implements zero initialization for them. 
Fixes #1638
=> [glsl-out] Fix initializers not being written

src/front/wgsl/mod.rs
I am using `naga` in my build script to validate all of my shaders, and it would be nice to be able to display the file path inside of the diagnostic, so I added a method `emit_to_stderr_with_path` to `naga::front::wgsl::ParserError`.
=> Add a way to emit errors with a path

src/back/msl/writer.rs, tests/in/image.wgsl, tests/out/glsl/image.main.Compute.glsl, tests/out/glsl/image.queries.Vertex.glsl, tests/out/hlsl/image.hlsl, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/wgsl/image.wgsl
Fixes #1642.
Since 1d textures cannot have mipmaps, MSL requires that the `level` argument to
texel accesses and dimension queries be a constexpr 0. For our purposes, just
omit the level argument altogether.
=> [msl-out] Don't give level in texture1d accesses.

src/front/spv/convert.rs, src/front/spv/mod.rs
Only missing the shift operations but those require some special attention.
Closes #1645
=> spv-in: Implement more sign agnostic operations

Cargo.toml, src/back/spv/block.rs, tests/out/spv/operators.spvasm
=> spv-out: use OpFRem instead of OpFMod

.gitignore, src/front/wgsl/mod.rs, tests/wgsl-errors.rs
Fix #1655
```shell
error: the type of `x` is expected to be `i32`
┌─ wgsl:3:9
│
3 │     var x: u32 = 0;
│         ^ definition of `x`
```
=> [wgsl-in] Write a real type in type mismatch error

.gitignore, CHANGELOG.md, Cargo.toml, cli/Cargo.toml, src/back/msl/writer.rs, src/back/spv/block.rs, src/front/spv/convert.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/valid/interface.rs, tests/in/image.wgsl, tests/out/glsl/image.main.Compute.glsl, tests/out/glsl/image.queries.Vertex.glsl, tests/out/hlsl/image.hlsl, tests/out/msl/bits.msl, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/spv/operators.spvasm, tests/out/wgsl/image.wgsl, tests/wgsl-errors.rs
Includes #1637, #1639, #1647, #1650, #1651, #1653, #1658
=> Release 0.8.2

src/back/glsl/mod.rs
Previously the name of the sampler would be picked for the next argument, this is bad for two reasons:
- The debug data would be wrong
- If the argument was a pointer and written to, the expression would pick the right name but there wouldn't be a argument with that name
=> glsl-out: Write correct argument name when skipping samplers

src/back/glsl/features.rs, src/back/glsl/mod.rs, tests/in/functions-webgl.param.ron, tests/in/interpolate.param.ron, tests/in/push-constants.param.ron, tests/in/push-constants.wgsl, tests/in/quad.param.ron, tests/in/skybox.param.ron, tests/out/glsl/push-constants.main.Fragment.glsl, tests/snapshots.rs
This PR allows for the glsl backend to output push constants as uniform buffers to allow for push constant emulation.
It only allows for one push constant per entry point, which is fine in my opinion since even vulkan glsl only allows one `push_constant` decoration per shader.
It also changes the `ReflectionInfo` to return a name of the uniform buffer used for the emulation if it was used and `Options` to take the binding to use for the buffer if explicit bindings are supported.
This interface is deeply tied with the changes for push constant emulation on wgpu, so it might be useful to also see it https://github.com/JCapucho/wgpu/commit/ee3887ebb53e04471e221f21d1126aeb73630532
**Note**: I don't have much experience with openGL so the code might not be the best.
=> glsl-out: Add support for push constant emulation

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs
Fixes #1582
Implement block comments that support nesting.
=> [wgsl-in] implement block comments

src/back/glsl/mod.rs, tests/out/glsl/control-flow.main.Compute.glsl
This should fix https://github.com/gfx-rs/naga/issues/1677
OpenGL memory barriers and visibility are really confusing to me, but I spent some time researching to the best of my ability to make this correct: I started from https://www.khronos.org/opengl/wiki/Memory_Model#Ensuring_visibility and then read some extra questions/answers/blog posts around the net to confirm that I understood the khronos wiki correctly.
After the code change I did run `cargo test --all-features --workspace` and it reported no error, then I ran `make validate-glsl` and finally committed the new (modified) test output.
Edit: P.S: the `barrier()` GLSL function can only be called in a compute shader, but I am pretty sure this is fine because WGSL synchronization built-in functions can only be called in compute …
=> glsl-out: Call proper memory barrier functions

src/back/glsl/mod.rs, tests/in/functions-webgl.param.ron, tests/in/interpolate.param.ron, tests/in/push-constants.param.ron, tests/in/quad.param.ron, tests/in/skybox.param.ron, tests/out/glsl/push-constants.main.Fragment.glsl
Previously this was done with UBOs but this posed some problems when
integrating with wgpu (see https://github.com/gfx-rs/wgpu/pull/2400)
It basically reverses the previous PR retaining only the feature detection changes
=> glsl-out: push constants use anonymous uniforms

src/proc/layouter.rs, src/proc/mod.rs
Rename `TypeLayoutError` to `LayoutErrorInner`, for consistency. It makes no sense to have 'Type' in the name of one of the error types but not the other. The 'Inner' convention is used by the module types.
Cite the layout rules in the WGSL spec, not a GitHub issue.
(I just wrote this while reviewing another PR.)
=> Document `proc::layouter`.

CHANGELOG.md, src/back/wgsl/writer.rs, src/front/glsl/mod.rs, src/front/glsl/types.rs, src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, src/proc/layouter.rs, src/valid/type.rs, tests/in/access.wgsl, tests/in/boids.wgsl, tests/in/collatz.wgsl, tests/in/shadow.wgsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/246-collatz-comp.wgsl, tests/out/wgsl/access.wgsl, tests/out/wgsl/bevy-pbr-frag.wgsl, tests/out/wgsl/boids.wgsl, tests/out/wgsl/collatz.wgsl, tests/out/wgsl/constant-array-size-vert.wgsl, tests/out/wgsl/globals.wgsl, tests/out/wgsl/pointers.wgsl, tests/out/wgsl/shadow.wgsl, tests/wgsl-errors.rs
Matches https://github.com/gpuweb/gpuweb/pull
I first thought we'd remove the stride from the IR but then realized the IR is a bit more detailed than WGSL. In particular, it already has struct member offsets and struct sizes. So keeping `stride` in the IR is more consistent.
=> wgsl: remove stride

src/back/msl/writer.rs
=> msl: emit point size even when there is no struct

cli/src/main.rs
Fixes #1700 
Three changes are added to support reading from stdin:
- ~With `argh` crate, the `INPUT` argument cannot be optional. So this PR replaces `argh` with `clap` crate.~
- The `INPUT` argument is now optional: `naga [OPTIONS] [FILES...]`
- Since a file path cannot be known when reading from stdin, so a new option `--stdin-file-path <PATH>` is added to notify the file path. This is the same way as `eslint` does.
=> naga-cli: Support reading input from stdin

cli/src/main.rs
This PR adds `--version` flag to show its version so that users can easily check that the version of `naga` command matches to the version of `wgpu` crate which their projects are depending on.
=> cli: Add --version flag

cli/src/main.rs
Adding the file path to WGSL parse error output from `naga` would be better since a tool which uses the output can easily parse the file path from it
Before:
```
error: expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file, found '['
┌─ wgsl:5:1
│
5 │ [[group(1), binding(0)]]
│ ^ expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file
Could not parse WGSL
```
After:
```
error: expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file, found '['
┌─ /path/to/test.wgsl:5:1
│
5 │ [[group(1), binding(0)]]
│ ^ expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file
Could not parse WGSL
```
=> cli: Include file path in WGSL parse error

src/front/wgsl/mod.rs
Recently I'm trying to integrate `naga` command to my text editor to check WGSL sources on the fly.
However, a WGSL parse error output is hard to parse because it contains many color escape sequences. By this PR, error outputs are colorful only when stderr is connected to terminal. By this patch, tools like text editors can get error outputs without color escape sequences and easily parse the outputs.
=> wgsl: Do not make error output colorful when the terminal is dumb

src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/helpers.rs, src/valid/interface.rs, tests/in/globals.wgsl, tests/out/glsl/globals.main.Compute.glsl, tests/out/hlsl/globals.hlsl, tests/out/msl/globals.msl, tests/out/spv/globals.spvasm, tests/out/wgsl/globals.wgsl
Matches https://github.com/gpuweb/gpuweb/pull/2401
=> Allow non-structure buffer types

src/arena.rs, src/valid/compose.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/interface.rs, src/valid/mod.rs
It's a bit annoying to see this kind of an error:
```
error: 
┌─ uniform.wgsl:2:4
│
2 │ var buffer: array<vec4<f32>, 4>;
│    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::GlobalVariable [1]
Global variable [1] 'buffer' is invalid: 
Type isn't compatible with with the storage class
```
It's unclear what storage class is meant, and what the problem is. This PR changes this into:
```
error: 
┌─ uniform.wgsl:2:4
│
2 │ var buffer: array<vec4<f32>, 4>;
│    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::GlobalVariable [1]
Global variable [1] 'buffer' is invalid: 
Type isn't compatible with with address space Handle
```
Which is a bit better...
@jimblandy I feel that defaulting to `Handle` class is not doing WGSL any good, and it should be explicit instead.
=> Improve error messages about address space

src/front/glsl/parser/functions.rs
Under certatin circumstances the parser would panic because of culling
using an index out of bound, for example take the following code:
```glsl
{
x = 1; // Index 0 on nested block
discard; // Index 1 on nested block
} // Index 0 on block
```
The parser seeing this would attempt to cull the block using the start
index of 1 which would be out of bound and panic. Now instead the nested
block properly does it's internal culling and the outer block culls
everything after the nested block only.
=> glsl-in: Fix panic when culling nested block

src/front/glsl/ast.rs, src/front/glsl/parser.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/parser/functions.rs, src/front/glsl/parser/types.rs, src/front/glsl/variables.rs, tests/out/wgsl/expressions-frag.wgsl, tests/out/wgsl/fma-frag.wgsl
The previous implementation had many issues, most importantly it didn't
allow to implement (at least in a sane way) some future features like
default qualifiers and format qualifiers.
This implementations centralizes the qualifiers into a struct with a
hashmap for layout qualifiers, error reporting is also centralized which
means that `add_global_var` and `add_local_var` no longer need to
duplicate effort and the ugly loop + match combo is gone.
Finally some minor fixes are also done as part of this rework, like
a default location being provided for input/outputs variables, layout
qualifiers being allowed to be repeated (overwriting the previous one)
like the spec defines, more syntax validation is added to qualifiers and
more errors are made to not stop parsing when encountered.
=> glsl-in: Type qualifiers rework

src/back/glsl/mod.rs, src/back/hlsl/help.rs, src/back/msl/writer.rs, src/back/spv/index.rs, src/back/spv/mod.rs, src/lib.rs, tests/in/globals.wgsl, tests/out/glsl/globals.main.Compute.glsl, tests/out/hlsl/globals.hlsl, tests/out/msl/collatz.msl, tests/out/msl/globals.msl, tests/out/msl/shadow.msl, tests/out/spv/globals.spvasm, tests/out/wgsl/globals.wgsl
=> [msl-out][spv-out][glsl-out] Implement `ArraySize` on globals.

src/front/spv/mod.rs
=> spv-in: align array stride for undecorated arrays

src/back/wgsl/writer.rs, src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, tests/in/boids.wgsl, tests/in/collatz.wgsl, tests/in/control-flow.wgsl, tests/in/extra.wgsl, tests/in/operators.wgsl, tests/in/quad.wgsl, tests/in/shadow.wgsl, tests/out/wgsl/246-collatz-comp.wgsl, tests/out/wgsl/932-for-loop-if-vert.wgsl, tests/out/wgsl/bevy-pbr-frag.wgsl, tests/out/wgsl/boids.wgsl, tests/out/wgsl/collatz.wgsl, tests/out/wgsl/constant-array-size-vert.wgsl, tests/out/wgsl/control-flow.wgsl, tests/out/wgsl/extra.wgsl, tests/out/wgsl/operators.wgsl, tests/out/wgsl/quad.wgsl, tests/out/wgsl/shadow.wgsl
=> [wgsl] Optional parentheses for `if` and `switch`

src/back/msl/writer.rs, src/back/spv/image.rs, src/valid/analyzer.rs
These are a few things I came across during development. No code changes.
=> Various doc fixes

src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/spv/image.rs, src/back/wgsl/writer.rs, src/front/glsl/builtins.rs, src/front/spv/image.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/mod.rs, src/valid/analyzer.rs, src/valid/expression.rs
I'm curious whether folks see this as an improvement. It means more detailed matches in some places, but it also means we don't have to reach into the types to figure out what that `index` means, and I think it's a cleaner IR.
(Consider the last commit only; GitHub won't let me exclude the other PR's commit from this one, but it depends on it.)
=> Introduce TexelSelector type

src/front/glsl/ast.rs, src/front/glsl/builtins.rs, src/front/glsl/functions.rs, tests/in/variations.glsl, tests/out/glsl/variations-glsl.main.Fragment.glsl, tests/snapshots.rs
Also adds a glsl to glsl test to make sure that no unneeded extensions are activated.
=> glsl-in: inject sampler2DMSArray builtins on use

src/back/msl/keywords.rs, src/back/msl/writer.rs, tests/out/msl/access.msl, tests/out/msl/bits.msl, tests/out/msl/boids.msl, tests/out/msl/bounds-check-restrict.msl, tests/out/msl/bounds-check-zero-atomic.msl, tests/out/msl/bounds-check-zero.msl, tests/out/msl/collatz.msl, tests/out/msl/control-flow.msl, tests/out/msl/empty-global-name.msl, tests/out/msl/empty.msl, tests/out/msl/extra.msl, tests/out/msl/functions.msl, tests/out/msl/globals.msl, tests/out/msl/image.msl, tests/out/msl/interface.msl, tests/out/msl/interpolate.msl, tests/out/msl/math-functions.msl, tests/out/msl/operators.msl, tests/out/msl/policy-mix.msl, tests/out/msl/quad-vert.msl, tests/out/msl/quad.msl, tests/out/msl/shadow.msl, tests/out/msl/skybox.msl, tests/out/msl/standard.msl, tests/out/msl/texture-arg.msl
This lets us remove some special cases where `uint` must be fully qualified, even though other similar types are not.
This will conflict with the texture access bounds check branch (#1730), but it affects every single file in `tests/out/msl`, so combining it with that would flood the patch with noise that has nothing to do with bounds checks. So we can land the two separately, and I'll take care of whatever merging needs to be done. Whichever order you prefer is fine, but it's a lot less work to land this one second.
=> [msl-out] Write 'using metal::uint' at the top, to work around bug.

src/back/glsl/mod.rs, src/back/spv/image.rs, tests/in/image.wgsl, tests/out/glsl/image.queries.Vertex.glsl, tests/out/glsl/image.sample.Fragment.glsl, tests/out/glsl/image.sample_comparison.Fragment.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl, tests/out/hlsl/image.hlsl, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/wgsl/image.wgsl
- samplerCubeShadow requires vec3 gradients
- Bias must be written after offset
- sampler1D hack on GLES requires vec2 gradients
- textureSize doesn't accept a lod argument for MS samplers
- sampler1DArray hack on GLES requires a y component on imageLoad
Also adds some tests in wgsl
=> glsl-out: texture function fixes

src/front/wgsl/lexer.rs
I had this minor fix as part of #1750, but since it's causing CI failures for everything, I'm going to land it separately.
=> [wgsl-in] Use unwrap_or to placate Clippy.

src/front/wgsl/lexer.rs
This makes it unnecessary to check that field in every other pattern in the match.
=> [wgsl-in] consume_number: Check uint_suffix flag at top of match.

src/front/glsl/error.rs, src/front/glsl/parser.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/parser/functions.rs, tests/in/glsl/expressions.frag, tests/out/wgsl/expressions-frag.wgsl
This required doing backtracking in order to select between a declaration statement and a expression statement.
This PR is divided into 2 parts, each with it's own commit that can be reviewed and tested individually:
- Implementing backtracking
- Fixing the constructor freestanding parsing  
Closes #1554
=> glsl-in: Fix freestanding constructor parsing

src/front/glsl/functions.rs, tests/in/glsl/declarations.vert, tests/out/wgsl/declarations-vert.wgsl
Like it was already done for structs, arrays are flattened and each
element is attributed a location that is it's index + the array base
location.
Closes #1233
=> glsl-in: Support arrays as input/output types

src/back/hlsl/writer.rs, src/back/msl/writer.rs, tests/out/hlsl/operators.hlsl, tests/out/msl/operators.msl
Fixes #1252
In HLSL and MSL, when outputting a not operator, look at the expression type to choose the correct operator.
Mostly took code from the GLSL backend and adapted it for the other backends.
=> Not operator depending on expression type

src/back/msl/writer.rs, tests/in/access.param.ron, tests/in/access.wgsl, tests/in/globals.wgsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo_frag.Fragment.glsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/glsl/globals.main.Compute.glsl, tests/out/hlsl/access.hlsl, tests/out/hlsl/access.hlsl.config, tests/out/hlsl/globals.hlsl, tests/out/msl/access.msl, tests/out/msl/boids.msl, tests/out/msl/bounds-check-restrict.msl, tests/out/msl/bounds-check-zero.msl, tests/out/msl/globals.msl, tests/out/msl/policy-mix.msl, tests/out/msl/shadow.msl, tests/out/spv/access.spvasm, tests/out/spv/globals.spvasm, tests/out/wgsl/access.wgsl, tests/out/wgsl/globals.wgsl
=> msl: qualify read-only storage with const

src/back/spv/writer.rs
Matrices should have a `MatrixStride` of 8 for `matCx2` however the current implementation outputs a `MatrixStride` of 8 for `mat2xR`.
=> [spv-out] fix wrong MatrixStride for matCx2 and mat2xR

src/back/hlsl/writer.rs
fixes #1783
With this fix WGSL's `align` & `size` attributes and also spir-v's `Offset` decoration are respected since the offset in the IR is affected by those.
=> [hlsl-out] Insert padding between struct members

src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, tests/in/collatz.wgsl, tests/out/hlsl/collatz.hlsl, tests/out/ir/collatz.ron, tests/out/msl/collatz.msl, tests/out/spv/collatz.spvasm, tests/out/wgsl/collatz.wgsl
closes #1721
Implemented while loop as per [spec](https://gpuweb.github.io/gpuweb/wgsl/#while-statement).
=> [wgsl-in] Implement while loop

src/front/glsl/ast.rs, src/front/glsl/lex.rs, src/front/glsl/parser/types.rs, src/front/glsl/token.rs, src/front/glsl/variables.rs, tests/in/glsl/images.frag, tests/out/wgsl/images-frag.wgsl
Adds some documentation to better explain how the memory qualifier works
troughout the parser and some storage textures tests.
Closes #1770
=> glsl-in: Fix memory qualifiers being inverted

src/front/glsl/parser/declarations.rs, src/front/glsl/parser/functions.rs, src/front/glsl/parser/types.rs, src/front/glsl/types.rs, tests/in/glsl/declarations.vert, tests/out/wgsl/declarations-vert.wgsl
=> glsl-in: Allow multiple array specifiers

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/in/operators.wgsl, tests/in/shadow.wgsl, tests/out/glsl/operators.main.Compute.glsl, tests/out/hlsl/operators.hlsl, tests/out/msl/operators.msl, tests/out/spv/operators.spvasm, tests/out/wgsl/operators.wgsl
Implements increment (++) and decrement (--) statements as per [spec](https://gpuweb.github.io/gpuweb/wgsl/#increment-decrement).
=> [wgsl-in] Implement increment and decrement statements

src/front/glsl/builtins.rs, tests/in/glsl/images.frag, tests/out/wgsl/images-frag.wgsl
This wasn't done before which caused the frontend to crash if anything
appeared after it.
=> glsl-in: Resume expression emit after imageStore

src/front/glsl/builtins.rs
This attempts to implement the GLSL `barrier` function based some of the surrounding builtin implementations. However, it panics later when emitting expressions, so it evidentially isn't correct yet. 
Fixes #1771
=> Add glsl barrier function

src/front/glsl/context.rs, src/front/glsl/functions.rs, tests/in/glsl/expressions.frag, tests/out/wgsl/expressions-frag.wgsl
The spec defines that for vector and matrix constructors all arguments
should use the same conversions as scalar constructors (forced conversions)
Fixes #1792
=> glsl-in: use forced conversions for vector/matrix constructors

src/front/glsl/ast.rs, src/front/glsl/context.rs, src/front/glsl/variables.rs, tests/in/glsl/buffer.frag, tests/out/wgsl/bevy-pbr-frag.wgsl, tests/out/wgsl/buffer-frag.wgsl, tests/out/wgsl/declarations-vert.wgsl, tests/out/wgsl/fma-frag.wgsl
Also fixes access to runtime sized arrays behind named blocks
=> glsl-in: Allow nested accesses in lhs positions

src/back/hlsl/mod.rs, src/back/hlsl/storage.rs, src/back/hlsl/writer.rs, tests/in/access.wgsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo_frag.Fragment.glsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
HLSL uses inverted col/row notation (relative to GLSL, WGSL, MSL).
i.e. `mat3x2` in WGSL = `float2x3` in HLSL
Reference: [HLSL Matrix Doc](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-matrix)
related to original change in #1199
=> [hlsl-out] fix matrix not being declared as transposed

src/back/hlsl/conv.rs, src/back/hlsl/writer.rs, tests/out/hlsl/interface.hlsl, tests/out/hlsl/interpolate.hlsl, tests/out/hlsl/quad-vert.hlsl, tests/out/hlsl/quad.hlsl, tests/out/hlsl/shadow.hlsl, tests/out/hlsl/skybox.hlsl
Currently, hlsl-out writes the interpolation modifier before most structs, e.g.
```hlsl
struct input_0_ {
linear float4 SV_Position : LOC0;
};
```
However, [the linear intepolation modifier is the default](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-struct#interpolation-modifiers-introduced-in-shader-model-4) in HLSL.
This pull request makes hlsl-output not output `linear` to make outputted code look more human-like.
=> [hlsl-out] Don't output interpolation modifier if it's the default

src/front/glsl/error.rs, src/front/glsl/offset.rs
Our IR expects matrices of the form `matCx2` to have a stride of 8 however matrices in the std140 layout have a stride of at least 16.
=> [glsl-in] Error on a `matCx2` used with the std140 layout

src/front/spv/error.rs, src/front/spv/mod.rs
=> [spv-in] Error on unsupported `MatrixStride`

src/front/glsl/constants.rs
As the title says, added the implementation of `MathFunction::Clamp`. Feedback is very much appreciated! :)
=> [glsl-in] Implement `MathFunction::Clamp`

src/front/glsl/constants.rs
=> glsl-in: Add tests for constants NaN handling

src/back/glsl/mod.rs, src/back/hlsl/conv.rs, src/back/hlsl/help.rs, src/back/hlsl/storage.rs, src/back/hlsl/writer.rs, tests/in/access.wgsl, tests/in/padding.param.ron, tests/in/padding.wgsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo_frag.Fragment.glsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/glsl/padding.vertex.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/hlsl/operators.hlsl, tests/out/hlsl/padding.hlsl, tests/out/hlsl/padding.hlsl.config, tests/out/hlsl/quad-vert.hlsl, tests/out/msl/access.msl, tests/out/msl/padding.msl, tests/out/spv/access.spvasm, tests/out/spv/padding.spvasm, tests/out/wgsl/access.wgsl, tests/out/wgsl/padding.wgsl, tests/snapshots.rs
fixes #1772
Add padding at the end of structs and after struct members of type matrix and array since apparently the size of HLSL's matrices, arrays and structs doesn't get rounded up to a multiple of their alignment implicitly.
see also https://github.com/gfx-rs/naga/issues/1772#issuecomment-1093995973
You can now see that the HLSL output of the newly added test has the expected offsets.
https://shader-playground.timjones.io/86acbc3f9bec2bad5d3668e5ac707eeb
=> [hlsl-out] Add more padding when necessary

src/back/msl/mod.rs, src/back/msl/writer.rs, tests/out/msl/interface.msl
Split into two commits for easier review, but it's pretty short either way.
=> [msl-out] Permit `invariant` qualifier on vertex shader outputs.

src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/hlsl/conv.rs, src/back/hlsl/writer.rs, src/back/mod.rs, src/back/msl/mod.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/spv/helpers.rs, src/back/spv/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/variables.rs, src/front/spv/convert.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/spv/null.rs, src/front/wgsl/conv.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/mod.rs, src/valid/analyzer.rs, src/valid/interface.rs, tests/out/ir/collatz.ron, tests/out/spv/interface.fragment.spvasm, tests/out/spv/interface.vertex.spvasm, tests/out/spv/interface.vertex_two_structs.spvasm
Use the type system to enforce the rule that the invariant attribute may only appear on `Position` builtins.
Draft because it's dependent on #1821, but also because I want to look it over with fresh eyes tomorrow.
=> Move `invariant` bit from `Binding::Builtin` to `Builtin::Position`.

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/proc/mod.rs, tests/in/globals.wgsl, tests/out/glsl/globals.main.Compute.glsl, tests/out/hlsl/globals.hlsl, tests/out/msl/globals.msl, tests/out/spv/globals.spvasm, tests/out/wgsl/globals.wgsl
=> [glsl-out] Emit globals of any type, as required by Naga IR.

src/back/spv/helpers.rs, src/back/spv/writer.rs, tests/in/globals.wgsl, tests/out/glsl/globals.main.Compute.glsl, tests/out/hlsl/globals.hlsl, tests/out/msl/globals.msl, tests/out/spv/globals.spvasm, tests/out/wgsl/globals.wgsl
Fixes #1810. Draft PR because it contains no tests. Contains no tests because #1811.
[spv-out] Decorate array and struct type layouts unconditionally.
Remove the `decorate_layout` variable, which is unconditionally set to `true` anyway.
=> [spv-out] Emit required decorations on wrapper struct types, too.

src/front/wgsl/mod.rs, src/span.rs
I integrated naga error messages into [wgsl-analyzer](https://github.com/wgsl-analyzer/wgsl-analyzer) and in doing so made a few improvements to the error types allowing me to extract information I need.
Namely:
- expose `message` and `labels` from `frong::wgsl::ParseError`
- add `as_inner(&self) -> &E` to `WithSpan` (`into_inner(self) -> E` already exists)
- add `+ ExactSizeIterator` to the label/span iterators. This is not required but nice to have when checking whether any spans exist at all with `iter.len() == 0`
=> add methods on the error types for reusability in wgsl-analyzer

.github/workflows/pipeline.yml, Cargo.toml, README.md, src/front/glsl/constants.rs
As mentioned on matrix, `wgpu`'s MSRV has been recently bumped up to 1.59 and I proposed to bump the MSRV of `naga` to 1.56.
Besides API changes, I think thees are the most relevant features for us since 1.43 (our current MSRV):
- [1.56](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html); rust 2021 (can upgrade in the future), `rust-version` in Cargo.toml, multiple bindings in match arms
- [1.55](https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html#faster-more-correct-float-parsing); faster, more correct float parsing
- [1.53](https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#or-patterns); ability to nest OR patterns in match arms
- [1.51](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp); Const Generics MVP
- …
=> Update MSRV to 1.56

src/back/hlsl/writer.rs, tests/out/hlsl/globals.hlsl
=> [hlsl-out] Emit `row_major` qualifier on matrix uniform globals.

.github/workflows/pipeline.yml, Cargo.toml
Depends on #1838 (will rebase once it lands)
Adds minimal-versions checking for dependencies to CI and fixes minimal versions of some of our dependencies.
Relevant links
- arbitrary: https://github.com/rust-fuzz/arbitrary/blob/master/CHANGELOG.md#102
- bitflags: https://github.com/gfx-rs/rspirv/issues/232 (https://github.com/bitflags/bitflags/releases/tag/1.0.4)
- serde: https://github.com/serde-rs/serde/releases/tag/v1.0.103
Tested locally via
`cargo msrv verify -- cargo minimal-versions test --all-features --workspace` ([cargo-msrv](https://github.com/foresterre/cargo-msrv), [cargo-minimal-versions](https://github.com/taiki-e/cargo-minimal-versions))
=> CI minimal-versions checking for dependencies 

Cargo.toml
https://github.com/bitflags/bitflags/releases/tag/1.0.5
This fixes CI since #1840 landed without being rebased after #1841 got merged.
=> Fix bitflags min version

Cargo.toml, src/front/wgsl/lexer.rs
In 743c8aa387cbfbd3c47e6097c8c2694b3f6ad0a0 I mistakenly used `unicode-id` instead of `unicode-xid`.
Unicode defines both `ID_{Start,Continue}` and `XID_{Start,Continue}` in [Table_Lexical_Classes_for_Identifiers](https://www.unicode.org/reports/tr31/tr31-35.html#Table_Lexical_Classes_for_Identifiers).
=> Replace `unicode-id` with `unicode-xid`

src/back/msl/writer.rs, src/proc/index.rs, tests/in/binding-arrays.param.ron, tests/out/msl/binding-arrays.msl, tests/out/spv/binding-arrays.spvasm, tests/snapshots.rs
Found an issue with binding indexing in the MSL backend when bounds checks were on.
This fixes the issue and adds a binding array bounds check policy that, for now, must be unchecked.
=> Binding arrays play nice with bounds checks

src/lib.rs
The docs for `AccessIndex` only note it can be used with arrays ("Array access with a known index.") and don't mention [it can be used with structs or other types](https://github.com/gfx-rs/naga/blob/1aa9154964238af8c692cf521ff90e1f2395e147/src/valid/expression.rs#L227).
This pull request documents the full list of types relative to those for `Expression::Access`, which already have a more extensive blurb written about them.
=> Clarify accepted types for `Expression::AccessIndex`

src/valid/interface.rs, src/valid/type.rs
TypeFlags::INTERFACE -> TypeFlags::IO_SHARED
(WGSL §4.4.4's "IO-shareable types")
TypeFLags::HOST_SHARED -> TypeFlags::HOST_SHAREABLE
(WGSL §4.4.5's "Host-shareable types")
=> Rename type flags to better align with the current WGSL spec.

src/valid/type.rs
A `ValuePointer` type should always be handled exactly like the equivalent `Pointer` to `Scalar` type. To this end:
- Adjust the handling of `TypeFlags::ARGUMENT`.
- Neither `Pointer` nor `ValuePointer` types are ever `DATA`.
=> Validate `ValuePointer` exactly like a `Pointer` to a `Scalar`.

src/arena.rs
This function is used from both `Arena` and `UniqueArena`. When its code moved from `Arena` to `Handle`, the error message was adapted incorrectly.
=> Correct error message for `Handle` index overflow.

cli/src/main.rs, src/arena.rs, src/back/mod.rs, src/back/msl/writer.rs, src/front/spv/mod.rs, src/front/spv/null.rs, src/valid/expression.rs
[What can I say, it screwed me up!](https://github.com/gfx-rs/naga/pull/1862#discussion_r857831242) It didn't register that `!` in Rust performs both boolean and bitwise [negation](https://doc.rust-lang.org/std/ops/trait.Not.html), unlike other languages where it's `!`/`not` vs `~`.
This PR changes all instances of `!0` to equivalent results (`<type>::MAX` or `-1`, depending on signedness) to improve readability and prevent such errors in the future.
=> Change `!0` to equivalent results for readability

src/proc/mod.rs, src/valid/interface.rs, src/valid/type.rs, tests/wgsl-errors.rs
However, `bool` is permitted for built-ins.
=> The `bool` type is neither a host-shareable nor an interface type.

Cargo.toml
The unicode-xid crate just had a release with Unicode 14 data, which the WGSL spec requires.
=> Use Unicode 14 for WGSL

src/back/hlsl/help.rs, tests/out/hlsl/access.hlsl, tests/out/hlsl/interface.hlsl, tests/out/hlsl/operators.hlsl, tests/out/hlsl/quad-vert.hlsl, tests/out/hlsl/quad.hlsl, tests/out/hlsl/skybox.hlsl
Work around for FXC `error X4555: cannot use casts on l-values`.
Both approaches of zero initializing the whole struct (this PR) and explicitly initializing the padding fields generate the same DXBC.
fixes #1886
=> [hlsl-out] Zero init struct constructor

src/back/glsl/features.rs, src/back/glsl/mod.rs
The fma wasn't being searched in case it wasn't supported which is the
opposite of what we want since if it's used we want to error if it isn't
supported.
It was also searching in all entry points instead of only in the current
one.
All samples queries need the ARB_shader_texture_image_samples extension
so we need to check if any samples queries are made and if so request
the extension.
=> glsl-out: Fix feature search in expressions

README.md
I think installing `naga-cli` is more convenient than using `cargo run`. How about showing it on README rather than `cargo run`?
=> Show naga-cli instead of cargo run on README

src/back/hlsl/help.rs, src/back/hlsl/storage.rs, tests/out/hlsl/globals.hlsl, tests/out/hlsl/shadow.hlsl
Use `WrappedConstructor`s for `struct`s that are loaded from `AddressSpace::Storage` since they might be padded.
fixes #1892
=> [hlsl-out] Use wrapped constructors when loading from storage address space

src/back/hlsl/storage.rs, tests/in/access.param.ron, tests/in/access.wgsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo_frag.Fragment.glsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
=> Fix generated hlsl for writes to scalar/vector storage buffer

src/back/msl/writer.rs, tests/in/access.wgsl, tests/out/glsl/access.assign_through_ptr.Compute.glsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo_frag.Fragment.glsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/hlsl/access.hlsl.config, tests/out/msl/access.msl, tests/out/msl/policy-mix.msl, tests/out/msl/quad-vert.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
Changes pointers to private or workgroup address spaces to always be read-write (according to the WGSL spec).
fixes #1262
The added test used to fail with
```
error: no matching function for call to 'assign_through_ptr_fn'
assign_through_ptr_fn(val);
^~~~~~~~~~~~~~~~~~~~~
note: candidate function not viable: 1st argument ('const threadgroup metal::uint' (aka 'const threadgroup unsigned int')) would lose const qualifier
void assign_through_ptr_fn(
^
1 error generated.
```
References
https://gpuweb.github.io/gpuweb/wgsl/#access-mode-defaults
https://gpuweb.github.io/gpuweb/wgsl/#address-space-table
=> [msl-out] Fix pointers to private or workgroup address spaces possibly being read only

src/back/hlsl/help.rs, tests/out/hlsl/access.hlsl, tests/out/hlsl/operators.hlsl, tests/out/hlsl/quad-vert.hlsl
According to https://github.com/microsoft/DirectXShaderCompiler/issues/1808 the syntax used for returning arrays (which was added in https://github.com/gfx-rs/naga/pull/1814) is specific to DXC. This PR changes it to use a typedef which is supported by both FXC and DXC.
fixes https://github.com/gfx-rs/naga/issues/1913
=> [hlsl-out] Fix array constructor return type (for FXC)

src/front/wgsl/construction.rs, src/front/wgsl/mod.rs, tests/wgsl-errors.rs
=> Add error for matrices without `f32` scalar type

src/back/hlsl/writer.rs
This PR fixes usage of the HLSL `countbits` and `reversebits` functions with signed integers, by adding the necessary `asuint` and `asint` conversions.
Fixes #1904
=> [hlsl-out] Fix countOneBits and reverseBits for signed integers

src/back/msl/writer.rs, src/back/wgsl/writer.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs
Naga's support for multiview shaders seems pretty good so I think we can enable this SPIR-V capability, especially because `SPV_KHR_multiview` is already in `SUPPORTED_EXTENSIONS`.
=> [spv-in] Add MultiView to SUPPORTED_CAPABILITIES

.github/workflows/validation-windows.yml, Makefile, README.md
Added HLSL validation via FXC to CI since `wgpu` currently uses FXC for the D3D backends.
There are 4 issues with our current tests/backend that have to be resolved for FXC validation to succeed.
- #1919
- #1920
- #1921
- #1922
=> Add HLSL validation via FXC to CI

src/front/wgsl/mod.rs, src/lib.rs, src/span.rs
The idea is to get an easily consumable location (line/column/etc.) in the shader source for errors, where "easily consumable" really just means what [the WebGPU spec](https://www.w3.org/TR/webgpu/#shader-module-compilation-information) expects for errors.
r? @jimblandy
=> Add a helper for getting the location of a span in some textual source

src/back/glsl/mod.rs
`rgba8ui` is for unsigned ints, the correct one is `rgba8`
=> glsl-out: Fix storage format for Rgba8Unorm

README.md
This updates it to state that only Vulkan semantics are supported.
=> Update README for glsl-in

cli/src/main.rs, src/back/glsl/features.rs, src/back/glsl/mod.rs, tests/in/bounds-check-image-restrict.param.ron, tests/in/bounds-check-image-restrict.wgsl, tests/in/bounds-check-image-rzsw.param.ron, tests/in/bounds-check-image-rzsw.wgsl, tests/out/glsl/bounds-check-image-restrict.fragment_shader.Fragment.glsl, tests/out/glsl/bounds-check-image-rzsw.fragment_shader.Fragment.glsl, tests/out/glsl/image.main.Compute.glsl, tests/out/msl/bounds-check-image-restrict.msl, tests/out/msl/bounds-check-image-rzsw.msl, tests/out/spv/bounds-check-image-restrict.spvasm, tests/out/spv/bounds-check-image-rzsw.spvasm, tests/snapshots.rs
Depends on #1887
Implements bounds checks for `ImageLoad` on sampled images, because the opengl behavior on invalid texel load and stores for storage images is `ReadZeroSkipWrite` (no bound checks needed).
Only works on core for now since es doesn't support samples/levels queries (kvark said in the matrix room that they should be passed in uniforms then)
Closes #1080
=> glsl-out: Implement bounds checks for `ImageLoad`

src/back/hlsl/writer.rs, tests/in/control-flow.wgsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/hlsl/control-flow.hlsl, tests/out/msl/control-flow.msl, tests/out/spv/control-flow.spvasm, tests/out/wgsl/control-flow.wgsl
Fixes FXC `error X3537: Fall-throughs in switch statements are not allowed` by emitting the statements of the following case blocks (the ones the fallthrough was supposed to reach).
=> [hlsl-out] Fix fallthrough in switch statements (for FXC)

tests/in/access.wgsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
Avoid FXC `error X3504: array index out of bounds` triggered by the `access.wgsl` example.
=> [hlsl-out] Avoid error X3504: array index out of bounds (for FXC)

src/front/glsl/context.rs
This wasn't being done when there were no implicit conversions, causing
the emitter to panic.
closes #1942
=> glsl-in: Stop emitter in conditional

src/front/glsl/context.rs, tests/in/glsl/expressions.frag, tests/out/wgsl/expressions-frag.wgsl
The previous check compared rows to rows and columns to columns but
multiplication of matrices only needs the columns of the left matrix to
be equal to the rows of the right matrix.
closes #1947
=> glsl-in: Fix matrix multiplication check

benches/criterion.rs
As of #1889, the GLSL back end takes an additional argument specifying the bounds checks policies to use.
=> Fix Criterion benchmark build.

src/valid/function.rs, src/valid/type.rs, tests/wgsl-errors.rs
All commits should be CI-clean.
- Don't allow pointers in return values.
- [wgsl-in]: Use a `matches!` expression for brevity.
- Don't permit `Expression::Select` to operate on pointers. At the moment, Naga
doesn't support anything like SPIR-V's 'variable pointers'.
- Naga `TypeInner::Pointer` types are not `TypeFlags::DATA`.
Change `Validator::validate_type` not to mark pointers with the
`TypeFlags::Data` flag. The `TypeFlags::DATA` flag is supposed to correspond to
WGSL's concept of a 'plain type': a scalar, atomic, or composite type, excluding
textures, samplers, and pointers.
With this change, there is no type where `TypeFlags::DATA` and
`TypeFlags::INTERFACE` differ, but I'm not removing anything in this PR, because
I think we'll want to re-introduce a different distinction between …
=> Don't treat pointers as data.

CHANGELOG.md
Updates the changelog for v0.9 (also minor releases of v0.8.x from the 0.8 branch) and should include all user facing changes.
@cwfitzgerald and I discussed a bit about an updated format and this is what we came up with (`wgpu` will also adopt this format).
=> Update changelog for v0.9

src/front/glsl/builtins.rs, src/front/glsl/functions.rs, tests/in/glsl/sampler-functions.frag, tests/out/wgsl/sampler-functions-frag.wgsl
The conversion from sampled images to depth changed the `argument` type
but didn't change the `parameter` type (`argument` without pointer
indirection) causing 2+ deep propagation of depth images with function
arguments to fail.
=> glsl-in: Fix parameter not changing to depth

src/front/glsl/builtins.rs, tests/in/glsl/math-functions.vert, tests/out/wgsl/math-functions-vert.wgsl
Glsl defines two overloads for smoothstep that accept `min` and `max` as
scalars and the value as a vector, naga's IR is stricter and only allows
operators with the same dimensions, so this inputs must be splatted.
closes #1971
=> glsl-in: Splat inputs for smoothstep if needed

src/front/glsl/parser/functions.rs, tests/in/glsl/statements.frag, tests/out/wgsl/statements-frag.wgsl
GLSL allows the last case of a switch statement to not have a `break`
statement causing it to be marked as fall-trough, naga's IR on the other
hand doesn't allow the last case to be fall-trough, this is fixed by
force marking it in the glsl frontend as not fall-trough.
GLSL also allows empty switch statements and without default cases,
naga's IR requires there be a default case, this is fixed by adding an
empty default case in the glsl frontend if no default case was present
in the switch statement.
Finally, the GLSL spec forbids switch statements with an empty last case, so we
check that now and throw an error if necessary.
closes #1959
=> glsl-in: switch statement fixes

src/back/glsl/mod.rs, tests/in/math-functions.wgsl, tests/out/glsl/math-functions.main.Vertex.glsl, tests/out/hlsl/math-functions.hlsl, tests/out/msl/math-functions.msl, tests/out/spv/math-functions.spvasm, tests/out/wgsl/math-functions.wgsl
Some functions like abs only accept signed integers while naga's IR
accepts both signed and unsigned integers, this wasn't accounted for in
the glsl backend causing it to produce code that wouldn't type check.
This commit addresses it by performing casts from uint to int of the
function argument and then back from int to uint for the function
return.
closes #1968
~~Edit: found some problems that need to be fixed first~~
Edit2: Good to go now
=> glsl-out: Perform casts in int only math functions

Cargo.toml, tests/out/ir/shadow.ron
Require at least version 0.7.1 of ron, this version changed how floating points are
serialized by forcing them to always have the decimal part, this makes it backwards
incompatible with our tests because we do a syntatic diff and not a semantic one.
=> Patch ron version

src/back/hlsl/conv.rs, src/back/hlsl/storage.rs, src/back/spv/writer.rs, src/front/glsl/offset.rs, src/front/glsl/parser/declarations.rs, src/front/mod.rs, src/front/spv/mod.rs, src/front/wgsl/construction.rs, src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, src/proc/layouter.rs, src/proc/mod.rs, src/valid/type.rs, tests/wgsl-errors.rs
From the WGSL spec:
> [Must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) be a power of 2, and [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) satisfy the required-alignment for the member type:
> 
> If align(n) is applied to a member of S with type T, and S is the [store type](https://gpuweb.github.io/gpuweb/wgsl/#store-type) or contained in the store type for a variable in address space C, then n [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) satisfy: n = k × [RequiredAlignOf](https://gpuweb.github.io/gpuweb/wgsl/#requiredalignof)(T,C) for some positive integer k.
> This number [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) be at least the [byte-size](https://gpuweb.github.io/gpuweb/wgsl/#byte-size) of the …
=> [wgsl-in] Implement complete validation for size and align attributes

src/back/msl/writer.rs, tests/in/access.wgsl, tests/out/glsl/access.assign_through_ptr.Compute.glsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo_frag.Fragment.glsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
=> [msl-out] Insert padding initialization for global constants

src/back/glsl/mod.rs, tests/out/glsl/boids.main.Compute.glsl, tests/out/glsl/shadow.fs_main.Fragment.glsl, tests/out/glsl/shadow.fs_main_without_storage.Fragment.glsl
The continuing block in glsl was being generated with the same indentation as the loop body
=> glsl-out: Fix indentation for continuing block

src/back/hlsl/writer.rs, tests/out/hlsl/boids.hlsl, tests/out/hlsl/shadow.hlsl
The continuing block in hlsl was being generated with the same indentation as the loop body
=> hlsl-out: Fix indentation for continuing block

src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/spv/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/parser/functions.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/lib.rs, src/valid/analyzer.rs, src/valid/function.rs, tests/in/break-if.wgsl, tests/out/glsl/break-if.main.Compute.glsl, tests/out/hlsl/break-if.hlsl, tests/out/hlsl/break-if.hlsl.config, tests/out/ir/collatz.ron, tests/out/ir/shadow.ron, tests/out/msl/break-if.msl, tests/out/spv/break-if.spvasm, tests/out/wgsl/break-if.wgsl, tests/snapshots.rs, tests/wgsl-errors.rs
Adds support for the `break if` statement that may appear in the `continuing` block of a loop.
Relevant part of the spec: https://gpuweb.github.io/gpuweb/wgsl/#break-if-statement
Implements parsing in the wgsl frontend, emission on all the backends and validation for it.
Uniformity analysis isn't implemented, following the same behavior as regular breaks (this will be fixed in the uniformity analysis v5 rewrite).
All commits can be reviewed individually and are fully tested
Closes #1831
=> Add support for break if

src/front/spv/mod.rs
Since spirv's SMod doesn't map to naga's IR modulo operator the
instruction is mapped into it's direct formula, this formula requires
some casts from int to float and back.
These casts were present but their `convert` field was left to `None`
which implied that they were bitcasts, causing some wildly incorrect
results.
This commit fixes it by setting the `convert` field to the same size as
the result type.
=> spv-in: Fix incorrect translation of SMod

src/back/hlsl/writer.rs
This is especially relevant for shaders generated by rust-gpu.
Before:
```hlsl
struct VertexOutput_single_view::vertex_skybox_mirrored {
float3 member_1 : LOC0;
float4 member : SV_Position;
};
```
After:
```hlsl
struct VertexOutput_single_viewvertex_skybox_mirrored {
float3 member_1 : LOC0;
float4 member : SV_Position;
};
```
=> [hlsl-out] Use the namer to sanitise entrypoint input/output struct names

src/back/hlsl/writer.rs
[`f16tof32`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/f16tof32) handles unpacking of the lower half of a `uint` to a 16-bit float, so we need to call that twice, with a bitshift the second time.
=> Handle Unpack2x16float in hlsl

Cargo.toml
Termcolor only needs to be pulled in to the dependencies when codespan-reporting is pulled in.
=> Make termcolor dependency optional

src/front/wgsl/mod.rs, src/span.rs
Mirrors those already found for parse errors. Also took the time to remove the `StringErrorBuffer` writer in favor of the existing `NoColor` writer and added the `emit_to_string_with_path` method to complete the set.
=> add `emit_to_{stderr,string}` helpers to validation error

src/front/glsl/ast.rs, src/front/glsl/context.rs, src/front/glsl/parser/expressions.rs, tests/in/glsl/expressions.frag, tests/out/wgsl/expressions-frag.wgsl
this fixes #2016
i see two reasons you may not want to merge this
1. this assumes that .length() is only valid on arrays and never has any other meaning
2. this assumes that .length() has the same semantics as `Expression::ArrayLength`, which it may not have
other than that there should be no problems, other than that this was done in a hasty way
=> [glsl-in] add support for .length()

src/front/glsl/builtins.rs, src/lib.rs
1.63 Introduced some new clippy lints, this PR fixes them and disables the `derive_partial_eq_without_eq` lint because the structures it flags don't need to implement `Eq` (they are for internal use only) and deriving it might affect compilation times.
=> Fix clippy lints for 1.63

Cargo.toml, src/arena.rs, src/lib.rs
=> Implement `Clone` for `Module`

Makefile, src/back/hlsl/mod.rs, src/back/hlsl/writer.rs, tests/in/push-constants.param.ron, tests/in/push-constants.wgsl, tests/out/glsl/push-constants.vert_main.Vertex.glsl, tests/out/hlsl/push-constants.hlsl, tests/out/hlsl/push-constants.hlsl.config, tests/snapshots.rs
Push constants need to be configured by the consumer which must pass the
bind target of the constant buffer used for the push constants.
Closes #1782
=> hlsl-out: Add support for push constants

src/back/spv/writer.rs, tests/out/spv/interface.vertex.spvasm, tests/out/spv/shadow.spvasm
=> spv-out: Don't decorate varyings with interpolation modes at pipeline start/end

src/back/spv/writer.rs, tests/out/spv/access.spvasm, tests/out/spv/boids.spvasm, tests/out/spv/collatz.spvasm, tests/out/spv/control-flow.spvasm, tests/out/spv/extra.spvasm, tests/out/spv/image.spvasm, tests/out/spv/interface.compute.spvasm, tests/out/spv/interface.fragment.spvasm, tests/out/spv/interface.vertex.spvasm, tests/out/spv/interface.vertex_two_structs.spvasm, tests/out/spv/multiview.spvasm, tests/out/spv/skybox.spvasm
Fixes #2032
Take what I write in this PR with a whole handful off salt, I'm new enough to naga and spirv that there's a decent chance I am jumping to conclusions.
See the investigation in #2032. My uneducated guess is that spirv wants the integer input builtins such as `primitive_index` to have the flat decoration. So I added that in fairly naive way.
This PR fixes the `primitive_index.wgsl` test case and doesn't appear to cause regressions as far as `cargo test --all` can tell.
=> spv-out: Decorate integer builtins as Flat in the spirv writer

src/back/spv/writer.rs
=> Use `Option::as_deref` as appropriate.

src/back/spv/writer.rs, tests/out/spv/access.spvasm, tests/out/spv/boids.spvasm, tests/out/spv/collatz.spvasm, tests/out/spv/control-flow.spvasm, tests/out/spv/image.spvasm, tests/out/spv/interface.compute.spvasm, tests/out/spv/interface.fragment.spvasm, tests/out/spv/interface.vertex.spvasm, tests/out/spv/interface.vertex_two_structs.spvasm, tests/out/spv/multiview.spvasm, tests/out/spv/skybox.spvasm
The Vulkan decoration rules require us to distinguish vertex shader
inputs, fragment shader inputs, and everything else, so just pass the
stage to `Writer::write_varying`. Together with the SPIRV storage
class, this is sufficient to distinguish all the cases in a way that
closely follows the spec language.
=> [spv-out] Properly combine the fixes for #2035 and #2038.

src/front/mod.rs, src/front/wgsl/mod.rs, tests/in/lexical-scopes.wgsl, tests/out/wgsl/lexical-scopes.wgsl, tests/snapshots.rs
Previously the wgsl frontend wasn't aware of lexical scopes causing all variables and named expressions to share a single function scope, this meant that if a variable was defined in a block with the same name as a variable in the function body, the variable in the function body would be lost and exiting the block all references to the variable in the function body would be replaced with the variable of the block.
This PR fixes that in two commits, the first commit introduces a new frontend agnostic type `SymbolTable` that will be responsible for managing lexical scopes and performing variable lookups, this type is only used in wgsl right now but I intend to change glsl's internal symbol table for it, the second commit wires it up to the wgsl frontend and inserts the proper push/pop of …
=> wgsl-in: Implement lexical scopes

src/back/spv/block.rs, tests/out/spv/image.spvasm, tests/out/spv/operators.spvasm
As reported in #2015, some drivers trip over these.
=> [spv-out] Don't emit no-op `OpBitCast` instructions.

src/front/wgsl/construction.rs, src/front/wgsl/mod.rs
Rename related functions and variables appropriately.
Also, make `Rule` private to the WGSL front end, and remove the unused `ImportDecl` variant.
=> wgsl-in: Rename `Scope` to `Rule`, since we now have lexical scope.

src/front/glsl/context.rs, src/front/glsl/parser/functions.rs, src/front/glsl/variables.rs, src/front/mod.rs
Moves the glsl frontend from it's custom solution for lexical scopes to the new `SymbolTable`.
Adds an `add_root` method to `SymbolTable` that's needed for glsl builtins and implement `Debug`.
=> glsl-in: Migrate to `SymbolTable`

src/valid/function.rs, src/valid/interface.rs, src/valid/mod.rs
Checks that all arguments and return types have no bindings in regular functions.
Closes #2037
=> valid: Check regular functions don't have bindings

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs
The wgsl frontend was emiting errors for lhs expressions on assignments that weren't references using a span that didn't skip blankspaces causing the span to look weird (like starting at the end of the previous line)
This is fixed by consuming the blankspace before constructing the span
Related to #2053
=> wgsl-in: Fix bad span in assignment lhs error

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/wgsl-errors.rs
This fixes #2053 for all cases, ensuring that no spans have leading or trailing trivia in them.
The lexer API is changed to have `.start_byte_offset()` and `.end_byte_offset()`, to be used when trying to get the byte offset of the start and end of a node, respectively.
=> wgsl-in: Fix inclusion of trivia in spans

src/front/wgsl/lexer.rs, src/front/wgsl/mod.rs, tests/wgsl-errors.rs
This improves the diagnostics on invalid assignment statements.
Fixes #2052.
Given:
```wgsl
fn f() {
var v = vec2(0);
v.xy = vec2(1);
}
```
Naga used to error with:
```
error: the left-hand side of an assignment must be a reference
┌─ test.wgsl:3:5
│
3 │     v.xy = vec2(1);
│     ^^^^ expression is not a reference
```
Now:
```
error: invalid left-hand side of assignment
┌─ test.wgsl:3:5
│
3 │     v.xy = vec2(1);
│     ^^^^ cannot assign to this expression
│
= note: WGSL does not support assignments to swizzles
= note: consider assigning each component individually
```
Given:
```wgsl
fn f() {
3 + 5;
}
```
Naga used to error with:
```
error: the left-hand side of an assignment must be a reference
┌─ test.wgsl:2:5
│
2 │     3 + 5;
│     ^ expression is not a reference
```
Now:
```
error: …
```
=> wgsl-in: Improve assignment diagnostics

src/front/wgsl/mod.rs
Whitespace and formatting changes only.
It turns out that if `cargo fmt` comes across a single line it can't make fit within the margins, then it sort of gives up on the surrounding construct. So breaking up the error message for `Error::UnknownScalarType` in `Error::as_parse_error` and then re-running `cargo fmt` cleans up lots of other stuff in the file.
cargo fmt issue:
https://github.com/rust-lang/rustfmt/issues/3863
=> [wgsl-in] Break up long string, reformat rest of file.

Cargo.toml
I noticed that depending on the environment the std check by the autocfg crate may fail. This enables std like recommended here: https://github.com/bluss/indexmap/issues/184
=> Explicitely enable std for indexmap

src/front/glsl/parser/declarations.rs
Previously when parsing an initializer list, the type passed to `parse_initializer` was not updated to reflect the child type, this caused implicit conversions to not work and nested initializer lists to not be allowed.
=> glsl-in: Update initializer list type when parsing

src/back/hlsl/writer.rs, tests/out/hlsl/access.hlsl
Fixes #2095 by using more conventional `.x` indexing instead of "unconventional" `[0]`.
=> Workaround FXC Bug in Matrix Indexing

src/back/hlsl/storage.rs, src/back/hlsl/writer.rs, tests/out/hlsl/bitcast.hlsl, tests/out/hlsl/bitcast.hlsl.config, tests/out/hlsl/operators.hlsl, tests/snapshots.rs
- Implements bitcast properly
- Fixes column vs row confusion when forming access chains into storage buffers.
Fixes #2093 
Fixes #2092 
Recommended review style is commit-by-commit.
=> [hlsl-out] Fix issues in wgpu Layout Tests

src/back/msl/writer.rs, tests/in/bounds-check-zero-atomic.wgsl, tests/out/msl/bounds-check-zero-atomic.msl
Generalize put_atomic_fetch to handle `exchange` as well, rather than special-cased code which didn't do the bounds check (the check handling as fixed in #1703 but only for the fetch cases, exchange was skipped).
Fixes #1848
=> Fix incorrect atomic bounds check on metal back-end

Cargo.toml, cli/Cargo.toml, src/arena.rs, src/front/wgsl/number.rs, src/proc/mod.rs
Since the MSRV of `naga` [is currently 1.56][msrv], I don't think there's a strong reason to stay with the 2018 edition, and there _are_ a [few good reasons][edition-guide] to move to the 2021 edition.
I did this migration mostly automatically, per [official Rust guidelines]:
```sh
$ cargo fix --edition --all-targets
$ sed -i Cargo.toml 's/2018/2021'
$ cargo fix --edition-idioms --allow-dirty # doesn't change anything
```
The only manual edit needed to stymie a new warning introduced was the removal of the `TryFrom` import from several modules, since it's now in the 2021 prelude.
[msrv]: https://github.com/gfx-rs/naga/blob/a7193d652e49180661a6ca047889e0685667acdb/.github/workflows/pipeline.yml#L14
[edition-guide]: https://doc.rust-lang.org/edition-guide/rust-2021/index.html
[official Rust …
=> build: move to the Rust 2021 edition

src/back/wgsl/writer.rs, src/valid/analyzer.rs, src/valid/function.rs, src/valid/mod.rs, tests/wgsl-errors.rs
This lets us omit a `#[source]` annotation in the case of named members. Most other popular crates with a `derive` interface (like [`snafu`](https://docs.rs/snafu/0.7.3/snafu/index.html), [`derive-more`](https://jeltef.github.io/derive_more/derive_more/error.html)) use this convention, so it's pretty portable, overall.
Also, minor "bonus" refactor re-rolling a `for` loop in the `wgsl` backend. 😅 Reviewing commit-by-commit makes this easy to see.
=> Use `source` member name for source errors

src/back/msl/writer.rs, tests/out/msl/image.msl
```
thread 'main' panicked at 'wgpu error: Validation Error
Caused by:
In Device::create_render_pipeline
Internal error in VERTEX shader: Metal: Compilation failed: 
program_source:90:65: error: use of undeclared identifier 'int2'; did you mean 'int'?
metal::float4 _e4 = image.gather(samp, tex_coord_1, int2(0), metal::component::y);
^
program_source:94:65: error: use of undeclared identifier 'int2'; did you mean 'int'?
metal::float4 _e5 = image.gather(samp, tex_coord_1, int2(0), metal::component::z);
^
program_source:98:65: error: use of undeclared identifier 'int2'; did you mean 'int'?
metal::float4 _e6 = image.gather(samp, tex_coord_1, int2(0), metal::component::w);
^
program_source:196:98: warning: suggest braces around initialization of subobject
fitting_lanczos_weight(weight_color_1, …
```
=> Fix textureGather compatibility on macOS 10.13

benches/criterion.rs, src/back/msl/writer.rs, src/front/glsl/constants.rs, src/lib.rs, tests/snapshots.rs
Just some quick `clippy` lint updates; I'm currently using Rust 1.64 for this PR. 😊 Recommended review experience: commit by commit. I've tried to note in specific commits where I felt some thought was required with the decision to silence or change code significantly.
Open questions:
https://github.com/gfx-rs/naga/blob/41ebe1320d246f7db8645a4c8baa4f7e42267529/.github/workflows/pipeline.yml#L56-L70
=> Satisfy latest `clippy` lints (up to Rust 1.64)

src/lib.rs
👋 Hey there,
Was trying to figure out how to explicitly enable early depth tests in WebGPU/WGSL shaders, and noticed there was documentation on the syntax for `EarlyDepthTest` and `ConservativeDepth` options for GLSL/HLSL/SPIR-V, but not for WGSL. 
Had to do some digging through the parser code to figure out how to do it, so this PR adds documentation, so that hopefully others can find it more easily in the future.
```wgsl
@fragment
@early_depth_test
fn fragment(in: FragmentInput) -> @location(0) vec4<f32> {
// ....
}
```
_OR_
```wgsl
@fragment
@early_depth_test(greater_equal/less_equal/unchanged) // pick one mode
fn fragment(in: FragmentInput) -> @location(0) vec4<f32> {
// ....
}
```
=> Document `EarlyDepthTest` and `ConservativeDepth` syntax in WGSL

src/front/glsl/context.rs, tests/in/glsl/expressions.frag, tests/out/wgsl/bevy-pbr-frag.wgsl, tests/out/wgsl/expressions-frag.wgsl, tests/out/wgsl/fma-frag.wgsl
When lowering `Select` expressions the position could be wrongfully updated from `AccessBase { constant_index: false }` to `AccessBase { constant_index: true }` this caused dynamic indexing in an array behind a structure to fail if it was stored in a constant.
Furthermore the position could also be updated from `Rhs` to `AccessBase`, this could cause issues because `AccessBase` doesn't load variables (which `Rhs` does), so accessing a member from a structure behind a pointer would return the wrong result.
=> glsl-in: Fix position propagation in lowering

src/valid/analyzer.rs, src/valid/expression.rs, tests/in/image.wgsl, tests/out/glsl/image.gather.Fragment.glsl, tests/out/glsl/image.queries.Vertex.glsl, tests/out/hlsl/image.hlsl, tests/out/msl/image.msl, tests/out/spv/image.spvasm, tests/out/wgsl/image.wgsl
Fixes https://github.com/gfx-rs/naga/issues/2135.
I'm not sure if I did this correctly, so please double check if this is right. It's enough to let my shader pass validation, however.
=> Fix textureGather on texture_2d<u32/i32>

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/wgsl/writer.rs, src/front/wgsl/mod.rs, src/front/wgsl/tests.rs, src/lib.rs, tests/in/control-flow.wgsl, tests/out/glsl/control-flow.main.Compute.glsl, tests/out/hlsl/control-flow.hlsl, tests/out/msl/control-flow.msl, tests/out/spv/control-flow.spvasm, tests/out/wgsl/control-flow.wgsl, tests/wgsl-errors.rs
=> Switch statement improvements

src/back/wgsl/writer.rs, tests/out/wgsl/extra.wgsl
Related to https://github.com/gfx-rs/naga/issues/1272#issuecomment-945044963
=> [wgsl-out] Write correct scalar kind when width != 4

tests/snapshots.rs
This is for the same reason that we ignore `dead_code`:
// A lot of the code can be unused based on configuration flags,
// the corresponding warnings aren't helpful.
=> Ignore `unused_imports` in tests/snapshots.rs.

src/arena.rs
when working with naga IR i've found i need to be able to construct `Range`s (specifically for `Statement::Emit` which can't be constructed otherwise). it is possible currently, but only via serde hacking.
i added a `Range::new_from_bounds` method to allow construction.
first PR, apologies if i missed any standard process.
=> add Range::new_from_bounds

src/front/wgsl/conv.rs, src/front/wgsl/mod.rs, tests/wgsl-errors.rs
Validation already fails on any non-32bit integers but this change makes it clearer what the frontend actually supports.
Also commented out `f16`, we can uncomment it once we implement the extension.
=> [wgsl-in] Remove non-32bit integers

src/lib.rs, src/valid/interface.rs, src/valid/mod.rs, tests/out/analysis/collatz.info.ron, tests/out/analysis/shadow.info.ron
Part of #2154
A few things to think about here:
1. Is the scope of the flag chosen soundly? I was considering `INTERFACE` first, but it could be considered too wide of a scope.
2. Can this be released as a patch? I.e. is adding a bitflag a breaking change?
=> Add ValidationFlags::BINDINGS

src/arena.rs, src/back/hlsl/conv.rs, src/back/hlsl/writer.rs, src/proc/layouter.rs, src/proc/mod.rs, src/proc/typifier.rs, src/valid/analyzer.rs, src/valid/compose.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/handles.rs, src/valid/interface.rs, src/valid/mod.rs, src/valid/type.rs
Resolves #1692. Recommended review experience is commit-by-commit.
=> Add handle validation pass to `Validator`

src/back/glsl/mod.rs, src/back/hlsl/conv.rs, src/back/msl/mod.rs, src/back/spv/writer.rs, src/front/glsl/variables.rs, src/front/spv/convert.rs, src/lib.rs, src/valid/interface.rs
Support `gl_PointCoord` in the glsl frontend.
=> Supporting gl_PointCoord

src/back/msl/mod.rs, src/back/msl/writer.rs
The purpose of this code is to detect if a global variable can or can't be used legally by a given entry point. It assumes the resource binding is present and just checks if the override is set. I find it also useful to check if there is a binding at all. Hence the new error type.
Note that, technically speaking, all backends assume the module is valid. And this validity includes having a binding decoration on all resource globals. And now this code makes MSL backend *also* work correctly for a subset of modules that are valid except for the bindings part. So it's a tricky case, and it's not directly hit by WebGPU paths.
=> msl: handle the case of missing binding

src/back/glsl/mod.rs
Every global variable with `AddressSpace::Uniform | AddressSpace::Storage` will be written using `write_interface_block`, so this just exposes the reflection information that was previously private.
=> [glsl-out] emit reflection info for non-struct uniforms

src/back/glsl/features.rs, src/back/glsl/mod.rs, tests/in/functions-webgl.param.ron, tests/out/glsl/functions-webgl.main.Vertex.glsl, tests/out/glsl/functions.main.Compute.glsl
The issue was that we were effectively requiring GLSL 310 + `GL_EXT_gpu_shader5` when we could have instead used the polyfill.
Was previously brought up in https://github.com/gfx-rs/naga/pull/1580#discussion_r772578184.
Closes #2196.
=> [glsl-out] use `fma` polyfill for versions below gles 320

src/valid/analyzer.rs, src/valid/function.rs
I think this is the only other case in `process_block` where a uniformity requirement can be created without being validated.
=> Error if the uniformity requirements for a barrier aren't met

src/valid/analyzer.rs, src/valid/function.rs
This reverts commit e6e94d65 (#2115). That PR extends Naga's old uniformity analysis, adding a check for barriers that matches the existing checks on derivative operations. However, this breaks existing clients ([`Vello`](https://github.com/linebender/vello), for example), and extending the old uniformity analysis is not a priority, so it makes sense to back it out.
=> Revert "Error if the uniformity requirements for a barrier aren't met"

.github/workflows/validation-windows.yml
I saw the "[validation-windows](https://github.com/gfx-rs/naga/actions/workflows/validation-windows.yml)" jobs were giving a warning due to [setup-dxc](https://github.com/Napokue/setup-dxc) not being updated to NodeJs16. Updated it and released it under v1.1.0.
This PR updates the action to use v1.1.0 instead of version v1.0.0.
=> Update setup-dxc to v1.1.0

src/valid/analyzer.rs, src/valid/expression.rs, src/valid/function.rs
Undo some changes from #1668, now that #2090 has been merged.
cc @ErichDonGubler
=> Let the uniformity analysis trust the handle validation pass.

src/valid/type.rs
Fixes #2211 by removing the stride check, as suggested in https://github.com/gfx-rs/naga/pull/2212#issuecomment-1386177626. The alignments when used in uniforms and storage buffers are both validated below in the same function.
=> Remove overly restrictive array stride check

src/back/glsl/mod.rs, src/front/glsl/parser_tests.rs, src/front/glsl/variables.rs, tests/out/wgsl/931-constant-emitting-vert.wgsl, tests/out/wgsl/bevy-pbr-frag.wgsl, tests/out/wgsl/constant-array-size-vert.wgsl, tests/out/wgsl/expressions-frag.wgsl, tests/out/wgsl/global-constant-array-vert.wgsl, tests/out/wgsl/quad_glsl-vert.wgsl
- added a `back::glsl::WriterFlags` flag `INCLUDE_UNUSED_ITEMS`.
when set, unused globals, functions using unused globals, and named constants are included in the output glsl.
- added a named copy of named constants in front::glsl into the module, to allow exporting them above. this adds a bit of unnecessary weight to the module, but hopefully it's not a problem?
motivation is for better glsl support in naga_oil, where i rely on modules to contain all members even if unused at point of construction.
=> glsl: include unused items

benches/criterion.rs, cli/src/bin/naga.rs, src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/hlsl/conv.rs, src/back/hlsl/help.rs, src/back/hlsl/storage.rs, src/back/hlsl/writer.rs, src/back/msl/mod.rs, src/back/msl/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/constants.rs, src/front/glsl/context.rs, src/front/glsl/error.rs, src/front/glsl/functions.rs, src/front/glsl/types.rs, src/front/glsl/variables.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/wgsl/mod.rs, src/front/wgsl/number.rs, src/lib.rs, src/proc/namer.rs, src/proc/typifier.rs, tests/snapshots.rs, tests/spirv-capabilities.rs, tests/wgsl-errors.rs
* Inline identifiers into format strings.
[Since Rust 1.58], Rust format strings have been able to "capture
arguments simply by writing {ident} in the string." Clippy 1.67 made
the corresponding warning, `uninlined_format_args`, warn-by-default.
Inlined arguments seem more readable, so Naga should adopt them.
[Since Rust 1.58]: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1580-2022-01-13
* Allow `clippy::needless_borrowed_reference`.
In Clippy 1.67, the `needless_borrowed_reference` lint [was enhanced]
to look into struct and tuple patterns, so that a line like this:
for &(ref module, ref info) in inputs.iter()
where `inputs.iter()` is yielding `&(Module, ModuleInfo)` pairs,
elicits a warning. Clippy suggests, instead:
for (module, info) in inputs.iter()
but this is …
=> Address Clippy 1.67 lints.

src/valid/handles.rs
This PR fixes an issue with the dependency code and adds dependency validation to function calls.
The handle validator had an issue that caused it to try to build a handle with a zero based index while type erasing handles, this would crash because the index must be a `NonZeroU32` and it would also not be correct since the handle would be off by one from the original handle.
It also fixes the error message for the forward dependency not containing the subject's kind.
Lastly it adds a dependency check for function calls, to prevent forward declarations to pass to further stages and cause crashes (mitigates #2225)
=> valid: Improve forward declaration validation

Cargo.toml, src/back/hlsl/writer.rs, src/front/glsl/functions.rs, src/front/spv/function.rs, src/front/wgsl/lower/mod.rs, src/lib.rs, tests/out/ir/access.ron
=> [hlsl-out] clear `named_expressions` inserted by duplicated blocks

src/back/glsl/mod.rs, src/back/hlsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/wgsl/writer.rs, src/front/wgsl/parse/conv.rs, src/lib.rs, src/proc/mod.rs, src/proc/typifier.rs, src/valid/expression.rs, tests/in/math-functions.wgsl, tests/out/glsl/math-functions.main.Vertex.glsl, tests/out/hlsl/math-functions.hlsl, tests/out/msl/math-functions.msl, tests/out/spv/math-functions.spvasm, tests/out/wgsl/math-functions.wgsl
Adds `countLeadingZeros` from https://github.com/gfx-rs/naga/issues/2134#issue-1463112793
For negative expressions return `0`, otherwise return `31 - msb`.
This assumes `findUMsb`, `findMSB`, and `firstbithigh` all return an index from the `lsb`,
but I don't have the means to verify this is actually the case atm.
=> Add countLeadingZeros

src/front/wgsl/error.rs, src/front/wgsl/lower/mod.rs, src/front/wgsl/parse/mod.rs, tests/wgsl-errors.rs
- fixes #2216 
- fixes #2209 
- fixes #2169 
Also checks for the `;` after `break`, `continue`, and `discard`, as per the spec.
The diagnostic for #2209 is a bit weird:
```
error: type `array<f32, 0f>` is not constructible
┌─ wgsl:2:6
│
2 │     -array<f32, 0f>() = v;
│      ^^^^^^^^^^^^^^ type is not constructible
```
But it does point the user to where the problem is and doesn't crash.
The invalid assignment diagnostic is also improved overall:
```
error: invalid left-hand side of assignment
┌─ wgsl:2:9
│
2 │     let a = array(1, 2);
│         ^ this is an immutable binding
3 │     a[0] = 2;
│     ^^^^ cannot assign to this expression
│
= note: consider declaring 'a' with `var` instead of `let`
```
=> Correctness and diagnostic fixes

src/back/glsl/mod.rs, tests/in/force_point_size_vertex_shader_webgl.param.ron, tests/in/force_point_size_vertex_shader_webgl.wgsl, tests/out/glsl/force_point_size_vertex_shader_webgl.fs_main.Fragment.glsl, tests/out/glsl/force_point_size_vertex_shader_webgl.vs_main.Vertex.glsl, tests/snapshots.rs
According to https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html#built-in-language-variables
> The variable gl_PointSize is intended for a shader to write the size of the point to be rasterized. It is measured in pixels. If gl_PointSize is not written to, its value is undefined in subsequent pipe stages.
This is the first part of the changes to address https://github.com/gfx-rs/wgpu/issues/3179
=> [glsl] Inject default `gl_PointSize = 1.0` in vertex shaders if `FORCE_POINT_SIZE` option was set

src/back/glsl/mod.rs, tests/out/glsl/math-functions.main.Vertex.glsl
Update `countLeadingZeros` to use `findMSB` in `400+` and `es 310+`.
As a side note, all of the integer functions categorized under `// bit` have the same [version requirements](https://docs.gl/sl4/bitCount).
=> [glsl-out] Version check countLeadingZeros

src/front/spv/function.rs, src/front/spv/mod.rs, tests/out/ir/shadow.ron
SPIR-V doesn't allow the `Flat`, `NoPerspective`, `Sample` or `Centroid` decorations on fragment shaders outputs ([VUID-StandaloneSpirv-Flat-06201](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-StandaloneSpirv-Flat-06201)), but the spirv frontend was applying default interpolation to all outputs unconditionally.
This wasn't an issue for most shaders since they output floats and the default values for them don't interfere with SPIR-V semantics, but if the shader returned a uint or int the interpolation would be set to `Flat` which as stated above is disallowed.
This commit fixes the issue by only running the default interpolation code when constructing the entry point and if the stage/IO allow it.
=> spv-in: Don't apply interpolation to fragment shaders outputs

.github/workflows/ci.yml, .github/workflows/lazy.yml, .github/workflows/pipeline.yml, .github/workflows/validation-linux.yml, .github/workflows/validation-macos.yml, .github/workflows/validation-windows.yml
- update actions
- check `naga-fuzz`
- use `cargo-nextest`
- remove unmaintained `actions-rs` actions
- only check on MSRV and minimal-versions (dev deps might bump up the version of deps)
- enable colors in the CI terminal
- use `cargo-llvm-cov` (improves accuracy of reports 69% -> 82%, wgpu also uses it)
- compute and upload coverage to codecov for PRs as well
(should resolve all CI warnings; ex. scroll down to "Annotations" section https://github.com/gfx-rs/naga/actions/runs/4085172347)
=> Improve CI

.github/workflows/lazy.yml, .github/workflows/validation-linux.yml, .github/workflows/validation-macos.yml, .github/workflows/validation-windows.yml
- fix `Error: Unable to resolve action 'Napokue/setup-dxc@v1.1', unable to find version 'v1.1'`
- trigger workflows if their workflow file was changed (to avoid breaking CI in the future)
=> Fix `setup-dxc` not found and make sure workflows run if their file was changed

.gitattributes
Depending on how you have your gitconfig set up, running the snapshot tests can cause a diff across every snapshot on Windows where line endings might switch between LF and CRLF. Instead we can force LF for everything in the `tests/out` directory which should avoid this problem.
=> Require LF for snapshots

benches/criterion.rs, fuzz/fuzz_targets/ir.rs, src/valid/interface.rs, src/valid/mod.rs, tests/in/multiview.param.ron, tests/in/multiview_webgl.param.ron, tests/snapshots.rs, tests/wgsl-errors.rs
- fixes https://github.com/gfx-rs/naga/issues/2150
- fixes https://github.com/gfx-rs/naga/issues/2152
- also adds `Capabilities::MULTISAMPLED_SHADING` mapping to wgpu's `DownlevelFlags::MULTISAMPLED_SHADING`
=> Add missing capss

src/back/glsl/mod.rs, tests/in/invariant.param.ron, tests/in/invariant.wgsl, tests/out/glsl/invariant.frag_main.Fragment.glsl, tests/out/glsl/invariant.fs.Fragment.glsl, tests/out/glsl/invariant.vs.Vertex.glsl, tests/snapshots.rs
Fixes #2252
If the browser behavior changes here we can restore it later on, but for now at least ANGLE (maybe others) reject `invariant gl_FragCoord` as described in #2252
=> Skip `invariant` for `gl_FragCoord` on WebGL2

src/front/wgsl/parse/mod.rs, tests/in/operators.wgsl, tests/in/type-alias.wgsl, tests/out/wgsl/type-alias.wgsl
This PR addresses https://github.com/gfx-rs/naga/issues/2144#issue-1476193749.
=> [wgsl-in] Add predeclared vector and matrix type aliases

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, tests/in/access.wgsl, tests/out/analysis/access.info.ron, tests/out/glsl/access.assign_through_ptr.Compute.glsl, tests/out/glsl/access.atomics.Compute.glsl, tests/out/glsl/access.foo_frag.Fragment.glsl, tests/out/glsl/access.foo_vert.Vertex.glsl, tests/out/hlsl/access.hlsl, tests/out/ir/access.ron, tests/out/msl/access.msl, tests/out/spv/access.spvasm, tests/out/wgsl/access.wgsl
Arrays can be put behind pointers in inout and out parameters in GLSL and HLSL, whose dimensions must be specified to let array access compile. So, we specify their dimensions.
Fixes #2248
=> [glsl/hlsl-out] Write sizes of arrays behind pointers in function arguments

src/back/spv/block.rs, tests/out/spv/math-functions.spvasm
- `id` should have had the result of the last operation
- `MathOp::Custom` should have been returned since we later execute: `self.cached[expr_handle] = id;`
- removed unnecessary bitcast
=> [spv-out] fix `countLeadingZeros` impl

src/back/msl/mod.rs, src/back/msl/writer.rs, tests/in/access.param.ron, tests/in/binding-arrays.param.ron, tests/in/bitcast.params.ron, tests/in/bits.param.ron, tests/in/boids.param.ron, tests/in/extra.param.ron, tests/in/interface.param.ron, tests/in/padding.param.ron, tests/in/resource-binding-map.param.ron, tests/in/resource-binding-map.wgsl, tests/in/skybox.param.ron, tests/in/workgroup-var-init.param.ron, tests/out/msl/resource-binding-map.msl, tests/snapshots.rs
The existing `per_stage_map` field of MSL backend options specifies resource binding maps that apply to all entry points of each stage type. It is useful to have the ability to provide a separate binding index map for each entry point, especially when the same shader module defines multiple entry points of the same stage kind.
This patch introduces a new `per_entry_point_map` option. When fields are missing in the per-entry-point map, the code falls back to the existing `per_stage_map` option as before.
=> [msl-out] Replace `per_stage_map` with `per_entry_point_map`

src/valid/function.rs, tests/wgsl-errors.rs
Fixes https://github.com/gfx-rs/naga/issues/2263
as per [wgsl spec](https://www.w3.org/TR/WGSL/#discard-statement) "The discard statement must only be used in a fragment shader stage."
=> enforce discard only in fragment

src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/wgsl/writer.rs, src/front/glsl/parser/functions.rs, src/front/spv/function.rs, src/front/wgsl/lower/mod.rs, src/lib.rs, src/valid/function.rs, src/valid/mod.rs
Fixes https://github.com/gfx-rs/naga/issues/1960.
Updated all instances of `SwitchValue::Integer` to include uints.
Renamed `select_cases` to `switch_values` since it did not appear to be used for anything other than switch values.
Added a check to validate all cases had similar types. That's just how I interpreted [this bit](https://www.w3.org/TR/WGSL/#ref-for-type-rule-preconditions%E2%91%A1)  from the spec.
Added a duplicate `SwitchValue` enum to validation since I wasn't sure if adding additional derives to `lib` was appropriate or not. This adds a tiny bit of redundancy that I can remove if needed.
=> Differentiate between i32 and u32 in switch

src/front/glsl/parser/functions.rs, tests/in/glsl/statements.frag, tests/out/wgsl/statements-frag.wgsl
GLSL allows for implicitly converting `int` -> `uint` in switch cases.
=> [glsl-in] Switch implicit type conversion

src/arena.rs, src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/hlsl/conv.rs, src/back/msl/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/variables.rs, src/front/spv/function.rs, src/front/spv/mod.rs, tests/out/hlsl/quad-vert.hlsl, tests/out/wgsl/quad-vert.wgsl
also closes https://github.com/gfx-rs/naga/issues/2182
=> Skip `gl_PerVertex` unused builtins in the SPIR-V frontend

src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/wgsl/writer.rs, src/front/glsl/builtins.rs, src/front/spv/mod.rs, src/front/wgsl/lower/mod.rs, src/front/wgsl/parse/conv.rs, src/lib.rs, src/proc/typifier.rs, src/valid/analyzer.rs, src/valid/expression.rs, src/valid/handles.rs, tests/in/standard.wgsl, tests/out/glsl/standard.derivatives.Fragment.glsl, tests/out/hlsl/standard.hlsl, tests/out/msl/standard.msl, tests/out/spv/standard.spvasm, tests/out/wgsl/standard.wgsl
Adds the following from https://github.com/gfx-rs/naga/issues/2134
- dpdxCoarse
- dpdxFine
- dpdyCoarse
- dpdyFine
- fwidthCoarse
- fwidthFine
Feel free to make any changes btw.
=> Add partial derivative builtins

src/back/spv/writer.rs, tests/in/fragment-output.wgsl, tests/out/glsl/fragment-output.main.Fragment.glsl, tests/out/glsl/fragment-output.main_vec2scalar.Fragment.glsl, tests/out/glsl/fragment-output.main_vec4vec3.Fragment.glsl, tests/out/hlsl/fragment-output.hlsl, tests/out/hlsl/fragment-output.hlsl.config, tests/out/msl/fragment-output.msl, tests/out/spv/fragment-output.spvasm, tests/out/wgsl/fragment-output.wgsl, tests/snapshots.rs
Furthermore, fix allowing to add `Centroid` and `Sample` decorator to vertex inputs.
Fixes #2270
Testing:
Verified this against the scenario in #2270 on a Windows machine and ran existing tests. I expected `interpolate.wgsl` to produce a different spirv because of my change on  `Centroid` and `Sample`, but it seems those are already suppressed elsewhere as well (?).
Added test to verify how fragment outputs are passed out depending on type.
=> [spirv-out] Fix adding illegal decorators on fragment outputs.

src/back/spv/block.rs, tests/out/spv/functions.spvasm, tests/out/spv/math-functions.spvasm
Short: this fixes integer dot product SPIR-V generation by moving a constant declaration to the right place.
Longer:
The code generation for integer dot products would (only sometimes, I am not sure why the tests do not catch this) produce SPIR-V that is technically invalid because it tries to declare constant null/0 inside of a function:
```
; Function 21
%21 = OpFunction %void None %22
%17 = OpLabel
// [...]
// vvv generated integer dot product
%38 = OpConstantNull %uint
%39 = OpCompositeExtract %uint %33 0
%40 = OpCompositeExtract %uint %36 0
%41 = OpIMul %uint %39 %40
%42 = OpIAdd %uint %38 %41
// [...]
```
Running against the SPIR-V validator (or a sufficiently pedantic driver like those for the Intel Arc Alchemist) causes a validation failure along the lines of:
```
error: line 55: …
```
=> [spv-out] Fix invalid spirv being generated from integer dot products

src/back/spv/block.rs, src/back/spv/helpers.rs, src/back/spv/mod.rs, src/back/spv/writer.rs, src/lib.rs, src/proc/index.rs, src/proc/typifier.rs, src/valid/interface.rs, src/valid/type.rs, tests/in/binding-buffer-arrays.param.ron, tests/in/binding-buffer-arrays.wgsl, tests/out/spv/binding-arrays.spvasm, tests/out/spv/binding-buffer-arrays.spvasm, tests/out/wgsl/binding-buffer-arrays.wgsl, tests/snapshots.rs, tests/wgsl-errors.rs
Built upon #2256 , which should land first. I can also move this one out (so far just one commit).
Only WGSL -> IR -> SPV path supported right now.
Closes #1864
=> Support array bindings of buffers

src/back/msl/writer.rs, tests/out/msl/access.msl, tests/out/msl/policy-mix.msl, tests/out/msl/workgroup-var-init.msl
Assigning arrays by value works fine since all arrays are now wrapped by a struct.
Author: @teoxoy
=> [msl-out] Revert af4d989 since #764 removes the need for it

src/back/hlsl/conv.rs, src/back/hlsl/help.rs, src/back/hlsl/storage.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/front/glsl/functions.rs, src/front/glsl/parser/types.rs, src/front/spv/function.rs, src/front/spv/mod.rs, src/front/wgsl/lower/construction.rs, src/front/wgsl/lower/mod.rs, src/front/wgsl/mod.rs, src/proc/layouter.rs, src/proc/mod.rs, src/valid/compose.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/interface.rs, src/valid/mod.rs, src/valid/type.rs
Split from https://github.com/gfx-rs/naga/pull/2266
=> Introduce `GlobalCtx`

src/lib.rs
I noticed that I had let `dbg!(…)` sneak into commits in #2294 by accident. Clippy can help us with this! Set `deny(clippy::dbg_macro)`, so CI catches this for future contributions.
---
We do this for `panic`king, but I'm not sure if `deny` or `warn` is more appropriate for a debugging tool like `dbg!(…)`.
=> Add several `clippy` lints

src/front/spv/mod.rs
This conflicts with #2290, so it's fine for that to land first.
cc @eddyb
=> [spv-in] Improve documentation for SPIR-V control flow parsing.

src/front/wgsl/parse/mod.rs, tests/in/lexical-scopes.wgsl, tests/out/wgsl/lexical-scopes.wgsl, tests/wgsl-errors.rs
Previously,
```rs
fn x(a: f32, a: vec2<f32>) {}
```
was silently accepted by naga, binding the second parameter to `a`.
Now, it errors with
```rs
error: redefinition of `a`
┌─ ..\naga tests\wgsl.wgsl:1:6
│
1 │ fn x(a: f32, a: vec2<f32>) {}
│      ^       ^ redefinition of `a`
│      │
│      previous definition of `a`
```
=> [wgsl-in] Error on param redefinition

src/back/dot/mod.rs, src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/back/wgsl/writer.rs, src/front/glsl/constants.rs, src/front/spv/mod.rs, src/front/wgsl/error.rs, src/front/wgsl/lower/mod.rs, src/lib.rs, src/proc/terminator.rs, src/proc/typifier.rs, src/valid/analyzer.rs, src/valid/expression.rs, src/valid/function.rs, src/valid/handles.rs, tests/in/workgroup-uniform-load.wgsl, tests/out/glsl/workgroup-uniform-load.test_workgroupUniformLoad.Compute.glsl, tests/out/hlsl/workgroup-uniform-load.hlsl, tests/out/hlsl/workgroup-uniform-load.hlsl.config, tests/out/msl/workgroup-uniform-load.msl, tests/out/spv/workgroup-uniform-load.spvasm, tests/out/wgsl/workgroup-uniform-load.wgsl, tests/snapshots.rs
=> Workgroup uniform load

CHANGELOG.md, Cargo.toml, src/back/spv/block.rs, src/back/spv/helpers.rs, src/back/spv/mod.rs, src/back/spv/writer.rs, src/lib.rs, src/proc/index.rs, src/proc/typifier.rs, src/valid/interface.rs, src/valid/type.rs, tests/in/binding-buffer-arrays.param.ron, tests/in/binding-buffer-arrays.wgsl, tests/out/spv/binding-arrays.spvasm, tests/out/spv/binding-buffer-arrays.spvasm, tests/out/wgsl/binding-buffer-arrays.wgsl, tests/snapshots.rs, tests/wgsl-errors.rs
=> [0.12] Support array bindings of buffers

Cargo.toml, src/back/glsl/mod.rs, src/back/hlsl/keywords.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/wgsl/writer.rs, src/proc/namer.rs, tests/in/hlsl-keyword.wgsl, tests/out/hlsl/hlsl-keyword.hlsl, tests/out/hlsl/hlsl-keyword.hlsl.config, tests/snapshots.rs
Honestly I realized while almost done with this that maybe trying to put maintenance effort into FXC rather than DXC wouldn't be worth it, but OH WELL. Feel free to deny this PR if we don't want to add bugfixes for FXC.
There are a few keywords like "pass" in HLSL that are actually case-insensitive for FXC. This can be disabled with strict mode, but even if you do that FXC will continue to give an error if you try to use them in identifiers (at all, with any casing).
This changes the namer code to escape these keywords even if the casing is different.
If you're wondering where I got the list from: I looked at the list of strings in D3DCompiler_47.dll. None of this is documented.
=> Handle case insensitive FXC HLSL keywords.

Makefile
Newer versions of these programs require `-` as a filename argument to read from standard input.
=> Makefile: validate-spv: update spirv-as and spirv-val invocations.

src/valid/expression.rs
In `src/valid/expresion.rs`, use the full path `std::ops::Index` when implementing the trait on `ExpressionTypeResolver`. This implementation is `#[cfg(feature = "validate")]`, so the `use` directive becomes unnecessary when that feature is not enabled, triggering warnings.
=> Don't `use std::opsIndex`, used only when `"validate"` is on.

src/back/spv/mod.rs, src/back/spv/recyclable.rs, src/back/spv/writer.rs, src/lib.rs, tests/out/spv/bounds-check-image-restrict.spvasm, tests/out/spv/bounds-check-image-rzsw.spvasm, tests/out/spv/image.spvasm, tests/out/spv/ray-query.spvasm, tests/spirv-capabilities.rs
Naga currently doesn't pass its own CI because its tests hardcode a specific `hashbrown`+`fx` iteration order.
And then upstream upgraded `hashbrown` in `nightly-2023-06-16` which changed the order:
* https://github.com/rust-lang/rust/pull/104455
What's worse is I'm hitting this on a `v0.10` backport, where I would prefer not to backport this PR too:
* https://github.com/gfx-rs/naga/pull/2387
=> [spv-out] Use `IndexSet` instead of `HashSet` for iterated sets (capabilities/extensions).

src/back/msl/sampler.rs, src/back/spv/mod.rs, src/back/spv/recyclable.rs, src/back/spv/writer.rs, src/lib.rs, tests/out/spv/bounds-check-image-restrict.spvasm, tests/out/spv/bounds-check-image-rzsw.spvasm, tests/out/spv/image.spvasm, tests/spirv-capabilities.rs
Updated version of #2390, since for some reason I can't push new commits to that PR.
@jimblandy: Adapt v0.10 to modern Clippy, cargo doc.
=> [revised v0.10 backport] [spv-out] Use `IndexSet` instead of `HashSet` for iterated sets (capabilities/extensions).

src/back/msl/mod.rs, src/back/msl/writer.rs, tests/in/interface.param.ron
Follow-up to https://github.com/gfx-rs/naga/pull/1674 where the behavior changed but the name and docs haven't.
=> Rename `allow_point_size` to `allow_and_force_point_size`

src/lib.rs
For my use case, I need to be able to access the `conservative` field of the `EarlyDepthTest` struct. Every other top-level public struct has every field accessible, so this just brings `EarlyDepthTest` in line with the other components of a module.
=> Expose early depth test field

src/back/glsl/mod.rs
This fixes shader compilation issues when writing wgsl code like `textureDimensions(texture, 0u)` with the GLSL backend.
[GLSL textureSize spec](https://registry.khronos.org/OpenGL-Refpages/gl4/html/textureSize.xhtml)
=> [glsl-out] textureSize level must be a signed integer.

src/back/wgsl/writer.rs, tests/out/wgsl/binding-arrays.wgsl, tests/out/wgsl/binding-buffer-arrays.wgsl, tests/out/wgsl/fragment-output.wgsl, tests/out/wgsl/interface.wgsl, tests/out/wgsl/interpolate.wgsl, tests/out/wgsl/shadow.wgsl
Backports #2318 to naga 0.12 because Bevy needs it for webgpu now that they adopted [naga_oil](https://github.com/bevyengine/naga_oil/).
Related: https://github.com/bevyengine/bevy/issues/9028
=> Backport Simplify map_binding_to_attribute to always return an interpolate attribute to 0.12

Cargo.toml, cli/Cargo.toml
Bumps various dependencies ahead of release.
**This also bumps MSRV from 1.63 to 1.64 after indexmap bumped their MSRV**
=> Bump dependencies

src/back/spv/image.rs, src/front/spv/image.rs, src/front/spv/mod.rs, tests/out/spv/binding-arrays.spvasm, tests/out/spv/image.spvasm
This pull request conditionally casts Sints in OpImageQuery functions where previously it was assumed to always be Sint and simplifies the backend by removing unneeded casts.
fixes https://github.com/gfx-rs/naga/issues/2354
=> [spv] Fix OpImageQueries to allow Uints

src/valid/interface.rs, tests/in/glsl/buffer.frag, tests/out/wgsl/buffer-frag.wgsl
Storage buffers only support `read` or `read_write` access modes (not `write`).
Related: https://github.com/gfx-rs/naga/issues/2160, https://github.com/gfx-rs/wgpu/pull/3984
=> Validate storage buffer access

Cargo.toml, src/lib.rs
in updating `naga_oil` i found i needed to have the `const_expressions` arena contain only unique expressions. this is needed because the equality test for `Const`s and `GlobalVariable`s does not inspect the `init` field, it just compares handles, so otherwise equal items with equivalent inits that are distinct handles do not test as equal. I rely on the `Arena::fetch_or_append` to deduplicate consts and globals which uses the derived equality.
adds the `expression-eq` feature to enable derive of `PartialEq` for `Expression`.
i note there are quite a lot of other `PartialEq` impls that are `cfg(test)`. I don't need any of them but perhaps the feature sohuld be more general and include them as well:
```rust
front::glsl::error::ErrorKind
front::glsl::error::Error …
```
=> derive PartialEq on Expression

src/back/spv/block.rs, src/back/spv/image.rs, src/back/spv/ray.rs, src/valid/interface.rs, tests/out/spv/binding-arrays.spvasm
See https://github.com/gfx-rs/naga/pull/2421#issuecomment-1665678646
Fixes https://github.com/gfx-rs/naga/issues/2408
Closes https://github.com/gfx-rs/naga/pull/2421
Commits are self-contained and don't require to be squashed.
=> [spv-out] Decorate binding array image/sample load result as `NonUniform` 

.github/workflows/ci.yml, Cargo.toml
I noticed that using `--offline` here doesn't properly go all the way down to the actual minimal version of each dependency. Bit too lazy to dig into why exactly, and I'm not sure why `--offline` was used in the first place, but we should see CI fail in a moment.
=> Properly test `-Zminimal-versions`

Cargo.toml
Bumps `indexmap` to v2.
See the [changelog](https://github.com/bluss/indexmap/blob/master/RELEASES.md), I don't believe there are any relevant changes for `naga`.
Notably this updates `hashbrown` from v0.12 to v0.14 and `ahash` from v0.7 to v0.8.
=> Bump `indexmap` to v2

src/front/wgsl/lower/mod.rs, src/front/wgsl/tests.rs
Fixes https://github.com/gfx-rs/naga/issues/2431.
=> [wgsl-in] Fix error message for invalid texture{Load,Store}() on 2d_array

src/front/wgsl/error.rs, src/front/wgsl/parse/mod.rs, src/front/wgsl/tests.rs
=> [wgsl-in] Fail on repeated attributes

src/front/wgsl/error.rs, src/front/wgsl/lower/mod.rs, src/front/wgsl/parse/ast.rs, src/front/wgsl/parse/mod.rs, src/front/wgsl/tests.rs
Fixes #2271 and also fixes #2434.
=> [wgsl-in] Handle repeated or missing @workgroup_size

src/front/wgsl/lower/mod.rs, src/front/wgsl/tests.rs
Fixes #2439.
[Reference](https://www.w3.org/TR/WGSL/#vector-multi-component:~:text=Binary%20arithmetic%20expressions%20with%20mixed%20scalar%20and%20vector%20operands):
=> [wgsl-in] Avoid splatting all binary operator expressions

src/front/wgsl/lower/mod.rs, src/front/wgsl/tests.rs
Change `binary_op_splat()` from splatting:
vec op scalar
_ op vec
to only splat:
vec op scalar
scalar op vec
This fixes some confusing error messages. Example function:
```wgsl
fn main(mat: mat3x3<f32>) {
let vec = vec3<f32>(1.0, 1.0, 1.0);
let result = mat / vec;
}
```
=> [wgsl-in] Only splat 'scalar op vec', not '_ op vec'

.gitignore
Gets rid of a small annoyance for vim users.
=> Add vim .swp files to gitignore

xtask/src/main.rs
[DX Compiler release for August 2023 ](https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.7.2308) was just released, and that made [HLSL 2021](https://github.com/microsoft/DirectXShaderCompiler/wiki/HLSL-2021) the default, breaking the CI build.
We currently generate hlsl that is not valid HLSL 2021, as there [binary logic operators can only be used with scalars](https://github.com/microsoft/DirectXShaderCompiler/wiki/HLSL-2021#logical-operation-short-circuiting-for-scalars), so we need to change generation:
```diff
-  doit = vec && (ShouldIDoIt(vec) || !ShouldINotDoIt(vec));
+  doit = and(vec, or(ShouldIDoIt(vec), !ShouldINotDoIt(vec)));
```
While possible (changing `countLeadingZeros()` and `select()` writing is enough to pass CI), fxc does not support HLSL 2021 (and the …
=> [ci] Specify -HV 2018 to dxc

src/front/wgsl/lower/mod.rs, tests/in/standard.wgsl, tests/out/glsl/standard.derivatives.Fragment.glsl, tests/out/hlsl/standard.hlsl, tests/out/msl/standard.msl, tests/out/spv/standard.spvasm, tests/out/wgsl/standard.wgsl
In wgsl there are overloads for `all(bool)` and `any(bool)` which just returns the boolean unmodified.
As at least glsl [any](https://registry.khronos.org/OpenGL-Refpages/gl4/html/any.xhtml) and [all](https://registry.khronos.org/OpenGL-Refpages/gl4/html/all.xhtml) does not support that, let's remove them while lowering to get rid of them early.
Fixes #1911.
=> [wgsl-in] Handle all(bool) and any(bool)

src/back/glsl/features.rs, src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/mod.rs, src/back/spv/writer.rs, src/back/wgsl/writer.rs, src/front/glsl/functions.rs, src/front/glsl/variables.rs, src/front/interpolator.rs, src/front/spv/mod.rs, src/front/wgsl/parse/mod.rs, src/lib.rs, src/valid/analyzer.rs, src/valid/interface.rs, src/valid/mod.rs, tests/in/dualsource.param.ron, tests/in/dualsource.wgsl, tests/out/analysis/access.info.ron, tests/out/analysis/collatz.info.ron, tests/out/analysis/shadow.info.ron, tests/out/glsl/dualsource.main.Fragment.glsl, tests/out/hlsl/dualsource.hlsl, tests/out/hlsl/dualsource.ron, tests/out/ir/access.ron, tests/out/ir/shadow.ron, tests/out/msl/dualsource.msl, tests/out/spv/dualsource.spvasm, tests/out/wgsl/dualsource.wgsl, tests/snapshots.rs
Support writing shaders with alt blender mode.
Tested on linux with OpenGL, and Vulkan, and on Mac using metal. I have made some changes for Direct X but since I don't have a windows build environment I haven't tested that.
See https://github.com/freqmod/helicoid/tree/master/helicoid-wgpu for usage example.
See https://github.com/gfx-rs/wgpu/issues/1804#issuecomment-1669452915 for related issue
=> Support dual source blending

src/front/glsl/builtins.rs, src/front/glsl/context.rs, src/front/glsl/functions.rs, src/front/glsl/mod.rs, src/front/glsl/parser.rs, src/front/glsl/parser/declarations.rs, src/front/glsl/parser/expressions.rs, src/front/glsl/parser/functions.rs, src/front/glsl/parser/types.rs, src/front/glsl/types.rs, src/front/glsl/variables.rs
Refactors needed for https://github.com/gfx-rs/naga/pull/2309.
=> [glsl-in] Refactors

src/valid/expression.rs
Minor nit, noted by @ErichDonGubler in #2463.
=> Use || instead of |

src/valid/interface.rs
This silences a warning that shows up when we run `cargo nextest run -p naga`:
```
warning: variable does not need to be mutable
--> src/valid/interface.rs:618:13
|
618 |         let mut info = self
|             ----^^^^
|             |
|             help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
```
The only assignment to `info` appears in a `"validate"`-only block.
=> Don't warn about unused mut in tests when "validate" feature is off.

tests/snapshots.rs
When `convert_spv` fails, this makes it easier to tell which file it was trying to process.
=> snapshots::convert_spv: Print input name before processing.

src/back/spv/writer.rs, tests/in/runtime-array-in-unused-struct.wgsl, tests/out/spv/access.spvasm, tests/out/spv/boids.spvasm, tests/out/spv/bounds-check-restrict.spvasm, tests/out/spv/bounds-check-zero.spvasm, tests/out/spv/collatz.spvasm, tests/out/spv/debug-symbol-terrain.spvasm, tests/out/spv/pointers.spvasm, tests/out/spv/runtime-array-in-unused-struct.spvasm, tests/snapshots.rs
Fixes #2322, and so will fix https://github.com/bevyengine/bevy/issues/8733 and fix https://github.com/webonnx/wonnx/issues/161
I'm sure the code can be polished and expanded on to take `BufferBlock`s into account, but I just based it off of https://vulkan.lunarg.com/doc/view/1.3.246.1/windows/1.3-extensions/vkspec.html#interfaces-resources-descset, table 21. Where uniform buffers, storage buffers, and inline uniform blocks all use the `Block` decoration.
=> [spv-out] Always give structs with runtime arrays a Block decoration

src/block.rs
The `splice()` call takes `IntoIterator`, so calling `into_iter()` is not needed.
=> Remove useless calls to `into_iter()`.

src/front/wgsl/error.rs, src/span.rs
`Iterator` is a supertrait of `ExactSizeIterator`, so specifying `ExactSizeIterator` is enough.
=> clippy: Remove extra Iterator bounds.

src/valid/expression.rs, src/valid/mod.rs
The `ModuleInfo` was not used mutably.
=> clippy: Fix unnecessary_mut_passed warning.

src/valid/interface.rs
Previously, using multiple push constant variables was undefined behavior (in wgpu, this resulted in https://github.com/gfx-rs/wgpu/issues/4099). Now, multiple push constant variables per entry point is a validation error!
=> Prevent using multiple push constant variables in one entry point.

src/front/wgsl/lower/mod.rs
The `front::wgsl::lowerer::RuntimeExpressionContext::local_table` field does not need to be a mutable reference, as expressions never introduce new local bindings.
=> [wgsl-in] make RuntimeExpressionContext::local_table a shared ref.

src/back/hlsl/writer.rs, src/back/mod.rs, src/back/wgsl/writer.rs
Document `FunctionType` better.
Use `FunctionCtx` name key methods where appropriate in the WGSL and HLSL backends.
=> Small cleanups to backend naming.

tests/in/const-exprs.wgsl, tests/out/glsl/const-exprs.main.Compute.glsl, tests/out/hlsl/const-exprs.hlsl, tests/out/msl/const-exprs.msl, tests/out/spv/const-exprs.spvasm, tests/out/wgsl/const-exprs.wgsl
See comments in test for details.
=> Test that only constant expressions are hoisted to initializers.

src/arena.rs, src/compact/mod.rs, src/front/spv/mod.rs, src/front/wgsl/lower/mod.rs, src/lib.rs
Various spots in WGSL are using plain `IndexMap` and `IndexSet` from the `indexmap` crate, rather than a variant that uses the same faster hash function as the rest of Naga. Change these sites to all use the faster hash function.
=> Use fast hashing functions with `IndexMap` and `IndexSet` everywhere.

src/arena.rs, src/compact/mod.rs, src/front/spv/mod.rs, src/front/wgsl/lower/mod.rs, src/front/wgsl/parse/ast.rs, src/front/wgsl/parse/mod.rs, src/lib.rs, tests/out/wgsl/module-scope.wgsl
Use `FastIndexSet`, rather than `FastHashSet`, for tracking global declarations' dependencies, so that the order in which functions are inserted into the `Module` (and thus, the order in which they are output) is not dependent on the hash function.
Depends on #2495.
=> [wgsl-in] Use deterministic ordering for dependency ordering.

tests/snapshots.rs
Remove the call to `Validator::validate` in `convert_spv`, since it directly follows the call to `check_targets`, which also called `Validator::validate`.
The only difference between the two is whether `Parameters::god_mode` is respected, but this difference doesn't seem to have been deliberate: at the time the call to `check_targets` was added to `convert_spv` (5f21cf360, 2021-02-17), the two calls were exactly the same.
=> snapshots: convert_spv: Don't validate the module twice.

src/back/glsl/mod.rs
Implementation derived from https://en.cppreference.com/w/cpp/numeric/math/frexp#Notes. 
Produces the following in `tests/out/glsl/math-functions.main.Fragment.glsl` when targeting `< 400 & 310 es`.
``` glsl
45   │ __frexp_result_f32_ naga_frexp(float arg) {
46   │     int other = arg == float(0) ? int(0) : int(float(1) + log2(arg));
47   │     float fract = arg * exp2(float(-other));
48   │     return __frexp_result_f32_(fract, other);
49   │ }
50   │
51   │ __frexp_result_vec4_f32_ naga_frexp(vec4 arg) {
52   │     ivec4 other = arg == vec4(0) ? ivec4(0) : ivec4(vec4(1) + log2(arg));
53   │     vec4 fract = arg * exp2(vec4(-other));
54   │     return __frexp_result_vec4_f32_(fract, other);
55   │ }
```
=> [glsl-out] Polyfill frexp

src/back/spv/block.rs, src/back/spv/writer.rs, src/front/glsl/context.rs, src/front/glsl/parser/declarations.rs, src/front/wgsl/lower/mod.rs, src/proc/constant_evaluator.rs, src/proc/mod.rs
These names seem more informative. "Extra Data" is pretty noisy. "Info" is at least what Naga already uses for "Data collected about this other thing" (ModuleInfo, FunctionInfo, etc.).
- `ExpressionConstnessTracker::contains` -> `is_const`
- `ConstantEvaluatorExtraData` -> `FunctionConstantInfo` 
- `ConstantEvaluator::extra_data` -> `function_info`
=> Rename some ConstantEvaluator-associated types and values.

src/front/glsl/context.rs, src/front/wgsl/lower/mod.rs, src/proc/constant_evaluator.rs, src/proc/mod.rs
- Make the fields of `ConstantEvaluator` private to the module.
- Add constructor functions `for_module` and `for_function`.
- Make `FunctionConstantInfo` private.
=> Tighten up `ConstantEvaluator`'s public API.

tests/snapshots.rs
The duplicate entry was introduced accidentally in #1845.
=> snapshots: convert_wgsl: Remove redundant cubeArrayShadow entry.

src/valid/analyzer.rs, src/valid/expression.rs
Disables uniformity requirements for the following:
- derivative builtin functions
- `textureSample`
- `textureSampleBias`
- `textureSampleCompare`
These are the same builtins `derivative_uniformity` diagnostic targets.
=> Disable uniformity analysis for the fragment stage

src/back/msl/writer.rs, tests/in/msl-varyings.wgsl, tests/out/msl/msl-varyings.msl, tests/out/msl/shadow.msl, tests/snapshots.rs
Fixes #1490
Naming conflicts can occur when multiple structs get flattened into one varyings struct.
This moves the `namer.call` invocation into the flattening routine so that each member gets a unique name.
=> [msl-out] Make varyings' struct members unique

src/proc/constant_evaluator.rs, tests/in/const-exprs.wgsl, tests/out/glsl/const-exprs.main.Compute.glsl, tests/out/hlsl/const-exprs.hlsl, tests/out/msl/const-exprs.msl, tests/out/spv/const-exprs.spvasm, tests/out/wgsl/const-exprs.wgsl, tests/out/wgsl/module-scope.wgsl
The `#[test]` tests may be redundant. Let me know what you think.
=> Let `ConstantEvaluator` see through `Constant` exprs in `Splat` and `Compose` exprs.

src/back/spv/writer.rs
Follow-up to https://github.com/gfx-rs/naga/pull/1962 & https://github.com/gfx-rs/naga/pull/2272.
=> [spv-out] Require `ClipDistance` & `CullDistance` capabilities if necessary

src/lib.rs, src/valid/expression.rs, src/valid/mod.rs
WGSL doesn't currently allow NaNs and infinities.
Resolves https://github.com/gfx-rs/naga/issues/2461.
=> [valid] Disallow NaNs and infinities

src/proc/mod.rs, tests/wgsl-errors.rs
Restore `negative_index` test in `tests/wgsl-errors.rs`, as part of the `invalid_arrays` test function.
=> Properly recognize `Literal` expressions as non-dynamic indices.

src/valid/analyzer.rs
* Improve docs for `FunctionInfo::process_expression`.
* Remove `expression` argument to `FunctionInfo::process_expression`. We're already passing the handle and the arena, so it's superfluous.
=> Minor cleanups to `FunctionInfo::process_expression`.

src/valid/function.rs, src/valid/interface.rs, src/valid/type.rs, tests/wgsl-errors.rs
Change the validator to enforce WGSL's requirement that all variables
in the `function` and `private` address spaces must have constructible
types.
Mark the `RayQuery` type as `CONSTRUCTIBLE`, since it is intended to
be used for local variables.
Add a regression test.
=> Require that `Function` and `Private` variables be `CONSTRUCTIBLE`.

src/back/glsl/mod.rs, src/back/hlsl/conv.rs, src/back/spv/image.rs, src/back/spv/instructions.rs, src/back/wgsl/writer.rs, src/front/wgsl/mod.rs, src/lib.rs, src/proc/mod.rs
Fixes #2195 
Blocks: https://github.com/gfx-rs/wgpu/pull/3634
I'm not sure what the best course is for the wgsl backend, so I defaulted to putting the "rgba8" swizzle which is the closest available format. I suppose that the backend would have to insert some extra code to convert when interacting with the storage texture (probably that's already done in other places?).
=> Add StorageFormat::Bgra8Unorm

src/back/wgsl/writer.rs, tests/out/wgsl/operators.wgsl
Remove incorrect special case for `UnaryOperator::Not` on vectors.
=> [wgsl-out] Generate correct code for bit complement on integers.

src/back/glsl/mod.rs, src/back/hlsl/writer.rs, src/back/msl/writer.rs, src/back/spv/block.rs, src/front/spv/convert.rs, src/lib.rs, src/proc/typifier.rs, src/valid/expression.rs
None of the frontends support those.
SPIR-V's `OpIsFinite` & `OpIsNormal` require the `Kernel` capability which is only available in OpenCL.
References
[The OpenCL™ SPIR-V Environment Specification](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Env.html#required-capabilities-1.0)
[Appendix A: Vulkan Environment for SPIR-V](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap52.html#spirvenv-capabilities)
Backends also have very limited support, only MSL supports both, HLSL supports `IsFinite`, the others don't support any.
=> Remove `IsFinite` & `IsNormal` completely

src/valid/mod.rs, src/valid/type.rs
This maps to wgpu's `wgt::DownlevelFlags::CUBE_ARRAY_TEXTURES`.
=> [valid] Add `Capabilities::CUBE_ARRAY_TEXTURES`
