gfx-rs/naga

Cargo.toml
README.md
examples/convert.rs
grammars/wgsl.pest
src/front/mod.rs
src/front/spirv.rs
src/front/wgsl.rs
src/lib.rs

Also has some nice changes to the `convert` example.

[WIP] WGSL/Tint front-end

---

src/back/msl.rs
src/front/mod.rs
src/front/spirv.rs
src/front/wgsl.rs
src/lib.rs

Flat type structure

---

grammars/wgsl.pest

Fix newline handling

---

src/front/wgsl.rs
src/lib.rs

This PR adds all the missing expression types to the IR. It also upgrades the WGSL lexer and expression parser to handle them.

Singular, intrinsic, and derivative expressions

---

src/front/wgsl.rs

This is just a big usability improvement for us developers. I don't think there are downsides.

[wgsl] make lexer Error-aware

---

Cargo.toml
examples/convert.rs
src/arena.rs
src/back/msl.rs
src/front/spirv.rs
src/front/wgsl.rs
src/lib.rs

Cleaned up all the clippy lints (bar one), removed all the unsafe (!), and ran rustfmt.

General cleanup: rustfmt, clippy, unsafe

---

Cargo.toml
Makefile
examples/convert.rs
src/lib.rs
test-data/boids.ron
tests/convert.rs

There is a bit of a miscommunication between the `convert` binary and the tests still, but it's a big improvement nevertheless.

Makefile and RON converter parameters

---

Makefile
examples/convert.rs
src/arena.rs
src/back/msl.rs
src/front/wgsl.rs
src/proc/interface.rs
src/proc/mod.rs
test-data/boids.ron
test-data/boids.wgsl
tests/convert.rs

Made more progress in MSL backend, to the point of successfully generating the [boids.metal](https://github.com/gfx-rs/naga/files/4357652/boids.metal.txt) without warnings or errors.

Boids running on MSL

---

src/back/msl.rs
src/front/spirv.rs
src/front/wgsl.rs
src/lib.rs
src/proc/interface.rs
src/proc/mod.rs

Move the global usage into the IR function

---

src/back/msl.rs
src/front/spirv.rs
src/front/wgsl.rs
src/lib.rs

Add support for ConstantComposite

---

src/back/msl.rs

This is a draft implementation for #31. I think there are a lot of different ways to structure this code, so let me know if you think this is a good strategy. If so, I can replace more panics.

Avoid panics in the Metal backend

---

src/back/msl.rs
src/lib.rs

Replace panics with errors in Metal backend

---

src/front/wgsl.rs
src/lib.rs
src/proc/mod.rs
src/proc/typifier.rs

Check constant types

---

test-data/boids.wgsl
test-data/quad.wgsl

Change integer values in vector f32 initialization. Discussed this with @kvark, and for now we will need to use strict values that match the variables type, as this is still being discussed in the working group.

Examples using integers in f32 vectors

---

.gitignore
README.md
examples/convert.rs
src/arena.rs
src/back/mod.rs
src/back/spv/layout.rs
src/back/spv/mod.rs
src/back/spv/writer.rs
src/front/mod.rs
src/front/spv.rs

- Quad example compiles from both a SPIR-V and WGSL front-end

Spirv backend

---

examples/convert.rs

- Also fis extension check for spv and wgsl (missing .)

Add glsl handling to convert sample

---

src/front/glsl/parser/mod.rs
src/front/glsl/parser/preprocessor.rs

Refactor GLSL parser modules

---

src/back/msl.rs
src/back/spv/writer.rs
src/front/glsl/mod.rs
src/front/spv.rs
src/front/wgsl.rs
src/lib.rs

Related to:
- https://github.com/gpuweb/gpuweb/issues/561
- https://github.com/gpuweb/gpuweb/issues/773

Add member offsets and array strides

---

src/arena.rs
src/proc/mod.rs
src/proc/validator.rs
tests/convert.rs

First bits of IR validation

---

src/back/spv/writer.rs

- Extracted all the instructions to their own functions. 
- Added all the instructions in order of the spec with comments used to categorize the instructions.
- Categorized the whole writer.rs to have the following order:
- Lookups
- Instructions
- Parsing
- Writing
To follow up, I will start working on unit testing all these instructions. This will be another PR.
Benefit of these changes are that it all these instructions can potentially also be used in the spirv front-end. Maybe it is an idea to create a shared module for front- and back-ends

Spirv backend - Extract instructions to own functions

---

src/arena.rs
src/back/mod.rs
src/front/mod.rs
src/front/wgsl.rs
src/lib.rs
src/proc/mod.rs
src/proc/validator.rs

This PR documents many types used in the public API.

Document (almost) everything

---

src/front/glsl_new/lex_tests.rs
src/front/glsl_new/mod.rs

A first simple test of the lexer

Add simple test for glsl-new lexer

---

src/front/glsl_new/lex.rs
src/front/glsl_new/lex_tests.rs

Add glsl-new lexer line comment support

---

src/front/glsl_new/lex.rs
src/front/glsl_new/lex_tests.rs
src/front/glsl_new/parser.rs

Fix illegal chars in identifier for glsl-new

---

src/front/glsl_new/lex.rs
src/front/glsl_new/lex_tests.rs
src/front/glsl_new/parser.rs

Glsl new multi line comments

---

src/front/glsl_new/ast.rs
src/front/glsl_new/mod.rs
src/front/glsl_new/parser.rs

Add inital ast for glsl-new

---

src/front/glsl_new/ast.rs
src/front/glsl_new/error.rs
src/front/glsl_new/lex.rs
src/front/glsl_new/lex_tests.rs
src/front/glsl_new/mod.rs
src/front/glsl_new/parser.rs
src/front/glsl_new/parser_tests.rs

A little bit more work on parser/ast :)
Includes tests 🧪

Glsl new handle version

---

src/front/glsl_new/ast.rs
src/front/glsl_new/mod.rs
src/front/glsl_new/parser.rs

Add more glsl-new handling of funcs and types

---

src/front/glsl_new/ast.rs
src/front/glsl_new/mod.rs
src/front/glsl_new/parser.rs

[glsl-new] store int constants in module

---

src/front/glsl_new/ast.rs
src/front/glsl_new/mod.rs
src/front/glsl_new/parser.rs
src/front/glsl_new/parser_tests.rs

[glsl-new] handle gl_Position builtin

---

src/front/glsl_new/ast.rs
src/front/glsl_new/parser.rs

- Initial work for handling expressions that also generates statements
- Not all expression rules handled yet

[glsl-new] Add ExpressionRule for expr/stmts

---

src/front/glsl_new/parser.rs
test-data/simple.vert

Should be simple enough :)
Ran into #85, so switching `simple.vert` to float.

[glsl-new] Add float consts

---

src/front/glsl_new/ast.rs
src/front/glsl_new/error.rs
src/front/glsl_new/lex.rs
src/front/glsl_new/parser.rs
test-data/simple.vert

Still lots of todos, but can now parse global in/out vars 😄

[glsl-new] initial declarations support

---

src/front/glsl_new/ast.rs
src/front/glsl_new/lex.rs
src/front/glsl_new/parser.rs
test-data/simple.vert

Manage to get local vars working :)

Glsl new local vars

---

Cargo.toml
src/front/glsl_new/ast.rs
src/front/glsl_new/error.rs
src/front/glsl_new/parser.rs

[glsl-new] put validation errors behind feature

---

src/front/glsl_new/parser.rs

[glsl-new] Use Empty statement

---

src/front/glsl_new/parser.rs

Small change :)
One step closer to matching wgsl frontend.

[glsl-new] set global_usage on functions

---

src/front/wgsl.rs

I think this follows all the rules.
https://gpuweb.github.io/gpuweb/wgsl.html#literals

Better floating point support for wgsl

---

src/front/wgsl.rs
src/lib.rs
test-data/function.wgsl

This pr adds support statement function calls, as well as fixes an issue with importing a namespace with multiple namespaces, aka: `import "GLSL.std.450" as std::glsl;`.
Resolves #136

[wgsl] Add more complete function calling support

---

.github/workflows/pipeline.yml
src/front/glsl_new/mod.rs
src/front/mod.rs

Add dependency on serialize for Rosetta tests

---

src/back/glsl.rs

Just some small fixes to fix names that begin with digits and actually put names on functions arguments

glsl-out: Fixed names beginning with digits and arguments without names

---

src/front/spv/flow.rs
src/front/spv/mod.rs

What the title says. I also fixed the traversal. Before It was repeatedly adding merge blocks.

Add kill, unreachable + switch

---

src/back/glsl.rs
src/back/msl.rs
src/front/spv/convert.rs
src/front/spv/error.rs
src/front/spv/function.rs
src/front/spv/mod.rs
src/lib.rs
src/proc/interface.rs
src/proc/typifier.rs

Addresses a large portion of  #155
See commit names. I checked every single one to pass full checks locally.

Improve SPIR-V frontend with image operands, dot and transpose

---

src/front/spv/flow.rs
src/front/spv/function.rs
src/front/spv/mod.rs

Implementation of phi removal for SPIR-V front-end.
Also fixes bug in traversal when else branch == merge branch.

SPIR-V front-end: Phi removal

---

src/back/spv/writer.rs

Refactor of the base logic for functions. Strong base is needed to support complex shaders in the future (boids for example). As the quad sample only works now, which is very basic, there was no need to have a "great" parsing for functions.
Recently, there has been more and more interest in more complex features of spirv like: if/else statements, loops, access chains etc.
This PR includes:

[spirv-out] - Refactor Function Base

---

src/front/glsl_new/lex.rs
src/front/glsl_new/parser.rs

- continue
- break
- return
- discard

[glsl-new] Add jump statements

---

src/back/spv/mod.rs
src/back/spv/rosetta_tests.rs

For now just check that spv-out succeeds

[spv-out] Add initial Rosetta test

---

src/back/glsl.rs
src/proc/interface.rs

I have also included some changes that are related to the fact that we were using some vulkan glsl only parts

[glsl-out]: combined image sampler

---

src/front/glsl/error.rs
src/front/glsl/mod.rs
src/front/glsl/parser.rs
src/front/glsl/variables.rs

Refactor variable handling out of parser.rs

[glsl-in] Add gl_VertexIndex

---

src/front/glsl/lex.rs
src/front/glsl/parser.rs

Also reorder things slightly in parser, in order to match the GLSL spec

[glsl-in] Add uniforms and structs

---

src/back/glsl.rs
src/lib.rs
src/proc/interface.rs
src/proc/typifier.rs

See https://github.com/gpuweb/gpuweb/issues/989
This PR cares about IR, the backend and validator support will need to come later.

Add ArrayLength expression

---

src/front/glsl/ast.rs
src/front/glsl/error.rs
src/front/glsl/parser.rs

Also includes some minor cleanup in parser

[glsl.in] Implement field lookup

---

src/front/glsl/parser.rs
src/front/wgsl/mod.rs
src/proc/validator.rs
test-data/boids.wgsl
test-data/simple/module.ron
tests/rosetta.rs

Another step towards  #59
This PR establishes the structure of the validator, and covers global variables and entry points.
There is an annoying bit that it's hard to say if a global is a storage buffer/texture or not, I wasn't able to figure that out yet, but it's not a blocker.

Validation of global variables and entry points

---

Makefile
examples/convert.rs
src/back/glsl.rs
src/back/msl.rs
src/back/spv/instructions.rs
src/back/spv/writer.rs
src/front/spv/mod.rs
src/front/wgsl/lexer.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/interface.rs
src/proc/mod.rs
src/proc/typifier.rs
test-data/boids.param.ron
test-data/quad.param.ron
test-data/quad.wgsl

See https://github.com/gpuweb/gpuweb/pull/909 and multiple follow-ups.
also, Fixes #204

[ir, wgsl] Texture support

---

src/back/spv/writer.rs

Add support for a matrix construct. 
This WGSL input:
```
[[stage(fragment)]]
var matrix: mat3x3<f32> = mat3x3<f32>(1.0, 2.0, 3.0);
return;
}
```
Will result in this SPIR-V output:
```
%main = OpFunction %void None %13
%14 = OpLabel
%9 = OpVariable %_ptr_Function_mat3v3float Function
%15 = OpCompositeConstruct %v3float %float_0_1 %float_0_2 %float_0_3
%16 = OpCompositeConstruct %v3float %float_0_1 %float_0_2 %float_0_3
%17 = OpCompositeConstruct %v3float %float_0_1 %float_0_2 %float_0_3
%18 = OpCompositeConstruct %mat3v3float %15 %16 %17
OpStore %9 %18 None
OpReturn
OpFunctionEnd
```
There isn't (yet) support for diagonal matrix initialization like in GLSL as far as I know, so I didn't take that into account with the changes.

[spv-out] Add matrix construct support

---

src/back/glsl.rs
src/back/msl.rs
src/back/spv/test_framework.rs
src/back/spv/writer.rs
src/front/glsl/types.rs
src/front/spv/mod.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/typifier.rs
src/proc/validator.rs

Should fix #229. I haven't included any additional validation, as I don't know how to do that (yet). I don't know if that is necessary for this PR or if that can be added later.

[ir] Remove Matrix Kind from the IR

---

src/front/glsl/lex.rs

Have single place where advancing to next line

[glsl-in] Extract lexer next_line method

---

src/back/msl.rs

[msl-out] Added the new method to the msl Writer

---

README.md
src/back/glsl.rs

Adds support for new external functions on the glsl backend to make it on par with the typifier
Also adds the under construction symbol on the readme that i always forget to add

Added support for more external functions on the glsl backend

---

src/arena.rs
src/front/spv/mod.rs
src/proc/mod.rs
src/proc/validator.rs

Just a little bit of a quality of life improvement

Add scalar_kind() accessor to IR Type

---

src/front/glsl/lex.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs

I added some control flow to the GLSL frontend.

Glsl control flow

---

src/front/spv/flow.rs

This brings 3 further fixes:
- `stop_node_index` is correctly propagated. What does this do? When you have a `Header block`/`Loop  block`, they recurse into their children. However, all the children except their `Merge  block` must stop upon arriving at the beforementioned `Merge block`. Example here: 
Code:
```
uint collatz_iterations(uint n) {
uint i = 0;
if (n == 4 ) {
while(true) {
if(n == 1u) {
if (mod(n, 2) == 0) {
n = n / 2;
}
else {
n = (3 * n) + 1;
}
i++;
continue;
} else {
if(n == 10) {
break;
} else {
continue;
}
}
}
} else {
return 4;
}
for(int j = 0; j < 5; j++) {
if (j == 2) {
break;
}
}
while(true) {
}
return i;
}
```
Graph:
```
digraph ControlFlowGraph {0 [ label = "%11 Some(Header)" ]
1 [ label = "%18 None" ]
2 [ label = "%20 Some(Loop)" ]
3 [ label = "%24 Some(Break)" ] …
```

spv-in: more loop fixes

---

src/back/glsl.rs

This pretty trivial change unfortunately required a loop to mutably borrow both
`builder` and `manager` at the same time, so I had to separate them. Perhaps a
cleaner solution would be to use an object with internal state instead of free
functions.

[glsl-out] Handle initializers for locals

---

src/front/glsl/parser.rs

See #175 
Appends return statement to function, if not already present as last statement

[glsl-in] Make sure functions ends with return

---

src/arena.rs
src/back/glsl.rs
src/back/msl.rs
src/back/spv/writer.rs
src/front/spv/mod.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/validator.rs

Our old semantics was entirely broken wrt SPIR-V :sweat_smile:

Fix and refactor the constant array sizes

---

src/back/spv/writer.rs

Combined matches together to reduce indentation. Later when the `BinaryOperator` match grows, we can consider to split each match to its own function.

[spv-out] Reduce BinaryOperator::Multiply indentation

---

src/front/glsl/parser.rs

Related to #277 
Example:
```glsl
#version 450
void main() {
float w = float(1);
} 
```
This should now result in `Expression::As` instead of `Expression::Compose`

[glsl-in] Handle simple casts

---

src/front/glsl/parser.rs

[glsl-in] use TypeInner::scalar_kind for casts

---

src/back/spv/writer.rs

Should fix a problem 3 wgpu-rs examples are facing currently. This change is a duplicate, and used by the matching arm of `Expression::Binary`. I want to refactor this, so we can easily use this for other Expressions (without DRY code), but I will do that a little bit later when spv-out is more feature complete.
Fixes #283

[spv-out] Load variables when using CompositeConstruct

---

src/lib.rs
src/proc/typifier.rs
src/proc/validator.rs

Required for https://github.com/gfx-rs/wgpu/pull/1034

Derive PartialEq for validation errors

---

src/front/glsl/parser.rs

For now simple ignore explicit `gl_PerVertex` struct. Will treat builtins like `gl_Position` like when implicit.

[glsl-in] Skip gl_PerVertex

---

src/back/spv/instructions.rs
src/back/spv/writer.rs

Follow-up to #220 to help with https://github.com/gfx-rs/wgpu-rs/issues/620

[spv-out] fix generation of OpConvert

---

src/front/wgsl/conv.rs
src/front/wgsl/mod.rs

See https://github.com/gpuweb/gpuweb/pull/1254 and https://github.com/gpuweb/gpuweb/issues/1219

[wgsl] update builtin names, have implicit function return type

---

src/front/glsl/parser.rs
src/front/wgsl/mod.rs
src/proc/mod.rs
src/proc/terminator.rs

Terminator processor, used in WGSL and GLSL frontends

---

src/front/wgsl/lexer.rs
src/front/wgsl/mod.rs
src/front/wgsl/tests.rs

Also refactors `parse_statement` and fixes the switch parsing (horay for tests!)

[wgsl] Tests for if/loop/switch statements

---

src/back/spv/instructions.rs
src/back/spv/writer.rs

I commented out the capabilities, since these are currently broken - #312
There is a test CI run - https://github.com/gfx-rs/wgpu/runs/1507885603

[spv] write down workgroup size

---

Cargo.toml
Makefile
examples/convert.rs
src/back/spv/layout_tests.rs
src/back/spv/mod.rs
src/back/spv/writer.rs
test-data/boids.param.ron
test-data/quad.param.ron
tests/convert.rs
tests/rosetta.rs

Reworked Spirv capabilities, more tests

---

src/back/glsl/mod.rs
src/back/msl/writer.rs
src/back/spv/writer.rs
src/front/spv/function.rs
src/front/spv/mod.rs
src/front/wgsl/conv.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/interface.rs
src/proc/mod.rs
src/proc/typifier.rs
test-data/boids.wgsl

Fixes #158
Hopefully, the last big disruptive IR change here.

Add all standard library functions to the IR

---

src/back/glsl/mod.rs
src/back/msl/mod.rs
src/back/spv/writer.rs
src/front/glsl/variables.rs
src/front/spv/convert.rs
src/front/wgsl/conv.rs
src/lib.rs
src/proc/validator.rs

Matches https://github.com/gpuweb/gpuweb/pull/1295

Add workgroup id and size builtins

---

src/back/glsl/mod.rs
src/back/msl/writer.rs
src/back/spv/writer.rs
src/front/glsl/parser.rs
src/front/spv/mod.rs
src/front/wgsl/conv.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/interface.rs
src/proc/mod.rs
src/proc/typifier.rs
tests/parse.rs
tests/snapshots.rs
tests/snapshots/snapshots__quad-Fragment.glsl.snap
tests/snapshots/snapshots__quad.msl.snap

Based on #326
This is an incremental update to IR that adds support for proper array indexing, gradient levels, and texture offsets.

Update texture sampling IR

---

src/back/spv/writer.rs

[spv] improves division and modulo operators

---

src/back/glsl/mod.rs
tests/snapshots/snapshots__quad-Fragment.glsl.snap
tests/snapshots/snapshots__quad-Vertex.glsl.snap
tests/snapshots/snapshots__skybox-Fragment.glsl.snap
tests/snapshots/snapshots__skybox-Vertex.glsl.snap

Generate locations with fixed naming scheme for linking

---

src/back/msl/writer.rs
src/back/spv/writer.rs
src/front/glsl/lex.rs
src/front/glsl/parser.rs
src/front/spv/mod.rs
src/front/wgsl/lexer.rs

Small fix for math functions, to properly lookup id for the GLSL.std.450 import

[spv-out] Handle import id for GLSL.std.450

---

src/front/glsl/mod.rs
src/proc/validator.rs

Validate constant array sizes

---

src/back/spv/writer.rs

Opens up the workaround for #346
r? @parasyte

[spv] indexing arrays

---

src/front/spv/mod.rs

Fixes https://github.com/gfx-rs/wgpu/issues/1141 once the updated Naga gets in.

[spv] Relax decoration checks for global variables

---

src/front/glsl/functions.rs

Handle calls to user defined functions

[glsl-in] Implement function call

---

src/back/glsl/mod.rs
src/back/msl/mod.rs
src/back/spv/writer.rs
src/front/spv/convert.rs
src/front/spv/mod.rs
src/front/wgsl/conv.rs
src/lib.rs
src/proc/validator.rs

Matches https://github.com/gpuweb/gpuweb/pull/1318 and https://github.com/gpuweb/gpuweb/pull/1346

Sample mask support

---

.github/workflows/pipeline.yml
src/back/spv/writer.rs
tests/snapshots/snapshots__skybox.spvasm.snap

I incorrectly used the RowMajor decorator in #360, this PR fixes it to be column major

Switch to column major

---

src/front/wgsl/mod.rs
src/front/wgsl/tests.rs

[wgsl] fix postfix expression parsing

---

src/front/wgsl/mod.rs
src/front/wgsl/tests.rs

[wgsl] enable access via rgba

---

src/back/spv/instructions.rs
src/back/spv/writer.rs

Adds support for all the image sampling modifiers, including the array index selection (most complex part here), bias, depth reference, etc.

[spv] implement full image sampling

---

src/back/spv/instructions.rs

[spv] fix depth sampler type

---

src/arena.rs
src/proc/validator.rs

Enforces `[[stride]]` on arrays and `[[block]]` on structures recursively.

Check host shared decorations in the validator

---

src/front/glsl/ast.rs
src/front/glsl/functions.rs
src/front/glsl/mod.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs

Also made ParseError public and changed global declarations to default to private instead of throwing error

[glsl-in] Add support for function declarations with arguments

---

src/back/spv/writer.rs
src/proc/typifier.rs
tests/snapshots/snapshots__boids.msl.snap
tests/snapshots/snapshots__boids.spvasm.snap
tests/snapshots/snapshots__collatz.spvasm.snap
tests/snapshots/snapshots__quad.spvasm.snap
tests/snapshots/snapshots__shadow.msl.snap
tests/snapshots/snapshots__shadow.spvasm.snap
tests/snapshots/snapshots__skybox.spvasm.snap

Fixes #339
Also, fixes the `Typifier`'s handling of logical operations, which was broken for everybody 😅

[spv] replace the internal type inferrence with the typifier

---

src/front/glsl/ast.rs
src/front/glsl/functions.rs
src/front/glsl/lex.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs
src/front/glsl/variables.rs
src/lib.rs
src/proc/constants.rs
src/proc/mod.rs

Adds another processor to translate expressions to constants if possible

[glsl-in] Added support for initalizers and constants

---

src/proc/typifier.rs

Helps with https://github.com/gfx-rs/wgpu/issues/1197

Don't break upon a void function in the typifier

---

src/back/glsl/mod.rs
src/back/msl/writer.rs
src/front/spv/mod.rs
src/front/wgsl/mod.rs
src/front/wgsl/tests.rs
src/lib.rs
src/proc/constants.rs
src/proc/interface.rs
src/proc/typifier.rs

Closes #412
Note: this PR does a bit of a minimal work to roll in the IR. There is still work to do in the font-ends and SPIR-V backend (as follow-ups).

Image queries

---

src/back/glsl/mod.rs
src/front/glsl/functions.rs

Also fixes a mistake when building the `mix` function in glsl-in where the third argument wasn't set

[glsl-*] component wise comparisons and more math functions

---

src/front/spv/error.rs
src/front/spv/mod.rs

Fixes the annoying warnings about matrix decorations.

[spv-in] handle matrix decorations

---

src/front/spv/mod.rs

Fixes #413
Another step closer to #410

[spv-in] Implement OpCompositeInsert

---

src/front/glsl/ast.rs
src/front/glsl/parser.rs
src/front/wgsl/conv.rs
src/proc/validator.rs
tests/snapshots.rs
tests/snapshots/in/texture-array.param.ron
tests/snapshots/in/texture-array.wgsl
tests/snapshots/snapshots__texture-array.spvasm.snap

Push constant support

---

src/front/wgsl/mod.rs

[wgsl] fix variable initializers wrt control flow

---

.github/workflows/validation.yml
.gitignore
Makefile

Only SPV and GLSL so far.
Follow-up to #422

Add CI action for validation of native shaders

---

src/back/msl/writer.rs
tests/out/shadow.msl.snap

[msl] Propagate entry point inputs and resources into called functions

---

src/front/glsl/parser.rs

Use `Handle` storage class for texture and sampler

[glsl-in] Fix StorageClass for texture and sampler

---

src/back/spv/writer.rs

See https://github.com/gfx-rs/naga/runs/1880675444?check_suite_focus=true

[spv-out] fix the clippy warning about Result type

---

src/front/wgsl/mod.rs
src/front/wgsl/tests.rs

Apparently, it's a thing!
We need to consider uplifting this to the IR, but so far it looks to be too specific to WGSL.

[wgsl] support 'elseif' construct

---

src/back/spv/writer.rs
tests/out/boids.spvasm.snap
tests/out/collatz.spvasm.snap
tests/out/empty.spvasm.snap
tests/out/quad.spvasm.snap
tests/out/shadow.spvasm.snap
tests/out/skybox.spvasm.snap
tests/out/texture-array.spvasm.snap
tests/snapshots.rs

Also enable the annotation for snapshots!

[spv-out] annotate function and constant names

---

src/front/wgsl/lexer.rs
src/front/wgsl/mod.rs
src/front/wgsl/tests.rs

[wgsl] fix boolean types and bang parsing

---

src/front/wgsl/mod.rs
src/front/wgsl/tests.rs

Add support for the `for` loop statement.

[wgsl] support for statement

---

LICENSE-MIT

Add MIT license

---

examples/convert.rs
src/front/glsl/ast.rs
src/front/glsl/error.rs
src/front/glsl/functions.rs
src/front/glsl/lex.rs
src/front/glsl/lex_tests.rs
src/front/glsl/mod.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs
src/front/glsl/preprocess.rs
src/front/glsl/preprocess_tests.rs
src/front/glsl/variables.rs
tests/in/quad-glsl.glsl
tests/in/quad-glsl.param.ron
tests/out/quad-glsl.ron.snap
tests/out/quad-glsl.spvasm.snap
tests/parse.rs
tests/snapshots.rs

Handle multiple entry points.
Add insta test for this.

[glsl-in] Support multiple entrypoints

---

src/proc/analyzer.rs

Follow-up from https://github.com/gfx-rs/naga/pull/491#issuecomment-780837606

Global usage tests in the analyzer

---

examples/convert.rs
src/back/msl/mod.rs
tests/snapshots.rs

It's helpful to be able to generate a MSL even if we don't have the binding map, for testing.

[msl] fake bindings

---

src/arena.rs

This makes it really easy to find the handles in the map

Implement Debug for arena and handle

---

src/back/spv/writer.rs
tests/out/boids.spvasm.snap
tests/out/collatz.spvasm.snap
tests/out/shadow.spvasm.snap

Now we aren't generating a "Label + Branch" pair for any empty block to branch on within if/else.

[spv-out] optimize if/else branching

---

src/back/glsl/mod.rs
src/back/msl/writer.rs
src/back/spv/writer.rs
src/front/glsl/functions.rs
src/front/spv/mod.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/analyzer.rs
src/proc/interface.rs
src/proc/typifier.rs
src/proc/validator.rs
tests/out/collatz.info.ron.snap
tests/out/collatz.msl.snap
tests/out/collatz.ron.snap
tests/out/collatz.spvasm.snap
tests/out/shadow.info.ron.snap
tests/out/shadow.msl.snap
tests/out/shadow.ron.snap
tests/out/shadow.spvasm.snap
tests/out/skybox.msl.snap

First step of https://github.com/gfx-rs/naga/issues/452#issuecomment-782784985

Remove mutation from the Call expression

---

src/front/wgsl/lexer.rs
src/front/wgsl/mod.rs

These changes should be non-functional but will enable #380 for `Error::Unexpected`. Other error variants will also be able to include these token spans after this change, but I thought it might be useful to try it with `Unexpected` first to keep the diff small.

[wgsl] Track token span for unexpected errors

---

src/front/spv/mod.rs

[spv-in] fix OpString and OpLine parsing

---

src/back/spv/writer.rs
src/front/spv/mod.rs

Fixes the issue found in #520 related to the switch selection.
Complements #523 
cc @MatusT

[spv] fix unsigned selector and bitcast

---

src/front/spv/flow.rs
tests/out/shadow.info.ron.snap
tests/out/shadow.ron.snap

Fixes https://github.com/gfx-rs/naga/issues/525

spv-in: Continue block should not clone Break block

---

src/back/glsl/mod.rs

[glsl-out] Fix array writing

---

src/front/wgsl/mod.rs

Fixes #532 by exposing the line number and column of the first span in the error. The first span is assumed to be the most significant because we could potentially have many important spans in a single error.

[wgsl-in] Expose location of parser errors

---

.github/workflows/validation-linux.yml
bin/convert.rs

see https://github.com/gfx-rs/naga/pull/543/checks?check_run_id=2032010132

Install graphviz on CI

---

src/back/glsl/mod.rs
tests/out/quad-Fragment.glsl.snap
tests/out/quad-Vertex.glsl.snap
tests/out/skybox-Fragment.glsl.snap
tests/out/skybox-Vertex.glsl.snap

Fix readability of output GLSL shaders

[glsl-out] Fix statement indentation

---

Makefile
src/front/spv/mod.rs

[spv-in] work around integer built-ins for compute

---

Makefile
src/lib.rs
src/proc/validator.rs

Relax interpolation validation for vertex outputs

---

src/back/dot/mod.rs
src/back/glsl/mod.rs
src/back/msl/writer.rs
src/back/spv/writer.rs
src/front/glsl/functions.rs
src/front/spv/function.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/analyzer.rs
src/proc/namer.rs
src/proc/validator.rs
tests/out/collatz.info.ron.snap
tests/out/collatz.ron.snap
tests/out/shadow.info.ron.snap
tests/out/shadow.ron.snap
tests/snapshots.rs

The idea of having a map was to make it conflict-less by construction. However, it turned out to be too inconvenient for all involved, and also inconsistent towards everything else in the API. Making it a Vec seems much nicer now.

Switch entry points from map to a vec

---

src/proc/validator.rs

This helps to work with SPIR-V shaders that have interface blocks, including the `gl_ClipDistance[]` arrays in them.

Relax array and block structure validation

---

src/back/glsl/mod.rs

I've spied a solution from [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_glsl.cpp#L6699) :smile:

[glsl-out] Workaround lod array shadow as textureGrad

---

src/back/spv/instructions.rs
src/back/spv/writer.rs

Basic implementation of derivatives (`dpdx`, `dpdy` and `fwidth`).

[spv-out] implement derivatives

---

src/front/wgsl/mod.rs
src/front/wgsl/tests.rs
tests/in/quad.wgsl
tests/in/shadow.wgsl
tests/in/skybox.wgsl
tests/out/skybox-Vertex.glsl.snap
tests/out/skybox.msl.snap
tests/out/skybox.spvasm.snap

Related to https://github.com/gpuweb/gpuweb/issues/1289 (constants only for now)

[wgsl] type inference for constants

---

src/back/msl/mod.rs
src/back/msl/writer.rs

[msl] filter out entry points based on the bindings

---

src/back/spv/writer.rs
src/front/glsl/parser.rs
src/front/spv/function.rs
src/front/spv/mod.rs
src/front/wgsl/mod.rs
src/front/wgsl/tests.rs
src/lib.rs
src/proc/layouter.rs
src/proc/validator.rs
tests/out/collatz.ron.snap
tests/out/shadow.ron.snap

Based on https://github.com/gpuweb/gpuweb/issues/1393
Fixes #579 
Fixes #567

Implement default layout in the IR and WGSL

---

src/back/dot/mod.rs
src/front/spv/mod.rs
src/proc/analyzer.rs
src/proc/layouter.rs
src/proc/validator.rs

This is a bag of related things, spawned from the need to fix https://github.com/gfx-rs/wgpu-rs/pull/796

Function call improvements

---

src/back/glsl/mod.rs
tests/out/quad-Fragment.glsl.snap
tests/out/quad-Vertex.glsl.snap
tests/out/shadow-Fragment.glsl.snap
tests/out/skybox-Fragment.glsl.snap
tests/out/skybox-Vertex.glsl.snap

We already known location index. Should help with #589

[glsl-out] Explicitly set location bindings

---

src/back/glsl/mod.rs
tests/out/quad-Fragment.glsl.snap
tests/out/quad-Vertex.glsl.snap
tests/out/shadow-Fragment.glsl.snap
tests/out/skybox-Fragment.glsl.snap
tests/out/skybox-Vertex.glsl.snap

Follow-up to #590 
r? @Gordon-F

[glsl-out] make varying names to match

---

src/proc/validator.rs

Another step towards #59
We can close the issue as soon as at least the listed sub-issues are addressed, and consider the rest of the missing logic to be bugs.
With this PR, adding more expression validation code should be straightforward.

First bits of expression validation

---

src/back/glsl/mod.rs
src/back/msl/mod.rs
src/back/spv/writer.rs
src/front/spv/convert.rs
src/front/spv/mod.rs
src/front/wgsl/conv.rs
src/lib.rs
src/proc/validator.rs

Matches https://github.com/gpuweb/gpuweb/pull/1492

Merge sample mask in/out builtins

---

src/back/msl/writer.rs
tests/out/boids.msl.snap
tests/out/collatz.msl.snap
tests/out/quad.msl.snap
tests/out/shadow.msl.snap
tests/out/skybox.msl.snap

Various MSL fixes: address spaces, select, brackets, constants, and others

---

src/front/wgsl/mod.rs
src/lib.rs

Distantly related to #613: we shouldn't be cloning statements at all.

[wgsl] don't clone statements

---

src/back/msl/writer.rs
tests/out/quad-vert.msl.snap
tests/snapshots.rs

Based on #618
Fixes #614 
This is quite unfortunate code to write, but I wish I knew a better way to deal with C++ here...

[msl] fix array element initialization

---

src/front/wgsl/tests.rs
src/valid/expression.rs

Closes #59
The following issues are closed by previous PRs in the validation series:
Closes #384 
Closes #383
Closes #453
Closes #470

Validate math functions

---

src/front/spv/mod.rs
tests/out/quad-vert.msl.snap
tests/out/shadow.ron.snap

Related to #620 (fixes the original problem, but the issue is larger as filed).

[spv-in] derivatives and fixed dynamic vector access

---

src/back/msl/writer.rs
tests/out/shadow.msl.snap

[msl] fix constant array initialization

---

src/back/glsl/mod.rs

[glsl-out] Fix Uint/Sint type conversion

---

src/back/msl/writer.rs
tests/out/boids.msl.snap
tests/out/collatz.msl.snap
tests/out/quad-vert.msl.snap
tests/out/shadow.msl.snap
tests/out/skybox.msl.snap

May help https://github.com/gfx-rs/wgpu/issues/1299

[msl] use uint behind metal namespace only

---

src/back/msl/writer.rs

Fixes  #640
Works around #613 in Metal backend

MSL allow re-emit, work around array copies

---

src/back/msl/writer.rs
tests/in/image-copy.param.ron
tests/in/image-copy.wgsl
tests/out/image-copy.msl.snap
tests/snapshots.rs

Fix MSL image storage coordinates, add a snapshot

---

src/back/msl/writer.rs

Just refactoring here.
Helps #595
At least we are no longer stack overflowing when jumping in the game.

Track MSL block function stack size, and reduce it a bit

---

src/back/msl/mod.rs
src/back/msl/writer.rs
tests/snapshots.rs

[msl-out] option to omit point size output

---

bin/convert.rs
src/proc/layouter.rs
src/valid/analyzer.rs
src/valid/mod.rs
tests/out/quad.spvasm.snap
tests/out/shadow.info.ron.snap

Fix layout roundup

---

src/back/spv/writer.rs
tests/out/texture-array.spvasm.snap

SPIRV-out fixes for depth sampling and dummy return

---

bin/convert.rs
src/back/msl/mod.rs
src/back/msl/sampler.rs
src/back/msl/writer.rs
tests/in/boids.param.ron
tests/in/collatz.param.ron
tests/in/empty.param.ron
tests/in/image-copy.param.ron
tests/in/quad-glsl.param.ron
tests/in/quad.param.ron
tests/in/shadow.param.ron
tests/in/skybox.param.ron
tests/in/texture-array.param.ron
tests/out/collatz.msl.snap
tests/out/image-copy.msl.snap
tests/out/quad.msl.snap
tests/out/shadow.msl.snap
tests/out/skybox.msl.snap
tests/snapshots.rs

Metal inlined samplers

---

src/front/spv/flow.rs

Fixes: https://github.com/gfx-rs/naga/issues/683
It seems that in real-world SPIR-V shaders (not trivially understood from a specification) there can be a case in CFG where edge to merge node can be the same branch as true or false edge from a loop block. Therefore, this block will be classified as something else rather than `break block` as it would need to be to produce a `break` statement.

spv-in: special-case a loop with true/false node == merge node

---

src/front/wgsl/mod.rs
src/front/wgsl/tests.rs
tests/errors.rs
tests/in/boids.wgsl
tests/in/image-copy.wgsl
tests/in/quad.wgsl
tests/in/shadow.wgsl
tests/in/skybox.wgsl

For https://github.com/gfx-rs/naga/issues/644

[wgsl-in] `const` to `let`

---

Cargo.toml
bin/convert.rs
src/back/hlsl/keywords.rs
src/back/hlsl/mod.rs
src/back/hlsl/writer.rs
src/back/mod.rs
tests/out/empty.hlsl.snap
tests/snapshots.rs

Start implementation of hlsl-out. This will cover only the empty case. When this is landed a simple empty entrypoint can be generated via the hlsl-out path.

Start hlsl-out

---

src/back/msl/keywords.rs

[Metal] Add the reserved types in `metal_types` to keywords

---

src/back/msl/writer.rs

This ~~, alongside https://github.com/gfx-rs/naga/pull/692, fully~~ fixes https://github.com/gfx-rs/naga/issues/685. ~~It feels a bit like a hacky solution though and I'm not sure if it's going to work in all cases.~~

[Metal] Change the function argument pointer type to use `&` instead of `*`

---

src/back/msl/writer.rs
tests/out/shadow.msl.snap

[Metal] Make constant composites non-`constexpr`

---

src/back/spv/writer.rs

[spv-out] put matrix decorations on arrays of matrices

---

src/back/msl/mod.rs
src/back/msl/writer.rs
src/front/spv/mod.rs
tests/in/boids.param.ron
tests/in/skybox.param.ron
tests/out/texture-array.msl.snap
tests/snapshots.rs

Fixes #713
Will need gfx backend changes.

[msl] push constants mapping to buffers

---

src/back/glsl/features.rs
src/valid/expression.rs
tests/snapshots.rs

Fixes the issue in Emscripten WebGPU examples

Allow stepping on floats in the validator

---

src/front/glsl/ast.rs
src/front/glsl/parser.rs

I tried uncommenting the first line in https://github.com/gfx-rs/naga/blob/9cd6fd9c205a57824644d0baedc6c15997be1e36/tests/parse.rs#L39-L44 and fixed the first failure
This PR add parsing for https://github.com/gfx-rs/naga/blob/9cd6fd9c205a57824644d0baedc6c15997be1e36/tests/cases/glsl_constant_expression.vert#L5

[glsl-in] add support for array variables

---

src/back/msl/mod.rs
tests/out/collatz.msl
tests/out/image-copy.msl
tests/out/quad.msl
tests/out/shadow.msl
tests/out/texture-array.msl

Fixes https://github.com/gfx-rs/naga/issues/736.

[Metal] Don't use an interpolation on fake bindings

---

src/front/spv/function.rs
src/front/spv/mod.rs
tests/out/shadow.info.ron
tests/out/shadow.ron

[spv-in] fix signed/unsigned casting for builtins

---

src/back/glsl/mod.rs
src/front/glsl/constants.rs
src/lib.rs

Follow up on the swizzle PR review notes

---

src/front/spv/mod.rs

Apparently generated by glslc, and ends up being present in https://noclip.website/

[spv-in] support OpModuleProcessed

---

src/front/spv/mod.rs

[spv-in] fix integer constants parsing

---

src/front/spv/error.rs
src/front/spv/image.rs
src/front/spv/mod.rs

Fixes #759 
This is my favourite kind of PR: removes code, has nice types, proper abstraction, and even fixes things :)

[spv-in] refactor image coordinate extraction

---

src/back/spv/instructions.rs
src/back/spv/writer.rs
tests/out/texture-array.spvasm

[spv-out] CFG NULL result, image and sampler type deduplication

---

src/back/glsl/mod.rs
src/back/mod.rs
src/back/msl/writer.rs
src/back/wgsl/mod.rs
src/back/wgsl/writer.rs

1. Return Err instead of panic for unimplemented cases
2. Implement writing for Scalar, Array, Matrix
3. Share some code between backends

More wgsl-out improvements

---

src/back/spv/helpers.rs
src/back/spv/instructions.rs
src/back/spv/writer.rs
src/proc/typifier.rs

Needed for https://github.com/kvark/vange-rs/pull/134

[spv-out] assorted fixes to get vange-rs shaders running

---

bin/naga.rs
src/front/glsl/parser.rs
src/front/spv/mod.rs
tests/snapshots.rs

Similar to #777 but for the frontend

[spv-in] allow non-strict check for capabilities

---

src/valid/function.rs

We needed this for a while! It's essential for the proper backend operation.

Validate that used expressions are emitted

---

src/front/wgsl/mod.rs

[wgsl-in] fix composition of a single element

---

src/back/msl/writer.rs

[msl] derive access qualifier based on the global variable flags

---

CHANGELOG.md
Cargo.toml

Going to hang in here till it's time to publish

Release v0.4

---

src/back/glsl/mod.rs
src/front/spv/mod.rs

[spv-in] null initialization for matrices

---

src/front/spv/mod.rs
src/front/wgsl/mod.rs
tests/out/skybox.msl

Fix struct layouts for WGSL and SPIRV

---

src/back/glsl/mod.rs
src/back/hlsl/writer.rs
src/back/msl/writer.rs
src/back/wgsl/writer.rs
src/proc/namer.rs

Fix #814. One more fix for #812

[glsl-out] Fix writing identifiers starting with gl_

---

src/back/msl/writer.rs
src/front/spv/error.rs
src/front/spv/function.rs
src/front/spv/mod.rs
src/front/spv/null.rs
tests/out/quad-vert.msl

[spv-in] default output builtins

---

src/front/spv/mod.rs
src/front/wgsl/mod.rs
src/proc/typifier.rs
tests/in/access.wgsl
tests/out/access.msl
tests/out/access.spvasm
tests/out/skybox.spvasm

Allow matrix indexing behind a pointer

---

.github/workflows/lazy.yml
.github/workflows/pipeline.yml
README.md

Integrate codecov on CI

---

src/back/msl/writer.rs

[mtl] move expression logic out of put_expression

---

src/back/msl/writer.rs

We can't just skip writing the rest of the entry point if we already started...
Follow-up to #825

[msl] early out if the binding sizes are missing

---

src/front/spv/flow.rs

Fixes several things:
1. Construct's variables ```enclosing_*``` were not initialized. They are needed for proper classification.
2. Construct's depth was incorrectly initialized.
3. Construct's parent was incorrectly initialized.
2. Classification of break edges(Loop/Switch/If) was brought from Tint. Finalized from the previous pull request.
3. Add break only on LoopBreak.
Fixes #856

[spv-in] fix handling of break blocks (borrowed from Tint)

---

src/front/spv/flow.rs
src/front/wgsl/conv.rs
tests/in/standard.param.ron
tests/in/standard.wgsl
tests/out/standard.Fragment.glsl
tests/out/standard.msl
tests/out/standard.spvasm
tests/snapshots.rs

Derivative tests

---

CHANGELOG.md
Cargo.toml
src/back/glsl/mod.rs
src/back/msl/writer.rs
src/back/spv/writer.rs
src/front/spv/convert.rs
src/front/spv/error.rs
src/front/spv/function.rs
src/front/spv/mod.rs
src/front/spv/null.rs
src/front/wgsl/conv.rs
src/front/wgsl/mod.rs
src/lib.rs
src/valid/expression.rs
tests/in/standard.param.ron
tests/in/standard.wgsl
tests/out/quad-vert.msl
tests/out/skybox.msl
tests/out/standard.Fragment.glsl
tests/out/standard.msl
tests/out/standard.spvasm
tests/snapshots.rs

Requested in https://github.com/gfx-rs/wgpu/issues/1360

Release 0.4.1

---

src/back/wgsl/writer.rs
tests/out/image.wgsl
tests/out/quad.wgsl
tests/snapshots.rs

Implement all statements and expressions required by image snapshot.

[wgsl-out] Enable snapshot testing for wgsl-in image test

---

src/back/wgsl/mod.rs
src/back/wgsl/writer.rs
tests/out/quad-vert.wgsl
tests/snapshots.rs

1. Implement all math functions (copy-paste from wgsl-in)
2. Rename entry point output structs if its name is none.

[wgsl-out] More improvements

---

src/back/glsl/features.rs
src/front/spv/mod.rs
tests/in/interface.param.ron
tests/in/interface.wgsl
tests/out/interface.msl
tests/out/interface.spvasm
tests/snapshots.rs

Builtins snapshot and a few fixes

---

src/back/wgsl/writer.rs
tests/out/image.wgsl
tests/out/quad-vert.wgsl
tests/out/quad.wgsl

Slightly improve readability of generated shaders

[wgsl-out] Create baking expression for texture function

---

src/front/wgsl/mod.rs
tests/wgsl-errors.rs

Dzmitry pointed out that the messages added in #873 are not as helpful as they could be.

[wgsl-in] Improve error message for UnknownIdent.

---

src/back/glsl/mod.rs
tests/out/boids.Compute.glsl
tests/out/quad-vert.Vertex.glsl
tests/out/quad.Fragment.glsl
tests/out/shadow.Fragment.glsl

Slightly improve readability of generated shaders.

[glsl-out] Write vector access as a swizzle

---

src/back/wgsl/writer.rs
tests/out/access.wgsl
tests/out/boids.wgsl
tests/out/collatz.wgsl
tests/out/control-flow.wgsl
tests/out/extra.wgsl
tests/out/interface.wgsl
tests/out/interpolate.wgsl
tests/out/operators.wgsl
tests/out/quad-vert.wgsl
tests/out/shadow.wgsl
tests/out/skybox.wgsl
tests/out/standard.wgsl
tests/snapshots.rs

Draft because some snapshots don't pass validation.

[wgsl-out] Implement all statements and expressions. Enable all wgsl-in tests

---

src/back/wgsl/writer.rs

Maybe it would be better to add options to `wgsl-out` backend and let users decide what better to do with unsupported built-in.
But for now, since we already skip members of struct with unsupported built-in when writing struct, we should skip it everywhere.

[wgsl-out] Skip access to unsupported builtin inside Store statement

---

src/valid/interface.rs

Validate built-ins to not repeat

---

src/front/glsl/ast.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs

[glsl-in] Support parsing push_constant and std430

---

src/back/spv/writer.rs

It turns out that the module's `Arena<Type>` was being passed around in a lot of places and never actually used. I guess Rust's unused variable detection was fooled by mutual recursion.
If we discover in the future that we do need the type arena somewhere deep in the depths of the call tree, this change would be a pain to undo. But I think it would be a lot more readable simply to let `Writer` hold a reference to the `Module` it's currently working on. There are ways to accomplish that while still using the same `Writer` for multiple `Module`s and retaining its allocations.

[spv-out]: Don't pass in the type arena where it's not needed.

---

src/back/wgsl/writer.rs
src/front/wgsl/mod.rs
tests/in/image.wgsl
tests/in/shadow.wgsl
tests/out/image.msl
tests/out/image.spvasm
tests/out/image.wgsl
tests/out/shadow.wgsl

See https://github.com/gpuweb/gpuweb/pull/1729

WGSL sample compare with level

---

src/front/glsl/ast.rs
src/front/glsl/functions.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs

One of the major pieces missing from the frontend, this adds only local implicit conversion and not across functions(will be done in another PR)

[glsl-in ] Implicit conversion for expressions

---

src/valid/analyzer.rs

Don't consider discard and return inside uniform control flow

---

src/front/glsl/functions.rs

Although validation doesn't complain, backends like wgsl cannot generate the compose expression

[glsl-in] Don't output empty struct in entry point

---

src/front/glsl/variables.rs
tests/in/glsl/901-lhs-field-select.vert

[glsl-in] Allow field selection behind pointers

---

src/back/glsl/mod.rs
src/back/mod.rs
src/back/wgsl/writer.rs
tests/in/access.wgsl
tests/out/access.msl
tests/out/access.spvasm
tests/out/access.wgsl
tests/out/boids.Compute.glsl
tests/out/boids.msl
tests/out/boids.wgsl
tests/out/collatz.msl
tests/out/collatz.wgsl
tests/out/globals.Compute.glsl
tests/out/interpolate.Vertex.glsl
tests/out/interpolate.msl
tests/out/interpolate.wgsl
tests/out/quad-glsl.wgsl
tests/out/quad-vert.Vertex.glsl
tests/out/quad-vert.msl
tests/out/quad-vert.wgsl
tests/out/shadow.Fragment.glsl
tests/out/shadow.msl
tests/out/shadow.wgsl
tests/out/skybox.Vertex.glsl
tests/out/skybox.msl
tests/out/skybox.wgsl

One more attempt to fix #910. Also added this case as a snapshot.
Previous discussion in #914.

Fix `Expression::Load` generating

---

src/back/spv/writer.rs

Nobody uses that value. This lets us simplify `GlobalVariable` and
`write_global_variable` as well.

[spv-out]: Don't have write_expression_pointer return a storage class.

---

src/back/glsl/mod.rs
src/back/wgsl/writer.rs

Follow up #957 for `wgsl-out` and `glsl-out`.

Simplify code for writing named expression

---

src/back/spv/writer.rs
tests/in/image.wgsl
tests/out/image.msl
tests/out/image.spvasm
tests/out/image.wgsl

[spv-out] fix image sampling ops, add more tests

---

tests/out/quad-glsl.wgsl

Regenerate quad-glsl shader

---

Makefile
src/back/hlsl/writer.rs
tests/out/quad.hlsl
tests/snapshots.rs

[hlsl-out] Reduce heap allocation

---

src/back/hlsl/writer.rs
tests/out/quad-vert.hlsl
tests/out/quad-vert.hlsl.config
tests/out/quad.hlsl
tests/snapshots.rs

Still draft, because I don't know why `dxc` segfault on output shader.

[hlsl-out] Implement all parts required by quad-spv snaphost test

---

src/front/glsl/parser.rs

Simple pr to fix a shortcoming of #973

[glsl-in] Allow structs as local type

---

CHANGELOG.md
Cargo.toml
README.md
src/front/glsl/error.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs

Release blocked on:
- https://github.com/Kangz/glslpp-rs/issues/44
- version bump
- possibly #988 ?

Changelog for v0.5 release

---

src/front/glsl/ast.rs
src/front/glsl/functions.rs
src/front/glsl/parser.rs
src/front/glsl/parser_tests.rs
src/front/mod.rs
tests/in/glsl/900-implicit-conversions.vert
tests/out/wgsl/900-implicit-conversions-vert.wgsl

Took me some time to figure it out but here's one of the largest missing parts for the glsl frontend

[glsl-in] Implicit casts for function calls

---

src/back/spv/writer.rs

[spv-out] don't OpConvert the same width

---

src/front/glsl/ast.rs
src/front/glsl/constants.rs
src/front/glsl/functions.rs
src/front/glsl/mod.rs
src/front/glsl/types.rs

A bundle of some more glsl bug fixes and new function implementations.
All commits are self contained and implement a specific feature so they can be reviewed individually

[glsl-in] more fixes

---

src/front/glsl/ast.rs

Implements addition, subtraction and division between a scalar and a vector trough an implicit splat.

[glsl-in] Support for more vector-scalar operations

---

src/back/hlsl/mod.rs
src/back/hlsl/writer.rs

Required for running gfx-rs quad example with naga path.

[hlsl-out] Implement Access and Unary expressions

---

src/back/wgsl/writer.rs

[wgsl-out] Fix Pointer writing

---

.github/workflows/validation-linux.yml
.github/workflows/validation-macos.yml
.github/workflows/validation-windows.yml

Fix CI validation tasks

---

src/lib.rs

Edits for flow, and a clearer explanation of expression evaluation time and scope.

Improvements to the Naga module-level documentation.

---

.github/workflows/lazy.yml

Test run - https://github.com/Gordon-F/naga/runs/2943811724?check_suite_focus=true
Part of #747

[CI] Add dneto0 spirv-samples to lazy task

---

src/back/msl/writer.rs
src/front/glsl/ast.rs

Fixes https://github.com/gfx-rs/wgpu/issues/1581

[mtl] detect binding incomatibility

---

src/front/glsl/functions.rs
src/valid/expression.rs
tests/in/glsl/bool-select.frag
tests/out/wgsl/bool-select-frag.wgsl

Code is quite terrible since I'm not a Rust expert yet, but it seems to work in my (admittedly limited) testing. Would love help making it better.

[glsl-in] Convert bool -> scalar cast to Select

---

src/front/glsl/ast.rs
src/front/glsl/parser_tests.rs

Fixes issues with indexing vectors. Fixes #1036.

[glsl-in] Make sure to Load on a ValuePointer as well

---

src/front/glsl/variables.rs

And remove the ability to read gl_Position in fragment.

[glsl-in] Add support for gl_FragCoord / gl_FragDepth

---

src/front/wgsl/mod.rs
tests/wgsl-errors.rs

Added some more error snapshots, and removed a few error variants that aren't used anymore.

wgsl-in: add more error tests

---

src/back/mod.rs
src/back/spv/block.rs
src/back/spv/mod.rs
src/back/spv/writer.rs
tests/in/texture-arg.param.ron
tests/out/spv/texture-arg.spvasm
tests/snapshots.rs

Follow up to #1022
Still a draft because it seems like vulkan doesn't quite like it

[spv-out] accept texture trough function argument

---

src/front/glsl/ast.rs
src/front/glsl/functions.rs
src/front/mod.rs
src/front/wgsl/mod.rs
src/front/wgsl/tests.rs
tests/in/access.wgsl
tests/in/boids.wgsl
tests/in/collatz.wgsl
tests/in/shadow.wgsl
tests/in/skybox.wgsl
tests/wgsl-errors.rs

Looks like the WGSL samples now require this.

Type inference for local variables in WGSL

---

src/front/wgsl/mod.rs

wgsl-in: fix auto array stride

---

src/back/spv/block.rs
src/lib.rs
src/valid/mod.rs

I've inferred most of this documentation from reading the code, so read it with skepticism. Let me know what I need to fix.

Document `ImageLoad`, `ImageStore`, and a few other random things.

---

src/back/hlsl/image.rs
src/back/hlsl/mod.rs
src/back/hlsl/writer.rs
src/back/wgsl/writer.rs
tests/in/skybox.param.ron
tests/out/hlsl/globals.hlsl
tests/out/hlsl/globals.hlsl.config
tests/out/hlsl/shadow.hlsl
tests/out/hlsl/shadow.hlsl.config
tests/out/hlsl/skybox.hlsl
tests/out/hlsl/skybox.hlsl.config
tests/snapshots.rs

Enables pretty much all the base tests, except boids and collatz.
See also - https://github.com/gpuweb/gpuweb/issues/1961

HLSL resources and texture coordinates

---

src/back/glsl/mod.rs
tests/out/glsl/boids.main.Compute.glsl
tests/out/glsl/quad-vert.main.Vertex.glsl
tests/out/glsl/shadow.fs_main.Fragment.glsl
tests/out/glsl/skybox.vs_main.Vertex.glsl

Possibly fix for #1115 and #1085.
@dhardy Could you retest your issue with this commits?

[glsl-out] Fix shader translation errors

---

src/back/glsl/features.rs
src/back/glsl/mod.rs
src/back/hlsl/image.rs
src/back/hlsl/writer.rs
src/back/msl/writer.rs
src/back/spv/block.rs
src/back/spv/instructions.rs
src/back/spv/writer.rs
src/back/wgsl/writer.rs
src/front/spv/image.rs
src/front/wgsl/mod.rs
src/lib.rs
src/proc/typifier.rs
src/valid/expression.rs
tests/in/image.wgsl
tests/out/hlsl/image.hlsl
tests/out/hlsl/shadow.hlsl
tests/out/ir/shadow.ron
tests/out/msl/image.msl
tests/out/spv/image.spvasm
tests/out/wgsl/image.wgsl

Follows https://github.com/gpuweb/gpuweb/pull/1793

Add MSAA depth texture type

---

src/back/glsl/mod.rs

That's strange, but we don't have any tests for this case 🤔 
Fix #1131.

[glsl-out] Fix bitcast operation for the same types

---

src/proc/mod.rs

Fix matrix size computation

---

src/back/glsl/mod.rs
src/back/hlsl/storage.rs

[glsl-out] Add `inout` qualifier for pointer function arguments

---

.github/workflows/pipeline.yml
src/back/dot/mod.rs
src/back/glsl/mod.rs
src/back/hlsl/conv.rs
src/back/hlsl/help.rs
src/back/hlsl/keywords.rs
src/back/hlsl/writer.rs
src/back/spv/mod.rs
src/back/wgsl/writer.rs

Fixes broken documentation links, replaces some normal comments with documentation comments for items and modules, adds a pipeline to check for documentation errors like broken links and some other fixes.

Documentation improvements

---

src/back/glsl/mod.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/operators.hlsl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl

Fix #1168 
@ElArtista Could you test this fix?

[glsl-out] Handle wgsl vector version of select

---

src/back/spv/block.rs

Take 2 since In the original I accidentally deleted the branch
> Currently on master cast to boolean are outputted as bitcasts which is invalid, this PR changes it so that instead NotEquals compared to 0 are emitted

[spv-out] Use NotEqual for boolean casts

---

src/back/hlsl/storage.rs
tests/out/hlsl/access.hlsl

[hlsl-out] fix member offset consideration for storage buffers

---

src/front/spv/mod.rs

[spv-in] fix struct spans for layout-less structs

---

src/front/spv/image.rs

[spv-in] use grad image operand

---

src/back/hlsl/writer.rs
src/back/msl/writer.rs
src/front/spv/image.rs
src/valid/expression.rs
tests/out/analysis/shadow.info.ron
tests/out/hlsl/quad-vert.hlsl
tests/out/ir/shadow.ron

revealed from vange-rs testing on latest wgpu
The last commit fixes a regression from #1189

Various HLSL fixes

---

src/back/hlsl/writer.rs
src/front/wgsl/mod.rs
tests/in/globals.wgsl
tests/out/glsl/globals.main.Compute.glsl
tests/out/hlsl/globals.hlsl
tests/out/msl/globals.msl
tests/out/spv/globals.spvasm
tests/out/wgsl/globals.wgsl

Fixes #1194
Comes with a test!

Fix atomic stores in WGSL

---

src/back/msl/writer.rs

[msl-out] pass-through workgroup storage

---

src/front/spv/mod.rs

Fixes #1196
This was regressed by #1142
Not tested much

[spv-in] work around storage image access

---

src/back/msl/writer.rs

[msl-out] insert padding struct initialization

---

src/back/hlsl/mod.rs
src/back/hlsl/storage.rs
src/back/hlsl/writer.rs
tests/out/hlsl/access.hlsl
tests/out/hlsl/shadow.hlsl
tests/out/hlsl/skybox.hlsl

Fixes one part of the issues I'm having with rend3. This now matches the behavior of vulkan exactly.

[hlsl-out] Fix reading from mat3

---

CHANGELOG.md
src/back/glsl/mod.rs
src/back/hlsl/conv.rs
src/back/hlsl/writer.rs
src/back/msl/mod.rs
src/back/spv/writer.rs
src/back/wgsl/writer.rs
src/front/glsl/variables.rs
src/front/spv/convert.rs
src/front/wgsl/conv.rs
src/lib.rs
src/valid/analyzer.rs
src/valid/interface.rs
tests/in/interface.param.ron
tests/in/interface.wgsl
tests/out/hlsl/interface.hlsl
tests/out/hlsl/skybox.hlsl
tests/out/msl/interface.msl
tests/out/spv/interface.spvasm
tests/out/wgsl/interface.wgsl

See https://github.com/gpuweb/gpuweb/pull/1684 and https://github.com/gpuweb/gpuweb/pull/944
It's mostly straightforward, except for HLSL, where it requires host API collaboration. Just like with base instance/vertex, the host API needs to provide the info in the root signature.

Support num_workgroups builtin

---

CHANGELOG.md
Cargo.toml
src/back/spv/writer.rs

The SPIRV capabilities stuff is a bit of a regression because of the new `spirv` crate, but it's not critical.

Release v0.10 version, changelog, and spirv update

---

src/back/hlsl/writer.rs
tests/out/hlsl/quad-vert.hlsl

[hlsl-out] fix array arguments in functions

---

src/back/hlsl/writer.rs

[hlsl-out] Fix pointer-to-array arguments

---

src/front/wgsl/mod.rs

[wgsl-in] Add support for the dereference operator

---

src/back/spv/writer.rs
tests/out/spv/image.spvasm

[spv-out] Request Sample1D capability when texture_1d is used.

---

src/front/glsl/lex.rs
src/front/glsl/parser/types.rs
src/front/glsl/token.rs

[glsl-in] parse shared qualifier

---

src/front/glsl/builtins.rs

Similar to #1203
glsl allows for shadow textures to be sampled to `textureGrad` but validation doesn't allow it because some backends like hlsl don't support it.
To fix this a warning is emitted and the level is set `SampleLevel::Zero` instead of `SampleLevel::Gradients`

[glsl-in] Cast grad sampling on shadow image into zero sampling

---

src/front/glsl/variables.rs

[glsl-in] Add support for more builtins

---

src/back/wgsl/writer.rs
src/front/wgsl/mod.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/operators.hlsl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl

Resolves #1229.
Implements `bitcast<type>(expression)` for the WGSL frontend and backend.
let me know if I got this right! It works in my project. :)

[wgsl-in] [wgsl-out] Implement bitcast()

---

src/front/glsl/builtins.rs

[glsl-in] Add support for float encoding/decoding builtins

---

src/front/spv/mod.rs

[spv-in] fix expression emit in image store

---

src/back/msl/writer.rs

Found and tested on `rend3` dev branch cube sample

[msl-out] Fix gradient sampling typo

---

src/front/glsl/builtins.rs

[glsl-in] Add support for derivative functions

---

src/back/glsl/mod.rs

[glsl-out] Modulo operator on float must be converted to mod function

---

Cargo.toml

Update deps petgraph and rose-tree

---

src/front/glsl/parser/functions.rs

Tentative fix for https://github.com/gfx-rs/naga/issues/1277

[glsl-in] Avoid infinite loop when parsing invalid statements

---

.github/workflows/pipeline.yml
CHANGELOG.md
Cargo.toml
README.md
src/back/glsl/mod.rs
src/back/hlsl/mod.rs
src/back/hlsl/writer.rs
src/back/msl/writer.rs
src/front/spv/function.rs
src/front/spv/image.rs
src/front/spv/mod.rs
tests/in/control-flow.wgsl
tests/out/glsl/control-flow.main.Compute.glsl
tests/out/hlsl/access.hlsl
tests/out/hlsl/boids.hlsl
tests/out/hlsl/collatz.hlsl
tests/out/hlsl/control-flow.hlsl
tests/out/hlsl/image.hlsl
tests/out/hlsl/interface.hlsl
tests/out/hlsl/interpolate.hlsl
tests/out/hlsl/quad-vert.hlsl
tests/out/hlsl/quad.hlsl
tests/out/hlsl/shadow.hlsl
tests/out/hlsl/skybox.hlsl
tests/out/hlsl/standard.hlsl
tests/out/msl/control-flow.msl
tests/out/wgsl/control-flow.wgsl
tests/snapshots.rs

Includes #1239, #1240, #1265, #1270, #1271, #1274, #1276, #1282, #1283, #1285, #1289

[0.6] Release 0.6.1

---

src/back/hlsl/writer.rs

Fix https://github.com/gfx-rs/wgpu/issues/1870

[hlsl-out] Fix output struct member names

---

src/back/hlsl/help.rs
src/back/hlsl/mod.rs
src/back/hlsl/writer.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/interface.hlsl
tests/out/hlsl/operators.hlsl
tests/out/hlsl/quad-vert.hlsl
tests/out/hlsl/quad.hlsl
tests/out/hlsl/skybox.hlsl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl

hlsl: implement struct constructors

---

src/front/spv/image.rs

Despite the spec not making any allusion to this, glslang produces spirv that expects this behavior and spirv_cross reads them this way.

[spv-in] Divide the depth ref in projection sample

---

src/front/wgsl/mod.rs
tests/in/operators.wgsl

Matches https://github.com/gpuweb/gpuweb/pull/2053

Infer types of module-scope let declarations

---

src/back/spv/mod.rs
src/back/spv/writer.rs
tests/snapshots.rs

Fixes #1331 (need testing/confirmation!)

spv-out: option to skip OpName for varyings

---

CHANGELOG.md
Cargo.toml
src/back/glsl/mod.rs
src/back/hlsl/help.rs
src/back/hlsl/mod.rs
src/back/hlsl/storage.rs
src/back/hlsl/writer.rs
src/back/mod.rs
src/back/msl/writer.rs
src/back/spv/mod.rs
src/back/spv/writer.rs
src/back/wgsl/writer.rs
src/front/glsl/offset.rs
src/front/glsl/parser/declarations.rs
src/front/mod.rs
src/front/spv/image.rs
src/front/spv/mod.rs
src/front/wgsl/mod.rs
src/valid/mod.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/interface.hlsl
tests/out/hlsl/operators.hlsl
tests/out/hlsl/quad-vert.hlsl
tests/out/hlsl/quad.hlsl
tests/out/hlsl/skybox.hlsl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl
tests/snapshots.rs

Includes #1319, #1321, #1323, #1325, #1326, #1327, #1330, #1333, #1334

Release v0.6.3

---

src/back/wgsl/writer.rs

Fixes #1322.
This still needs tests, so, marking it as a draft, but comments welcome.

[wgsl-out] Correct production of `*` and `&` operators.

---

src/back/hlsl/help.rs
tests/out/hlsl/image.hlsl

hlsl: avoid using texture keyword

---

src/back/msl/writer.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/operators.hlsl
tests/out/msl/access.msl
tests/out/msl/image.msl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl

msl-out: fix as_type expressions

---

src/front/spv/mod.rs
tests/snapshots.rs

Those review comments by Github are sure annoying, let's put an end to them.

Fix warnings in snapshots and spv-in

---

src/front/glsl/builtins.rs
src/front/glsl/types.rs
tests/in/glsl/samplers.frag
tests/out/wgsl/samplers-frag.wgsl

Partially solves #1354. Still need to write tests.

[glsl-in] Add support for a large number of texture sample overrides

---

src/front/glsl/parser/functions.rs

[glsl-in] Cast switch selector to int if it's uint

---

tests/in/glsl/global-constant-array.vert
tests/out/wgsl/global-constant-array-vert.wgsl

Folllow up to #1380
I didn't find a test shader to add this to, so I created a new one

[glsl-in] Add test for array constant dynamic indexing

---

src/front/spv/function.rs

[spv-in] Allow OpLine anywhere in the function

---

src/front/wgsl/lexer.rs

[wgsl-in] Disallow identifiers starting with _

---

src/valid/function.rs
tests/wgsl-errors.rs

Implements the missing part of gpuweb/gpuweb#2096 (tracking accross compund statements)
Closes #1019

Track finished across compound statements

---

src/front/glsl/functions.rs
src/front/glsl/parser/expressions.rs
tests/in/glsl/expressions.frag
tests/out/wgsl/expressions-frag.wgsl

Fixes some issues around type constructors:
- Allow use of constructors for user types
- Allow array constructors
Each commit passes CI and can be reviewed separately

[glsl-in] Type constructors improvements

---

src/proc/typifier.rs

Previously the typifier flagged all relational functions as producing a
scalar boolean but with the exception of `all` and `any`, according to
the wgsl spec, all other relational functions output a type the same
size as the input.
Furthermore all target languages support this out of the box:
- MSL - see the official spec at page 143, table 6.3
- HLSL - [`isinf`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-isinf), [`isfinite`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-isfinite), [`isnan`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-isnan), from what I could find there's no `isnormal` function so this seems like a problem in the backend.
- GLSL - …

[Typifier] Some relational functions output vectors

---

src/proc/namer.rs

Eliminate `Namer::namespace_index` and remove namespace indices from `Namer::unique` keys. Instead, implement `Namer::namespace` by just swapping in a fresh table for the duration of the call.
Create the fresh hash table with the right initial capacity. The prior implementation did manage to avoid allocations by sharing a hash table, and we'd like to not lose that advantage entirely.
This has no effect on generated code.

Simplify implementation of `Namer::namespace`.

---

src/front/glsl/parser/types.rs
tests/out/wgsl/bevy-pbr-frag.wgsl
tests/out/wgsl/constant-array-size-vert.wgsl
tests/out/wgsl/expressions-frag.wgsl
tests/out/wgsl/global-constant-array-vert.wgsl

[glsl-in] Always use uint for array size

---

.github/workflows/lazy.yml
src/valid/function.rs

It was failing to build if `validate` was enabled without `span`. Now CI checked.

Fix span includes into function validation

---

src/front/glsl/constants.rs

In `src/fornt/glsl/constants.rs`, the following:
```
Ok(self.constants.fetch_or_append(
Constant {
name: None,
specialization: None,
inner,
},
span,
))
```
was called repetitively.
I added `ConstantSolver::register_constant(&mut self, ConstantInner, Span)`
that returns `Handle<Constant>` to reduce repetition.

 [glsl-in] Add a helper function to reduce repetition

---

src/front/glsl/constants.rs

Forces wrapping for all operations, except that for division/remainder when `rhs == 0` the result will be `0`.
Closes #1496

[glsl-in] Don't panic on UB integer operations

---

Cargo.toml
tests/snapshots.rs

Update dev dependencies:
1. rspirv 0.10 -> 0.11
2. ron 0.6 -> 0.7
3. env_logger 0.8 -> 0.9

Update dev dependencies

---

Cargo.toml
src/front/spv/mod.rs
src/lib.rs

See gfx-rs/rspirv#221 for the rationale behind this change

Switch to rustc-hash

---

src/back/wgsl/mod.rs
src/back/wgsl/writer.rs
src/front/wgsl/conv.rs

[wgsl] Remove IsInf and IsNan

---

tests/snapshots.rs

Follow-up to #422 to address the lazy failure

Fix shapshots to run without deserialize feature

---

tests/out/glsl/interpolate.frag_main.Fragment.glsl
tests/out/glsl/interpolate.vert_main.Vertex.glsl
tests/out/glsl/quad.frag_main.Fragment.glsl
tests/out/glsl/quad.vert_main.Vertex.glsl

Just ran `make`, not sure why they are missing.

Add missing GLSL tests

---

src/front/glsl/context.rs
tests/in/glsl/swizzle_write.frag
tests/out/wgsl/swizzle_write-frag.wgsl

glsl-in: fix pre/postfix ops on swizzles

---

CHANGELOG.md
Cargo.toml
src/back/glsl/mod.rs
src/back/spv/block.rs
src/back/wgsl/writer.rs
src/front/wgsl/conv.rs
tests/out/spv/bits.spvasm

Backports v0.7.3

---

src/back/glsl/mod.rs
src/back/spv/block.rs
src/valid/expression.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/operators.hlsl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl

Straightforward change in the validator only spirv and glsl need to be patched since they don't accept it, most of the changes is tests
Closes #1574

Implement bitwise Or/And for booleans

---

src/front/spv/mod.rs

This needs to be handled this  way because when both branches are equal the spirv doesn't need a `OpSelectionMerge` so this could cause a huge amount of duplication in the two branches.
Closes #1588

spv-in: Remove if when both branches are equal

---

src/front/spv/mod.rs

spv-in: Allow branch weights in OpBranchConditional

---

src/back/spv/writer.rs
src/front/spv/mod.rs
src/valid/expression.rs

Fixes a regression from #1603
Addresses half of #1605
cc @JCapucho

Enforce casting width better, fix IEqual/INotEqual in spv

---

src/back/spv/helpers.rs
tests/out/spv/extra.spvasm

spv-out: Force wrapping of push constant structs

---

src/front/spv/mod.rs

Only adds support for unspecialized arrays
Closes #1591

spv-in: Implement CompositeInsert for arrays

---

src/front/glsl/parser/declarations.rs
src/front/glsl/parser/functions.rs

glsl-in: Cull the body of do while if needed

---

src/front/wgsl/mod.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/operators.hlsl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl

wgsl-in: Implement matrix construction from scalar

---

src/back/msl/writer.rs
tests/in/globals.wgsl
tests/out/glsl/globals.main.Compute.glsl
tests/out/hlsl/globals.hlsl
tests/out/msl/globals.msl
tests/out/spv/globals.spvasm
tests/out/wgsl/globals.wgsl
tests/snapshots.rs

msl: fix packed float support

---

src/valid/interface.rs

Fixes https://github.com/gfx-rs/wgpu/issues/2351

Validate structure resource types

---

src/back/glsl/mod.rs
tests/in/globals.wgsl
tests/out/glsl/globals.main.Compute.glsl
tests/out/hlsl/globals.hlsl
tests/out/msl/globals.msl
tests/out/spv/globals.spvasm
tests/out/wgsl/globals.wgsl

gl-out: skip unsized types if unused

---

src/front/spv/mod.rs

spv-in: OpVectorInsertDynamic allow unsigned index

---

src/front/wgsl/lexer.rs
src/front/wgsl/mod.rs
tests/in/operators.wgsl
tests/out/glsl/operators.main.Compute.glsl
tests/out/hlsl/operators.hlsl
tests/out/msl/operators.msl
tests/out/spv/operators.spvasm
tests/out/wgsl/operators.wgsl

Matches https://github.com/gpuweb/gpuweb/pull/2345 and prior stuff
Doesn't get represented in IR, only resolved as WGSL frontend sugar. We can reconsider this later if wanted.

WGSL: assignment binary operators

---

src/back/hlsl/storage.rs
src/back/msl/writer.rs
src/front/glsl/functions.rs
src/front/glsl/types.rs
src/front/spv/mod.rs
src/proc/layouter.rs
src/proc/mod.rs
src/valid/type.rs

layouter: let size() panic

---

src/back/glsl/mod.rs

Whoops
Closes: https://github.com/BVE-Reborn/rend3/issues/335

glsl: floatBitsToUint spelling

---

CHANGELOG.md
Cargo.toml
src/back/msl/writer.rs
tests/in/skybox.param.ron
tests/out/msl/skybox.msl

Release 0.8.5

---

src/back/glsl/mod.rs
src/back/mod.rs
src/back/msl/writer.rs
src/lib.rs

This unused type warning was annoying :)
Follow-up to #1689

Move NeedBakeExpressions into backends

---

src/back/msl/writer.rs

required for https://github.com/gfx-rs/wgpu/issues/2458
follow-up to #1717

msl: fix resource bindings for non-structures

---

src/back/msl/writer.rs
tests/out/msl/image.msl

Just a cleanup. One small change to the snapshots, probably necessary.

[msl-out] Consolidate numeric type formatting.

---

src/back/hlsl/help.rs
src/back/hlsl/writer.rs

Validation insures that `ImageLoad` expressions always have an `index` operand when the image's type requires it, so there is no need for `MipLevelCoordinate::Zero`. This means that `Option<Handle<Expression>>` serves adequately for this case.

[hlsl-out] Remove `MipLevelCoordinate` type.

---

src/back/msl/keywords.rs
src/back/msl/writer.rs
src/proc/index.rs
tests/out/msl/bounds-check-image-restrict.msl
tests/out/msl/bounds-check-image-rzsw.msl
tests/out/msl/image.msl
tests/out/msl/policy-mix.msl
tests/snapshots.rs

Posted early for silly reasons. ImageStore coming tomorrow. Comments welcome, of course.

[msl-out] Implement bounds checks for ImageLoad and ImageStore

---

src/back/msl/writer.rs
tests/in/extra.param.ron
tests/in/extra.wgsl
tests/out/msl/extra.msl
tests/out/spv/extra.spvasm
tests/out/wgsl/extra.wgsl

Actually test push constants to be used

---

CHANGELOG.md
src/back/wgsl/writer.rs
src/front/wgsl/conv.rs

Spec PR: https://github.com/gpuweb/gpuweb/pull/2712

[wgsl] Rename smoothStep to smoothstep

---

src/front/wgsl/mod.rs
src/front/wgsl/tests.rs

Spec PR: https://github.com/gpuweb/gpuweb/pull/2711

[wgsl] Make colon in case optional

---

src/valid/type.rs

fixes #1414
fixes #1299
fixes #1691
The examples in the [spec](https://gpuweb.github.io/gpuweb/wgsl/#address-space-layout-constraints) are now handled properly.

Validate uniform address space layout constraints

---

README.md

Update status of the HLSL backend as previously discussed on matrix. :ok: -> :white_check_mark:

Update `hlsl-out` status in README

---

Cargo.toml
src/front/wgsl/lexer.rs
src/front/wgsl/mod.rs

https://gpuweb.github.io/gpuweb/wgsl/#textual-structure

[wgsl-in] Update lexer to match more unicode characters

---

src/valid/interface.rs

When `VaryingContext::validate` discovers that it needs to examine each member of a struct, pass the type as an argument to `validate` and `validate_impl`, rather than mutating `self.ty` on each iteration of the loop. This matches the way we're handling the binding, and avoids stashing per-iteration state in a surprising place.
This should have no effect on execution.

Simplify type handling in VaryingContext.

---

src/front/glsl/parser.rs

Purely aesthetic. If it's not to your taste, feel free to turn it down.

[glsl-in] Simplify control flow in search for `main`.

---

src/keywords/wgsl.rs

Spec PR https://github.com/gpuweb/gpuweb/pull/2833

[wgsl] Reserve binding_array

---

src/valid/mod.rs

I somehow completely forgot how bitflags worked. Ah well.

[valid] Fix bitflag assignments

---

src/back/hlsl/help.rs
tests/out/hlsl/access.hlsl

Fixes FXC `error X3533: non-empty case statements must have break or return`

[hlsl-out] Fix missing break statements (for FXC)

---

src/front/spv/mod.rs

spv-in: Implement OpBitReverse and OpBitCount

---

.github/workflows/pipeline.yml

Also, the documentation job probably doesn't need Clippy.

Verify in CI that benchmarks build.

---

src/proc/layouter.rs

Per discussion in #1979. I accidentally merged the PR before the revisions had been made.

[wgsl-in] Restore error in the case of bad scalar widths.

---

CHANGELOG.md
Cargo.toml
cli/Cargo.toml

This pushes the release for 0.10.

Add changelog and bump version to 0.10

---

src/front/glsl/constants.rs
src/lib.rs

Just followed the suggestions offered by the checking tools causing CI to fail. Haven't taken time to determine where this got introduced yet.

Resolve CI failures in `master`

---

tests/out/wgsl/931-constant-emitting-vert.wgsl
tests/out/wgsl/bevy-pbr-frag.wgsl
tests/out/wgsl/constant-array-size-vert.wgsl
tests/out/wgsl/expressions-frag.wgsl
tests/out/wgsl/global-constant-array-vert.wgsl
tests/out/wgsl/quad_glsl-vert.wgsl

Fix for CI failing.
CI for https://github.com/gfx-rs/naga/pull/2205 hasn't run after we merged https://github.com/gfx-rs/naga/pull/2075.

Update test snapshots

---

.github/workflows/lazy.yml

see https://github.com/gfx-rs/naga/actions/runs/4008734121/jobs/6883263240 for a successful run

Fix CI, install `cargo-tarpaulin` via `cargo-binstall`

---

fuzz/fuzz_targets/glsl_parser.rs
fuzz/fuzz_targets/spv_parser.rs
fuzz/fuzz_targets/wgsl_parser.rs

Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55648

fuzz: fix build failure

---

CHANGELOG.md

Add changelog for v0.12

---

src/valid/mod.rs

refactor(valid)!: remove unneeded `ConstantError::Unresolved{Component,Size}`

---

xtask/hlsl-snapshots/Cargo.toml
xtask/src/cli.rs

[`wgpu`#3844](https://github.com/gfx-rs/wgpu/pull/3844)

Refine `xtask` based on feedback from `wgpu`#3844

---

cli/src/bin/naga.rs
src/back/spv/mod.rs

fix(spv-out-debug): fix debug options

---

CHANGELOG.md

closes https://github.com/gfx-rs/naga/issues/2409
cc @cwfitzgerald

Add v0.13 changelog + minor version bumps of previous versions

---

src/back/spv/writer.rs

This was added in ad28396851aa4229d228b16594bba7a3fd8d84a3.

spv-out: Remove empty else branch.

---

src/valid/interface.rs
tests/wgsl-errors.rs

Fixes https://github.com/gfx-rs/naga/issues/2512.

Validate variable initializer for address spaces

---

src/back/glsl/features.rs

Was added in https://github.com/gfx-rs/naga/pull/1398 (most likely due to a double paste).

Remove duplicated code

---

src/front/wgsl/parse/conv.rs

[wgsl-in] Parse the bgra8unorm storage format

---

.github/CODEOWNERS

This kickstarts the tem based workflow in naga

Add Codeowners File
